// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: basicTypes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URL_Platform int32

const (
	URL_PLATFORM_UNKNOWN URL_Platform = 0
	URL_PLATFORM_MACOS   URL_Platform = 1
	URL_PLATFORM_WIN32   URL_Platform = 2
	URL_PLATFORM_WEB     URL_Platform = 3
)

// Enum value maps for URL_Platform.
var (
	URL_Platform_name = map[int32]string{
		0: "PLATFORM_UNKNOWN",
		1: "PLATFORM_MACOS",
		2: "PLATFORM_WIN32",
		3: "PLATFORM_WEB",
	}
	URL_Platform_value = map[string]int32{
		"PLATFORM_UNKNOWN": 0,
		"PLATFORM_MACOS":   1,
		"PLATFORM_WIN32":   2,
		"PLATFORM_WEB":     3,
	}
)

func (x URL_Platform) Enum() *URL_Platform {
	p := new(URL_Platform)
	*p = x
	return p
}

func (x URL_Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (URL_Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_basicTypes_proto_enumTypes[0].Descriptor()
}

func (URL_Platform) Type() protoreflect.EnumType {
	return &file_basicTypes_proto_enumTypes[0]
}

func (x URL_Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use URL_Platform.Descriptor instead.
func (URL_Platform) EnumDescriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{0, 0}
}

type URL_LocalRelativePath_Root int32

const (
	URL_LocalRelativePath_ROOT_UNKNOWN          URL_LocalRelativePath_Root = 0
	URL_LocalRelativePath_ROOT_BOOT_VOLUME      URL_LocalRelativePath_Root = 1
	URL_LocalRelativePath_ROOT_USER_HOME        URL_LocalRelativePath_Root = 2
	URL_LocalRelativePath_ROOT_USER_DOCUMENTS   URL_LocalRelativePath_Root = 3
	URL_LocalRelativePath_ROOT_USER_DOWNLOADS   URL_LocalRelativePath_Root = 4
	URL_LocalRelativePath_ROOT_USER_MUSIC       URL_LocalRelativePath_Root = 5
	URL_LocalRelativePath_ROOT_USER_PICTURES    URL_LocalRelativePath_Root = 6
	URL_LocalRelativePath_ROOT_USER_VIDEOS      URL_LocalRelativePath_Root = 7
	URL_LocalRelativePath_ROOT_USER_DESKTOP     URL_LocalRelativePath_Root = 11
	URL_LocalRelativePath_ROOT_USER_APP_SUPPORT URL_LocalRelativePath_Root = 8
	URL_LocalRelativePath_ROOT_SHARED           URL_LocalRelativePath_Root = 9
	URL_LocalRelativePath_ROOT_SHOW             URL_LocalRelativePath_Root = 10
	URL_LocalRelativePath_ROOT_CURRENT_RESOURCE URL_LocalRelativePath_Root = 12
)

// Enum value maps for URL_LocalRelativePath_Root.
var (
	URL_LocalRelativePath_Root_name = map[int32]string{
		0:  "ROOT_UNKNOWN",
		1:  "ROOT_BOOT_VOLUME",
		2:  "ROOT_USER_HOME",
		3:  "ROOT_USER_DOCUMENTS",
		4:  "ROOT_USER_DOWNLOADS",
		5:  "ROOT_USER_MUSIC",
		6:  "ROOT_USER_PICTURES",
		7:  "ROOT_USER_VIDEOS",
		11: "ROOT_USER_DESKTOP",
		8:  "ROOT_USER_APP_SUPPORT",
		9:  "ROOT_SHARED",
		10: "ROOT_SHOW",
		12: "ROOT_CURRENT_RESOURCE",
	}
	URL_LocalRelativePath_Root_value = map[string]int32{
		"ROOT_UNKNOWN":          0,
		"ROOT_BOOT_VOLUME":      1,
		"ROOT_USER_HOME":        2,
		"ROOT_USER_DOCUMENTS":   3,
		"ROOT_USER_DOWNLOADS":   4,
		"ROOT_USER_MUSIC":       5,
		"ROOT_USER_PICTURES":    6,
		"ROOT_USER_VIDEOS":      7,
		"ROOT_USER_DESKTOP":     11,
		"ROOT_USER_APP_SUPPORT": 8,
		"ROOT_SHARED":           9,
		"ROOT_SHOW":             10,
		"ROOT_CURRENT_RESOURCE": 12,
	}
)

func (x URL_LocalRelativePath_Root) Enum() *URL_LocalRelativePath_Root {
	p := new(URL_LocalRelativePath_Root)
	*p = x
	return p
}

func (x URL_LocalRelativePath_Root) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (URL_LocalRelativePath_Root) Descriptor() protoreflect.EnumDescriptor {
	return file_basicTypes_proto_enumTypes[1].Descriptor()
}

func (URL_LocalRelativePath_Root) Type() protoreflect.EnumType {
	return &file_basicTypes_proto_enumTypes[1]
}

func (x URL_LocalRelativePath_Root) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use URL_LocalRelativePath_Root.Descriptor instead.
func (URL_LocalRelativePath_Root) EnumDescriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{0, 0, 0}
}

type ApplicationInfo_Platform int32

const (
	ApplicationInfo_PLATFORM_UNDEFINED ApplicationInfo_Platform = 0
	ApplicationInfo_PLATFORM_MACOS     ApplicationInfo_Platform = 1
	ApplicationInfo_PLATFORM_WINDOWS   ApplicationInfo_Platform = 2
)

// Enum value maps for ApplicationInfo_Platform.
var (
	ApplicationInfo_Platform_name = map[int32]string{
		0: "PLATFORM_UNDEFINED",
		1: "PLATFORM_MACOS",
		2: "PLATFORM_WINDOWS",
	}
	ApplicationInfo_Platform_value = map[string]int32{
		"PLATFORM_UNDEFINED": 0,
		"PLATFORM_MACOS":     1,
		"PLATFORM_WINDOWS":   2,
	}
)

func (x ApplicationInfo_Platform) Enum() *ApplicationInfo_Platform {
	p := new(ApplicationInfo_Platform)
	*p = x
	return p
}

func (x ApplicationInfo_Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationInfo_Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_basicTypes_proto_enumTypes[2].Descriptor()
}

func (ApplicationInfo_Platform) Type() protoreflect.EnumType {
	return &file_basicTypes_proto_enumTypes[2]
}

func (x ApplicationInfo_Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationInfo_Platform.Descriptor instead.
func (ApplicationInfo_Platform) EnumDescriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{6, 0}
}

type ApplicationInfo_Application int32

const (
	ApplicationInfo_APPLICATION_UNDEFINED      ApplicationInfo_Application = 0
	ApplicationInfo_APPLICATION_PROPRESENTER   ApplicationInfo_Application = 1
	ApplicationInfo_APPLICATION_PVP            ApplicationInfo_Application = 2
	ApplicationInfo_APPLICATION_PROVIDEOSERVER ApplicationInfo_Application = 3
	ApplicationInfo_APPLICATION_SCOREBOARD     ApplicationInfo_Application = 4
)

// Enum value maps for ApplicationInfo_Application.
var (
	ApplicationInfo_Application_name = map[int32]string{
		0: "APPLICATION_UNDEFINED",
		1: "APPLICATION_PROPRESENTER",
		2: "APPLICATION_PVP",
		3: "APPLICATION_PROVIDEOSERVER",
		4: "APPLICATION_SCOREBOARD",
	}
	ApplicationInfo_Application_value = map[string]int32{
		"APPLICATION_UNDEFINED":      0,
		"APPLICATION_PROPRESENTER":   1,
		"APPLICATION_PVP":            2,
		"APPLICATION_PROVIDEOSERVER": 3,
		"APPLICATION_SCOREBOARD":     4,
	}
)

func (x ApplicationInfo_Application) Enum() *ApplicationInfo_Application {
	p := new(ApplicationInfo_Application)
	*p = x
	return p
}

func (x ApplicationInfo_Application) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationInfo_Application) Descriptor() protoreflect.EnumDescriptor {
	return file_basicTypes_proto_enumTypes[3].Descriptor()
}

func (ApplicationInfo_Application) Type() protoreflect.EnumType {
	return &file_basicTypes_proto_enumTypes[3]
}

func (x ApplicationInfo_Application) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationInfo_Application.Descriptor instead.
func (ApplicationInfo_Application) EnumDescriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{6, 1}
}

type MusicKeyScale_MusicKey int32

const (
	MusicKeyScale_MUSIC_KEY_A_FLAT  MusicKeyScale_MusicKey = 0
	MusicKeyScale_MUSIC_KEY_A       MusicKeyScale_MusicKey = 1
	MusicKeyScale_MUSIC_KEY_A_SHARP MusicKeyScale_MusicKey = 2
	MusicKeyScale_MUSIC_KEY_B_FLAT  MusicKeyScale_MusicKey = 3
	MusicKeyScale_MUSIC_KEY_B       MusicKeyScale_MusicKey = 4
	MusicKeyScale_MUSIC_KEY_B_SHARP MusicKeyScale_MusicKey = 5
	MusicKeyScale_MUSIC_KEY_C_FLAT  MusicKeyScale_MusicKey = 6
	MusicKeyScale_MUSIC_KEY_C       MusicKeyScale_MusicKey = 7
	MusicKeyScale_MUSIC_KEY_C_SHARP MusicKeyScale_MusicKey = 8
	MusicKeyScale_MUSIC_KEY_D_FLAT  MusicKeyScale_MusicKey = 9
	MusicKeyScale_MUSIC_KEY_D       MusicKeyScale_MusicKey = 10
	MusicKeyScale_MUSIC_KEY_D_SHARP MusicKeyScale_MusicKey = 11
	MusicKeyScale_MUSIC_KEY_E_FLAT  MusicKeyScale_MusicKey = 12
	MusicKeyScale_MUSIC_KEY_E       MusicKeyScale_MusicKey = 13
	MusicKeyScale_MUSIC_KEY_E_SHARP MusicKeyScale_MusicKey = 14
	MusicKeyScale_MUSIC_KEY_F_FLAT  MusicKeyScale_MusicKey = 15
	MusicKeyScale_MUSIC_KEY_F       MusicKeyScale_MusicKey = 16
	MusicKeyScale_MUSIC_KEY_F_SHARP MusicKeyScale_MusicKey = 17
	MusicKeyScale_MUSIC_KEY_G_FLAT  MusicKeyScale_MusicKey = 18
	MusicKeyScale_MUSIC_KEY_G       MusicKeyScale_MusicKey = 19
	MusicKeyScale_MUSIC_KEY_G_SHARP MusicKeyScale_MusicKey = 20
)

// Enum value maps for MusicKeyScale_MusicKey.
var (
	MusicKeyScale_MusicKey_name = map[int32]string{
		0:  "MUSIC_KEY_A_FLAT",
		1:  "MUSIC_KEY_A",
		2:  "MUSIC_KEY_A_SHARP",
		3:  "MUSIC_KEY_B_FLAT",
		4:  "MUSIC_KEY_B",
		5:  "MUSIC_KEY_B_SHARP",
		6:  "MUSIC_KEY_C_FLAT",
		7:  "MUSIC_KEY_C",
		8:  "MUSIC_KEY_C_SHARP",
		9:  "MUSIC_KEY_D_FLAT",
		10: "MUSIC_KEY_D",
		11: "MUSIC_KEY_D_SHARP",
		12: "MUSIC_KEY_E_FLAT",
		13: "MUSIC_KEY_E",
		14: "MUSIC_KEY_E_SHARP",
		15: "MUSIC_KEY_F_FLAT",
		16: "MUSIC_KEY_F",
		17: "MUSIC_KEY_F_SHARP",
		18: "MUSIC_KEY_G_FLAT",
		19: "MUSIC_KEY_G",
		20: "MUSIC_KEY_G_SHARP",
	}
	MusicKeyScale_MusicKey_value = map[string]int32{
		"MUSIC_KEY_A_FLAT":  0,
		"MUSIC_KEY_A":       1,
		"MUSIC_KEY_A_SHARP": 2,
		"MUSIC_KEY_B_FLAT":  3,
		"MUSIC_KEY_B":       4,
		"MUSIC_KEY_B_SHARP": 5,
		"MUSIC_KEY_C_FLAT":  6,
		"MUSIC_KEY_C":       7,
		"MUSIC_KEY_C_SHARP": 8,
		"MUSIC_KEY_D_FLAT":  9,
		"MUSIC_KEY_D":       10,
		"MUSIC_KEY_D_SHARP": 11,
		"MUSIC_KEY_E_FLAT":  12,
		"MUSIC_KEY_E":       13,
		"MUSIC_KEY_E_SHARP": 14,
		"MUSIC_KEY_F_FLAT":  15,
		"MUSIC_KEY_F":       16,
		"MUSIC_KEY_F_SHARP": 17,
		"MUSIC_KEY_G_FLAT":  18,
		"MUSIC_KEY_G":       19,
		"MUSIC_KEY_G_SHARP": 20,
	}
)

func (x MusicKeyScale_MusicKey) Enum() *MusicKeyScale_MusicKey {
	p := new(MusicKeyScale_MusicKey)
	*p = x
	return p
}

func (x MusicKeyScale_MusicKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MusicKeyScale_MusicKey) Descriptor() protoreflect.EnumDescriptor {
	return file_basicTypes_proto_enumTypes[4].Descriptor()
}

func (MusicKeyScale_MusicKey) Type() protoreflect.EnumType {
	return &file_basicTypes_proto_enumTypes[4]
}

func (x MusicKeyScale_MusicKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MusicKeyScale_MusicKey.Descriptor instead.
func (MusicKeyScale_MusicKey) EnumDescriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{8, 0}
}

type MusicKeyScale_MusicScale int32

const (
	MusicKeyScale_MUSIC_SCALE_MAJOR MusicKeyScale_MusicScale = 0
	MusicKeyScale_MUSIC_SCALE_MINOR MusicKeyScale_MusicScale = 1
)

// Enum value maps for MusicKeyScale_MusicScale.
var (
	MusicKeyScale_MusicScale_name = map[int32]string{
		0: "MUSIC_SCALE_MAJOR",
		1: "MUSIC_SCALE_MINOR",
	}
	MusicKeyScale_MusicScale_value = map[string]int32{
		"MUSIC_SCALE_MAJOR": 0,
		"MUSIC_SCALE_MINOR": 1,
	}
)

func (x MusicKeyScale_MusicScale) Enum() *MusicKeyScale_MusicScale {
	p := new(MusicKeyScale_MusicScale)
	*p = x
	return p
}

func (x MusicKeyScale_MusicScale) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MusicKeyScale_MusicScale) Descriptor() protoreflect.EnumDescriptor {
	return file_basicTypes_proto_enumTypes[5].Descriptor()
}

func (MusicKeyScale_MusicScale) Type() protoreflect.EnumType {
	return &file_basicTypes_proto_enumTypes[5]
}

func (x MusicKeyScale_MusicScale) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MusicKeyScale_MusicScale.Descriptor instead.
func (MusicKeyScale_MusicScale) EnumDescriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{8, 1}
}

type URL struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Platform URL_Platform           `protobuf:"varint,3,opt,name=platform,proto3,enum=rv.data.URL_Platform" json:"platform,omitempty"`
	// Types that are valid to be assigned to Storage:
	//
	//	*URL_AbsoluteString
	//	*URL_RelativePath
	Storage isURL_Storage `protobuf_oneof:"Storage"`
	// Types that are valid to be assigned to RelativeFilePath:
	//
	//	*URL_Local
	//	*URL_External
	RelativeFilePath isURL_RelativeFilePath `protobuf_oneof:"RelativeFilePath"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_basicTypes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{0}
}

func (x *URL) GetPlatform() URL_Platform {
	if x != nil {
		return x.Platform
	}
	return URL_PLATFORM_UNKNOWN
}

func (x *URL) GetStorage() isURL_Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *URL) GetAbsoluteString() string {
	if x != nil {
		if x, ok := x.Storage.(*URL_AbsoluteString); ok {
			return x.AbsoluteString
		}
	}
	return ""
}

func (x *URL) GetRelativePath() string {
	if x != nil {
		if x, ok := x.Storage.(*URL_RelativePath); ok {
			return x.RelativePath
		}
	}
	return ""
}

func (x *URL) GetRelativeFilePath() isURL_RelativeFilePath {
	if x != nil {
		return x.RelativeFilePath
	}
	return nil
}

func (x *URL) GetLocal() *URL_LocalRelativePath {
	if x != nil {
		if x, ok := x.RelativeFilePath.(*URL_Local); ok {
			return x.Local
		}
	}
	return nil
}

func (x *URL) GetExternal() *URL_ExternalRelativePath {
	if x != nil {
		if x, ok := x.RelativeFilePath.(*URL_External); ok {
			return x.External
		}
	}
	return nil
}

type isURL_Storage interface {
	isURL_Storage()
}

type URL_AbsoluteString struct {
	AbsoluteString string `protobuf:"bytes,1,opt,name=absolute_string,json=absoluteString,proto3,oneof"`
}

type URL_RelativePath struct {
	RelativePath string `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3,oneof"`
}

func (*URL_AbsoluteString) isURL_Storage() {}

func (*URL_RelativePath) isURL_Storage() {}

type isURL_RelativeFilePath interface {
	isURL_RelativeFilePath()
}

type URL_Local struct {
	Local *URL_LocalRelativePath `protobuf:"bytes,4,opt,name=local,proto3,oneof"`
}

type URL_External struct {
	External *URL_ExternalRelativePath `protobuf:"bytes,5,opt,name=external,proto3,oneof"`
}

func (*URL_Local) isURL_RelativeFilePath() {}

func (*URL_External) isURL_RelativeFilePath() {}

type URLs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URL                 `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLs) Reset() {
	*x = URLs{}
	mi := &file_basicTypes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLs) ProtoMessage() {}

func (x *URLs) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLs.ProtoReflect.Descriptor instead.
func (*URLs) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{1}
}

func (x *URLs) GetUrls() []*URL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	String_       string                 `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_basicTypes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{2}
}

func (x *UUID) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

type IntRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntRange) Reset() {
	*x = IntRange{}
	mi := &file_basicTypes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntRange) ProtoMessage() {}

func (x *IntRange) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntRange.ProtoReflect.Descriptor instead.
func (*IntRange) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{3}
}

func (x *IntRange) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *IntRange) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Red           float32                `protobuf:"fixed32,1,opt,name=red,proto3" json:"red,omitempty"`
	Green         float32                `protobuf:"fixed32,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue          float32                `protobuf:"fixed32,3,opt,name=blue,proto3" json:"blue,omitempty"`
	Alpha         float32                `protobuf:"fixed32,4,opt,name=alpha,proto3" json:"alpha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_basicTypes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{4}
}

func (x *Color) GetRed() float32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *Color) GetGreen() float32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *Color) GetBlue() float32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

func (x *Color) GetAlpha() float32 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MajorVersion  uint32                 `protobuf:"varint,1,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	MinorVersion  uint32                 `protobuf:"varint,2,opt,name=minor_version,json=minorVersion,proto3" json:"minor_version,omitempty"`
	PatchVersion  uint32                 `protobuf:"varint,3,opt,name=patch_version,json=patchVersion,proto3" json:"patch_version,omitempty"`
	Build         string                 `protobuf:"bytes,4,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_basicTypes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{5}
}

func (x *Version) GetMajorVersion() uint32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *Version) GetMinorVersion() uint32 {
	if x != nil {
		return x.MinorVersion
	}
	return 0
}

func (x *Version) GetPatchVersion() uint32 {
	if x != nil {
		return x.PatchVersion
	}
	return 0
}

func (x *Version) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

type ApplicationInfo struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	Platform           ApplicationInfo_Platform    `protobuf:"varint,1,opt,name=platform,proto3,enum=rv.data.ApplicationInfo_Platform" json:"platform,omitempty"`
	PlatformVersion    *Version                    `protobuf:"bytes,2,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`
	Application        ApplicationInfo_Application `protobuf:"varint,3,opt,name=application,proto3,enum=rv.data.ApplicationInfo_Application" json:"application,omitempty"`
	ApplicationVersion *Version                    `protobuf:"bytes,4,opt,name=application_version,json=applicationVersion,proto3" json:"application_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplicationInfo) Reset() {
	*x = ApplicationInfo{}
	mi := &file_basicTypes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationInfo) ProtoMessage() {}

func (x *ApplicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationInfo.ProtoReflect.Descriptor instead.
func (*ApplicationInfo) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{6}
}

func (x *ApplicationInfo) GetPlatform() ApplicationInfo_Platform {
	if x != nil {
		return x.Platform
	}
	return ApplicationInfo_PLATFORM_UNDEFINED
}

func (x *ApplicationInfo) GetPlatformVersion() *Version {
	if x != nil {
		return x.PlatformVersion
	}
	return nil
}

func (x *ApplicationInfo) GetApplication() ApplicationInfo_Application {
	if x != nil {
		return x.Application
	}
	return ApplicationInfo_APPLICATION_UNDEFINED
}

func (x *ApplicationInfo) GetApplicationVersion() *Version {
	if x != nil {
		return x.ApplicationVersion
	}
	return nil
}

type CollectionElementType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParameterUuid *UUID                  `protobuf:"bytes,1,opt,name=parameter_uuid,json=parameterUuid,proto3" json:"parameter_uuid,omitempty"`
	ParameterName string                 `protobuf:"bytes,2,opt,name=parameter_name,json=parameterName,proto3" json:"parameter_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionElementType) Reset() {
	*x = CollectionElementType{}
	mi := &file_basicTypes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionElementType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionElementType) ProtoMessage() {}

func (x *CollectionElementType) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionElementType.ProtoReflect.Descriptor instead.
func (*CollectionElementType) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{7}
}

func (x *CollectionElementType) GetParameterUuid() *UUID {
	if x != nil {
		return x.ParameterUuid
	}
	return nil
}

func (x *CollectionElementType) GetParameterName() string {
	if x != nil {
		return x.ParameterName
	}
	return ""
}

type MusicKeyScale struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	MusicKey      MusicKeyScale_MusicKey   `protobuf:"varint,1,opt,name=music_key,json=musicKey,proto3,enum=rv.data.MusicKeyScale_MusicKey" json:"music_key,omitempty"`
	MusicScale    MusicKeyScale_MusicScale `protobuf:"varint,2,opt,name=music_scale,json=musicScale,proto3,enum=rv.data.MusicKeyScale_MusicScale" json:"music_scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MusicKeyScale) Reset() {
	*x = MusicKeyScale{}
	mi := &file_basicTypes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicKeyScale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicKeyScale) ProtoMessage() {}

func (x *MusicKeyScale) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicKeyScale.ProtoReflect.Descriptor instead.
func (*MusicKeyScale) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{8}
}

func (x *MusicKeyScale) GetMusicKey() MusicKeyScale_MusicKey {
	if x != nil {
		return x.MusicKey
	}
	return MusicKeyScale_MUSIC_KEY_A_FLAT
}

func (x *MusicKeyScale) GetMusicScale() MusicKeyScale_MusicScale {
	if x != nil {
		return x.MusicScale
	}
	return MusicKeyScale_MUSIC_SCALE_MAJOR
}

type URL_LocalRelativePath struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Root          URL_LocalRelativePath_Root `protobuf:"varint,1,opt,name=root,proto3,enum=rv.data.URL_LocalRelativePath_Root" json:"root,omitempty"`
	Path          string                     `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL_LocalRelativePath) Reset() {
	*x = URL_LocalRelativePath{}
	mi := &file_basicTypes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL_LocalRelativePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL_LocalRelativePath) ProtoMessage() {}

func (x *URL_LocalRelativePath) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL_LocalRelativePath.ProtoReflect.Descriptor instead.
func (*URL_LocalRelativePath) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{0, 0}
}

func (x *URL_LocalRelativePath) GetRoot() URL_LocalRelativePath_Root {
	if x != nil {
		return x.Root
	}
	return URL_LocalRelativePath_ROOT_UNKNOWN
}

func (x *URL_LocalRelativePath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type URL_ExternalRelativePath struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Macos         *URL_ExternalRelativePath_MacOSExternalVolume `protobuf:"bytes,1,opt,name=macos,proto3" json:"macos,omitempty"`
	Win32         *URL_ExternalRelativePath_Win32ExternalVolume `protobuf:"bytes,2,opt,name=win32,proto3" json:"win32,omitempty"`
	Path          string                                        `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL_ExternalRelativePath) Reset() {
	*x = URL_ExternalRelativePath{}
	mi := &file_basicTypes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL_ExternalRelativePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL_ExternalRelativePath) ProtoMessage() {}

func (x *URL_ExternalRelativePath) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL_ExternalRelativePath.ProtoReflect.Descriptor instead.
func (*URL_ExternalRelativePath) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{0, 1}
}

func (x *URL_ExternalRelativePath) GetMacos() *URL_ExternalRelativePath_MacOSExternalVolume {
	if x != nil {
		return x.Macos
	}
	return nil
}

func (x *URL_ExternalRelativePath) GetWin32() *URL_ExternalRelativePath_Win32ExternalVolume {
	if x != nil {
		return x.Win32
	}
	return nil
}

func (x *URL_ExternalRelativePath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type URL_ExternalRelativePath_MacOSExternalVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeName    string                 `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL_ExternalRelativePath_MacOSExternalVolume) Reset() {
	*x = URL_ExternalRelativePath_MacOSExternalVolume{}
	mi := &file_basicTypes_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL_ExternalRelativePath_MacOSExternalVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL_ExternalRelativePath_MacOSExternalVolume) ProtoMessage() {}

func (x *URL_ExternalRelativePath_MacOSExternalVolume) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL_ExternalRelativePath_MacOSExternalVolume.ProtoReflect.Descriptor instead.
func (*URL_ExternalRelativePath_MacOSExternalVolume) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *URL_ExternalRelativePath_MacOSExternalVolume) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

type URL_ExternalRelativePath_Win32ExternalVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriveLetter   string                 `protobuf:"bytes,1,opt,name=drive_letter,json=driveLetter,proto3" json:"drive_letter,omitempty"`
	VolumeName    string                 `protobuf:"bytes,2,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	NetworkShare  bool                   `protobuf:"varint,3,opt,name=network_share,json=networkShare,proto3" json:"network_share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL_ExternalRelativePath_Win32ExternalVolume) Reset() {
	*x = URL_ExternalRelativePath_Win32ExternalVolume{}
	mi := &file_basicTypes_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL_ExternalRelativePath_Win32ExternalVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL_ExternalRelativePath_Win32ExternalVolume) ProtoMessage() {}

func (x *URL_ExternalRelativePath_Win32ExternalVolume) ProtoReflect() protoreflect.Message {
	mi := &file_basicTypes_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL_ExternalRelativePath_Win32ExternalVolume.ProtoReflect.Descriptor instead.
func (*URL_ExternalRelativePath_Win32ExternalVolume) Descriptor() ([]byte, []int) {
	return file_basicTypes_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *URL_ExternalRelativePath_Win32ExternalVolume) GetDriveLetter() string {
	if x != nil {
		return x.DriveLetter
	}
	return ""
}

func (x *URL_ExternalRelativePath_Win32ExternalVolume) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *URL_ExternalRelativePath_Win32ExternalVolume) GetNetworkShare() bool {
	if x != nil {
		return x.NetworkShare
	}
	return false
}

var File_basicTypes_proto protoreflect.FileDescriptor

const file_basicTypes_proto_rawDesc = "" +
	"\n" +
	"\x10basicTypes.proto\x12\arv.data\"\x87\t\n" +
	"\x03URL\x121\n" +
	"\bplatform\x18\x03 \x01(\x0e2\x15.rv.data.URL.PlatformR\bplatform\x12)\n" +
	"\x0fabsolute_string\x18\x01 \x01(\tH\x00R\x0eabsoluteString\x12%\n" +
	"\rrelative_path\x18\x02 \x01(\tH\x00R\frelativePath\x126\n" +
	"\x05local\x18\x04 \x01(\v2\x1e.rv.data.URL.LocalRelativePathH\x01R\x05local\x12?\n" +
	"\bexternal\x18\x05 \x01(\v2!.rv.data.URL.ExternalRelativePathH\x01R\bexternal\x1a\x87\x03\n" +
	"\x11LocalRelativePath\x127\n" +
	"\x04root\x18\x01 \x01(\x0e2#.rv.data.URL.LocalRelativePath.RootR\x04root\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xa4\x02\n" +
	"\x04Root\x12\x10\n" +
	"\fROOT_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10ROOT_BOOT_VOLUME\x10\x01\x12\x12\n" +
	"\x0eROOT_USER_HOME\x10\x02\x12\x17\n" +
	"\x13ROOT_USER_DOCUMENTS\x10\x03\x12\x17\n" +
	"\x13ROOT_USER_DOWNLOADS\x10\x04\x12\x13\n" +
	"\x0fROOT_USER_MUSIC\x10\x05\x12\x16\n" +
	"\x12ROOT_USER_PICTURES\x10\x06\x12\x14\n" +
	"\x10ROOT_USER_VIDEOS\x10\a\x12\x15\n" +
	"\x11ROOT_USER_DESKTOP\x10\v\x12\x19\n" +
	"\x15ROOT_USER_APP_SUPPORT\x10\b\x12\x0f\n" +
	"\vROOT_SHARED\x10\t\x12\r\n" +
	"\tROOT_SHOW\x10\n" +
	"\x12\x19\n" +
	"\x15ROOT_CURRENT_RESOURCE\x10\f\x1a\xfc\x02\n" +
	"\x14ExternalRelativePath\x12K\n" +
	"\x05macos\x18\x01 \x01(\v25.rv.data.URL.ExternalRelativePath.MacOSExternalVolumeR\x05macos\x12K\n" +
	"\x05win32\x18\x02 \x01(\v25.rv.data.URL.ExternalRelativePath.Win32ExternalVolumeR\x05win32\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x1a6\n" +
	"\x13MacOSExternalVolume\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x1a~\n" +
	"\x13Win32ExternalVolume\x12!\n" +
	"\fdrive_letter\x18\x01 \x01(\tR\vdriveLetter\x12\x1f\n" +
	"\vvolume_name\x18\x02 \x01(\tR\n" +
	"volumeName\x12#\n" +
	"\rnetwork_share\x18\x03 \x01(\bR\fnetworkShare\"Z\n" +
	"\bPlatform\x12\x14\n" +
	"\x10PLATFORM_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0ePLATFORM_MACOS\x10\x01\x12\x12\n" +
	"\x0ePLATFORM_WIN32\x10\x02\x12\x10\n" +
	"\fPLATFORM_WEB\x10\x03B\t\n" +
	"\aStorageB\x12\n" +
	"\x10RelativeFilePath\"(\n" +
	"\x04URLs\x12 \n" +
	"\x04urls\x18\x01 \x03(\v2\f.rv.data.URLR\x04urls\"\x1e\n" +
	"\x04UUID\x12\x16\n" +
	"\x06string\x18\x01 \x01(\tR\x06string\"2\n" +
	"\bIntRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x05R\x03end\"Y\n" +
	"\x05Color\x12\x10\n" +
	"\x03red\x18\x01 \x01(\x02R\x03red\x12\x14\n" +
	"\x05green\x18\x02 \x01(\x02R\x05green\x12\x12\n" +
	"\x04blue\x18\x03 \x01(\x02R\x04blue\x12\x14\n" +
	"\x05alpha\x18\x04 \x01(\x02R\x05alpha\"\x8e\x01\n" +
	"\aVersion\x12#\n" +
	"\rmajor_version\x18\x01 \x01(\rR\fmajorVersion\x12#\n" +
	"\rminor_version\x18\x02 \x01(\rR\fminorVersion\x12#\n" +
	"\rpatch_version\x18\x03 \x01(\rR\fpatchVersion\x12\x14\n" +
	"\x05build\x18\x04 \x01(\tR\x05build\"\x80\x04\n" +
	"\x0fApplicationInfo\x12=\n" +
	"\bplatform\x18\x01 \x01(\x0e2!.rv.data.ApplicationInfo.PlatformR\bplatform\x12;\n" +
	"\x10platform_version\x18\x02 \x01(\v2\x10.rv.data.VersionR\x0fplatformVersion\x12F\n" +
	"\vapplication\x18\x03 \x01(\x0e2$.rv.data.ApplicationInfo.ApplicationR\vapplication\x12A\n" +
	"\x13application_version\x18\x04 \x01(\v2\x10.rv.data.VersionR\x12applicationVersion\"L\n" +
	"\bPlatform\x12\x16\n" +
	"\x12PLATFORM_UNDEFINED\x10\x00\x12\x12\n" +
	"\x0ePLATFORM_MACOS\x10\x01\x12\x14\n" +
	"\x10PLATFORM_WINDOWS\x10\x02\"\x97\x01\n" +
	"\vApplication\x12\x19\n" +
	"\x15APPLICATION_UNDEFINED\x10\x00\x12\x1c\n" +
	"\x18APPLICATION_PROPRESENTER\x10\x01\x12\x13\n" +
	"\x0fAPPLICATION_PVP\x10\x02\x12\x1e\n" +
	"\x1aAPPLICATION_PROVIDEOSERVER\x10\x03\x12\x1a\n" +
	"\x16APPLICATION_SCOREBOARD\x10\x04\"t\n" +
	"\x15CollectionElementType\x124\n" +
	"\x0eparameter_uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\rparameterUuid\x12%\n" +
	"\x0eparameter_name\x18\x02 \x01(\tR\rparameterName\"\x8c\x05\n" +
	"\rMusicKeyScale\x12<\n" +
	"\tmusic_key\x18\x01 \x01(\x0e2\x1f.rv.data.MusicKeyScale.MusicKeyR\bmusicKey\x12B\n" +
	"\vmusic_scale\x18\x02 \x01(\x0e2!.rv.data.MusicKeyScale.MusicScaleR\n" +
	"musicScale\"\xbc\x03\n" +
	"\bMusicKey\x12\x14\n" +
	"\x10MUSIC_KEY_A_FLAT\x10\x00\x12\x0f\n" +
	"\vMUSIC_KEY_A\x10\x01\x12\x15\n" +
	"\x11MUSIC_KEY_A_SHARP\x10\x02\x12\x14\n" +
	"\x10MUSIC_KEY_B_FLAT\x10\x03\x12\x0f\n" +
	"\vMUSIC_KEY_B\x10\x04\x12\x15\n" +
	"\x11MUSIC_KEY_B_SHARP\x10\x05\x12\x14\n" +
	"\x10MUSIC_KEY_C_FLAT\x10\x06\x12\x0f\n" +
	"\vMUSIC_KEY_C\x10\a\x12\x15\n" +
	"\x11MUSIC_KEY_C_SHARP\x10\b\x12\x14\n" +
	"\x10MUSIC_KEY_D_FLAT\x10\t\x12\x0f\n" +
	"\vMUSIC_KEY_D\x10\n" +
	"\x12\x15\n" +
	"\x11MUSIC_KEY_D_SHARP\x10\v\x12\x14\n" +
	"\x10MUSIC_KEY_E_FLAT\x10\f\x12\x0f\n" +
	"\vMUSIC_KEY_E\x10\r\x12\x15\n" +
	"\x11MUSIC_KEY_E_SHARP\x10\x0e\x12\x14\n" +
	"\x10MUSIC_KEY_F_FLAT\x10\x0f\x12\x0f\n" +
	"\vMUSIC_KEY_F\x10\x10\x12\x15\n" +
	"\x11MUSIC_KEY_F_SHARP\x10\x11\x12\x14\n" +
	"\x10MUSIC_KEY_G_FLAT\x10\x12\x12\x0f\n" +
	"\vMUSIC_KEY_G\x10\x13\x12\x15\n" +
	"\x11MUSIC_KEY_G_SHARP\x10\x14\":\n" +
	"\n" +
	"MusicScale\x12\x15\n" +
	"\x11MUSIC_SCALE_MAJOR\x10\x00\x12\x15\n" +
	"\x11MUSIC_SCALE_MINOR\x10\x01B\x96\x01\n" +
	"\vcom.rv.dataB\x0fBasicTypesProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_basicTypes_proto_rawDescOnce sync.Once
	file_basicTypes_proto_rawDescData []byte
)

func file_basicTypes_proto_rawDescGZIP() []byte {
	file_basicTypes_proto_rawDescOnce.Do(func() {
		file_basicTypes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basicTypes_proto_rawDesc), len(file_basicTypes_proto_rawDesc)))
	})
	return file_basicTypes_proto_rawDescData
}

var file_basicTypes_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_basicTypes_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_basicTypes_proto_goTypes = []any{
	(URL_Platform)(0),                // 0: rv.data.URL.Platform
	(URL_LocalRelativePath_Root)(0),  // 1: rv.data.URL.LocalRelativePath.Root
	(ApplicationInfo_Platform)(0),    // 2: rv.data.ApplicationInfo.Platform
	(ApplicationInfo_Application)(0), // 3: rv.data.ApplicationInfo.Application
	(MusicKeyScale_MusicKey)(0),      // 4: rv.data.MusicKeyScale.MusicKey
	(MusicKeyScale_MusicScale)(0),    // 5: rv.data.MusicKeyScale.MusicScale
	(*URL)(nil),                      // 6: rv.data.URL
	(*URLs)(nil),                     // 7: rv.data.URLs
	(*UUID)(nil),                     // 8: rv.data.UUID
	(*IntRange)(nil),                 // 9: rv.data.IntRange
	(*Color)(nil),                    // 10: rv.data.Color
	(*Version)(nil),                  // 11: rv.data.Version
	(*ApplicationInfo)(nil),          // 12: rv.data.ApplicationInfo
	(*CollectionElementType)(nil),    // 13: rv.data.CollectionElementType
	(*MusicKeyScale)(nil),            // 14: rv.data.MusicKeyScale
	(*URL_LocalRelativePath)(nil),    // 15: rv.data.URL.LocalRelativePath
	(*URL_ExternalRelativePath)(nil), // 16: rv.data.URL.ExternalRelativePath
	(*URL_ExternalRelativePath_MacOSExternalVolume)(nil), // 17: rv.data.URL.ExternalRelativePath.MacOSExternalVolume
	(*URL_ExternalRelativePath_Win32ExternalVolume)(nil), // 18: rv.data.URL.ExternalRelativePath.Win32ExternalVolume
}
var file_basicTypes_proto_depIdxs = []int32{
	0,  // 0: rv.data.URL.platform:type_name -> rv.data.URL.Platform
	15, // 1: rv.data.URL.local:type_name -> rv.data.URL.LocalRelativePath
	16, // 2: rv.data.URL.external:type_name -> rv.data.URL.ExternalRelativePath
	6,  // 3: rv.data.URLs.urls:type_name -> rv.data.URL
	2,  // 4: rv.data.ApplicationInfo.platform:type_name -> rv.data.ApplicationInfo.Platform
	11, // 5: rv.data.ApplicationInfo.platform_version:type_name -> rv.data.Version
	3,  // 6: rv.data.ApplicationInfo.application:type_name -> rv.data.ApplicationInfo.Application
	11, // 7: rv.data.ApplicationInfo.application_version:type_name -> rv.data.Version
	8,  // 8: rv.data.CollectionElementType.parameter_uuid:type_name -> rv.data.UUID
	4,  // 9: rv.data.MusicKeyScale.music_key:type_name -> rv.data.MusicKeyScale.MusicKey
	5,  // 10: rv.data.MusicKeyScale.music_scale:type_name -> rv.data.MusicKeyScale.MusicScale
	1,  // 11: rv.data.URL.LocalRelativePath.root:type_name -> rv.data.URL.LocalRelativePath.Root
	17, // 12: rv.data.URL.ExternalRelativePath.macos:type_name -> rv.data.URL.ExternalRelativePath.MacOSExternalVolume
	18, // 13: rv.data.URL.ExternalRelativePath.win32:type_name -> rv.data.URL.ExternalRelativePath.Win32ExternalVolume
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_basicTypes_proto_init() }
func file_basicTypes_proto_init() {
	if File_basicTypes_proto != nil {
		return
	}
	file_basicTypes_proto_msgTypes[0].OneofWrappers = []any{
		(*URL_AbsoluteString)(nil),
		(*URL_RelativePath)(nil),
		(*URL_Local)(nil),
		(*URL_External)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basicTypes_proto_rawDesc), len(file_basicTypes_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_basicTypes_proto_goTypes,
		DependencyIndexes: file_basicTypes_proto_depIdxs,
		EnumInfos:         file_basicTypes_proto_enumTypes,
		MessageInfos:      file_basicTypes_proto_msgTypes,
	}.Build()
	File_basicTypes_proto = out.File
	file_basicTypes_proto_goTypes = nil
	file_basicTypes_proto_depIdxs = nil
}
