// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: calendar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Calendar_Event_DayOfWeek int32

const (
	Calendar_Event_DAY_OF_WEEK_UNKNOWN   Calendar_Event_DayOfWeek = 0
	Calendar_Event_DAY_OF_WEEK_SUNDAY    Calendar_Event_DayOfWeek = 1
	Calendar_Event_DAY_OF_WEEK_MONDAY    Calendar_Event_DayOfWeek = 2
	Calendar_Event_DAY_OF_WEEK_TUESDAY   Calendar_Event_DayOfWeek = 3
	Calendar_Event_DAY_OF_WEEK_WEDNESDAY Calendar_Event_DayOfWeek = 4
	Calendar_Event_DAY_OF_WEEK_THURSDAY  Calendar_Event_DayOfWeek = 5
	Calendar_Event_DAY_OF_WEEK_FRIDAY    Calendar_Event_DayOfWeek = 6
	Calendar_Event_DAY_OF_WEEK_SATURDAY  Calendar_Event_DayOfWeek = 7
)

// Enum value maps for Calendar_Event_DayOfWeek.
var (
	Calendar_Event_DayOfWeek_name = map[int32]string{
		0: "DAY_OF_WEEK_UNKNOWN",
		1: "DAY_OF_WEEK_SUNDAY",
		2: "DAY_OF_WEEK_MONDAY",
		3: "DAY_OF_WEEK_TUESDAY",
		4: "DAY_OF_WEEK_WEDNESDAY",
		5: "DAY_OF_WEEK_THURSDAY",
		6: "DAY_OF_WEEK_FRIDAY",
		7: "DAY_OF_WEEK_SATURDAY",
	}
	Calendar_Event_DayOfWeek_value = map[string]int32{
		"DAY_OF_WEEK_UNKNOWN":   0,
		"DAY_OF_WEEK_SUNDAY":    1,
		"DAY_OF_WEEK_MONDAY":    2,
		"DAY_OF_WEEK_TUESDAY":   3,
		"DAY_OF_WEEK_WEDNESDAY": 4,
		"DAY_OF_WEEK_THURSDAY":  5,
		"DAY_OF_WEEK_FRIDAY":    6,
		"DAY_OF_WEEK_SATURDAY":  7,
	}
)

func (x Calendar_Event_DayOfWeek) Enum() *Calendar_Event_DayOfWeek {
	p := new(Calendar_Event_DayOfWeek)
	*p = x
	return p
}

func (x Calendar_Event_DayOfWeek) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Calendar_Event_DayOfWeek) Descriptor() protoreflect.EnumDescriptor {
	return file_calendar_proto_enumTypes[0].Descriptor()
}

func (Calendar_Event_DayOfWeek) Type() protoreflect.EnumType {
	return &file_calendar_proto_enumTypes[0]
}

func (x Calendar_Event_DayOfWeek) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Calendar_Event_DayOfWeek.Descriptor instead.
func (Calendar_Event_DayOfWeek) EnumDescriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Calendar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Calendar_Event      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Calendar) Reset() {
	*x = Calendar{}
	mi := &file_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calendar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calendar) ProtoMessage() {}

func (x *Calendar) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calendar.ProtoReflect.Descriptor instead.
func (*Calendar) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{0}
}

func (x *Calendar) GetEvents() []*Calendar_Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Calendar) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type Calendar_Event struct {
	state                   protoimpl.MessageState     `protogen:"open.v1"`
	Uuid                    *UUID                      `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                    string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description             string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Date                    *Timestamp                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	RecurrenceDays          []Calendar_Event_DayOfWeek `protobuf:"varint,5,rep,packed,name=recurrence_days,json=recurrenceDays,proto3,enum=rv.data.Calendar_Event_DayOfWeek" json:"recurrence_days,omitempty"`
	RecurrenceLimitDate     *Timestamp                 `protobuf:"bytes,6,opt,name=recurrence_limit_date,json=recurrenceLimitDate,proto3" json:"recurrence_limit_date,omitempty"`
	RecurrenceExcludedDates []*Timestamp               `protobuf:"bytes,7,rep,name=recurrence_excluded_dates,json=recurrenceExcludedDates,proto3" json:"recurrence_excluded_dates,omitempty"`
	Action                  *Calendar_Event_Action     `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Calendar_Event) Reset() {
	*x = Calendar_Event{}
	mi := &file_calendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calendar_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calendar_Event) ProtoMessage() {}

func (x *Calendar_Event) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calendar_Event.ProtoReflect.Descriptor instead.
func (*Calendar_Event) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Calendar_Event) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Calendar_Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Calendar_Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Calendar_Event) GetDate() *Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Calendar_Event) GetRecurrenceDays() []Calendar_Event_DayOfWeek {
	if x != nil {
		return x.RecurrenceDays
	}
	return nil
}

func (x *Calendar_Event) GetRecurrenceLimitDate() *Timestamp {
	if x != nil {
		return x.RecurrenceLimitDate
	}
	return nil
}

func (x *Calendar_Event) GetRecurrenceExcludedDates() []*Timestamp {
	if x != nil {
		return x.RecurrenceExcludedDates
	}
	return nil
}

func (x *Calendar_Event) GetAction() *Calendar_Event_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type Calendar_Event_Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Uuid  *UUID                  `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Types that are valid to be assigned to ActionType:
	//
	//	*Calendar_Event_Action_Playlist_
	//	*Calendar_Event_Action_Macro_
	ActionType    isCalendar_Event_Action_ActionType `protobuf_oneof:"ActionType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Calendar_Event_Action) Reset() {
	*x = Calendar_Event_Action{}
	mi := &file_calendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calendar_Event_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calendar_Event_Action) ProtoMessage() {}

func (x *Calendar_Event_Action) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calendar_Event_Action.ProtoReflect.Descriptor instead.
func (*Calendar_Event_Action) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Calendar_Event_Action) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Calendar_Event_Action) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Calendar_Event_Action) GetActionType() isCalendar_Event_Action_ActionType {
	if x != nil {
		return x.ActionType
	}
	return nil
}

func (x *Calendar_Event_Action) GetPlaylist() *Calendar_Event_Action_Playlist {
	if x != nil {
		if x, ok := x.ActionType.(*Calendar_Event_Action_Playlist_); ok {
			return x.Playlist
		}
	}
	return nil
}

func (x *Calendar_Event_Action) GetMacro() *Calendar_Event_Action_Macro {
	if x != nil {
		if x, ok := x.ActionType.(*Calendar_Event_Action_Macro_); ok {
			return x.Macro
		}
	}
	return nil
}

type isCalendar_Event_Action_ActionType interface {
	isCalendar_Event_Action_ActionType()
}

type Calendar_Event_Action_Playlist_ struct {
	Playlist *Calendar_Event_Action_Playlist `protobuf:"bytes,3,opt,name=playlist,proto3,oneof"`
}

type Calendar_Event_Action_Macro_ struct {
	Macro *Calendar_Event_Action_Macro `protobuf:"bytes,4,opt,name=macro,proto3,oneof"`
}

func (*Calendar_Event_Action_Playlist_) isCalendar_Event_Action_ActionType() {}

func (*Calendar_Event_Action_Macro_) isCalendar_Event_Action_ActionType() {}

type Calendar_Event_Action_Playlist struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlaylistUuid     *UUID                  `protobuf:"bytes,1,opt,name=playlist_uuid,json=playlistUuid,proto3" json:"playlist_uuid,omitempty"`
	PlaylistItemUuid *UUID                  `protobuf:"bytes,2,opt,name=playlist_item_uuid,json=playlistItemUuid,proto3" json:"playlist_item_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Calendar_Event_Action_Playlist) Reset() {
	*x = Calendar_Event_Action_Playlist{}
	mi := &file_calendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calendar_Event_Action_Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calendar_Event_Action_Playlist) ProtoMessage() {}

func (x *Calendar_Event_Action_Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calendar_Event_Action_Playlist.ProtoReflect.Descriptor instead.
func (*Calendar_Event_Action_Playlist) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *Calendar_Event_Action_Playlist) GetPlaylistUuid() *UUID {
	if x != nil {
		return x.PlaylistUuid
	}
	return nil
}

func (x *Calendar_Event_Action_Playlist) GetPlaylistItemUuid() *UUID {
	if x != nil {
		return x.PlaylistItemUuid
	}
	return nil
}

type Calendar_Event_Action_Macro struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identification *CollectionElementType `protobuf:"bytes,1,opt,name=identification,proto3" json:"identification,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Calendar_Event_Action_Macro) Reset() {
	*x = Calendar_Event_Action_Macro{}
	mi := &file_calendar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calendar_Event_Action_Macro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calendar_Event_Action_Macro) ProtoMessage() {}

func (x *Calendar_Event_Action_Macro) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calendar_Event_Action_Macro.ProtoReflect.Descriptor instead.
func (*Calendar_Event_Action_Macro) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

func (x *Calendar_Event_Action_Macro) GetIdentification() *CollectionElementType {
	if x != nil {
		return x.Identification
	}
	return nil
}

var File_calendar_proto protoreflect.FileDescriptor

const file_calendar_proto_rawDesc = "" +
	"\n" +
	"\x0ecalendar.proto\x12\arv.data\x1a\x10basicTypes.proto\x1a\x11rvtimestamp.proto\"\xf4\b\n" +
	"\bCalendar\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.rv.data.Calendar.EventR\x06events\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x1a\x9e\b\n" +
	"\x05Event\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12&\n" +
	"\x04date\x18\x04 \x01(\v2\x12.rv.data.TimestampR\x04date\x12J\n" +
	"\x0frecurrence_days\x18\x05 \x03(\x0e2!.rv.data.Calendar.Event.DayOfWeekR\x0erecurrenceDays\x12F\n" +
	"\x15recurrence_limit_date\x18\x06 \x01(\v2\x12.rv.data.TimestampR\x13recurrenceLimitDate\x12N\n" +
	"\x19recurrence_excluded_dates\x18\a \x03(\v2\x12.rv.data.TimestampR\x17recurrenceExcludedDates\x126\n" +
	"\x06action\x18\b \x01(\v2\x1e.rv.data.Calendar.Event.ActionR\x06action\x1a\xa0\x03\n" +
	"\x06Action\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12!\n" +
	"\x04uuid\x18\x02 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12E\n" +
	"\bplaylist\x18\x03 \x01(\v2'.rv.data.Calendar.Event.Action.PlaylistH\x00R\bplaylist\x12<\n" +
	"\x05macro\x18\x04 \x01(\v2$.rv.data.Calendar.Event.Action.MacroH\x00R\x05macro\x1a{\n" +
	"\bPlaylist\x122\n" +
	"\rplaylist_uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\fplaylistUuid\x12;\n" +
	"\x12playlist_item_uuid\x18\x02 \x01(\v2\r.rv.data.UUIDR\x10playlistItemUuid\x1aO\n" +
	"\x05Macro\x12F\n" +
	"\x0eidentification\x18\x01 \x01(\v2\x1e.rv.data.CollectionElementTypeR\x0eidentificationB\f\n" +
	"\n" +
	"ActionType\"\xd4\x01\n" +
	"\tDayOfWeek\x12\x17\n" +
	"\x13DAY_OF_WEEK_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12DAY_OF_WEEK_SUNDAY\x10\x01\x12\x16\n" +
	"\x12DAY_OF_WEEK_MONDAY\x10\x02\x12\x17\n" +
	"\x13DAY_OF_WEEK_TUESDAY\x10\x03\x12\x19\n" +
	"\x15DAY_OF_WEEK_WEDNESDAY\x10\x04\x12\x18\n" +
	"\x14DAY_OF_WEEK_THURSDAY\x10\x05\x12\x16\n" +
	"\x12DAY_OF_WEEK_FRIDAY\x10\x06\x12\x18\n" +
	"\x14DAY_OF_WEEK_SATURDAY\x10\aB\x93\x01\n" +
	"\vcom.rv.dataB\rCalendarProtoP\x01Z8github.com/thatguycleeb/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_calendar_proto_rawDescOnce sync.Once
	file_calendar_proto_rawDescData []byte
)

func file_calendar_proto_rawDescGZIP() []byte {
	file_calendar_proto_rawDescOnce.Do(func() {
		file_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calendar_proto_rawDesc), len(file_calendar_proto_rawDesc)))
	})
	return file_calendar_proto_rawDescData
}

var file_calendar_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_calendar_proto_goTypes = []any{
	(Calendar_Event_DayOfWeek)(0),          // 0: rv.data.Calendar.Event.DayOfWeek
	(*Calendar)(nil),                       // 1: rv.data.Calendar
	(*Calendar_Event)(nil),                 // 2: rv.data.Calendar.Event
	(*Calendar_Event_Action)(nil),          // 3: rv.data.Calendar.Event.Action
	(*Calendar_Event_Action_Playlist)(nil), // 4: rv.data.Calendar.Event.Action.Playlist
	(*Calendar_Event_Action_Macro)(nil),    // 5: rv.data.Calendar.Event.Action.Macro
	(*UUID)(nil),                           // 6: rv.data.UUID
	(*Timestamp)(nil),                      // 7: rv.data.Timestamp
	(*CollectionElementType)(nil),          // 8: rv.data.CollectionElementType
}
var file_calendar_proto_depIdxs = []int32{
	2,  // 0: rv.data.Calendar.events:type_name -> rv.data.Calendar.Event
	6,  // 1: rv.data.Calendar.Event.uuid:type_name -> rv.data.UUID
	7,  // 2: rv.data.Calendar.Event.date:type_name -> rv.data.Timestamp
	0,  // 3: rv.data.Calendar.Event.recurrence_days:type_name -> rv.data.Calendar.Event.DayOfWeek
	7,  // 4: rv.data.Calendar.Event.recurrence_limit_date:type_name -> rv.data.Timestamp
	7,  // 5: rv.data.Calendar.Event.recurrence_excluded_dates:type_name -> rv.data.Timestamp
	3,  // 6: rv.data.Calendar.Event.action:type_name -> rv.data.Calendar.Event.Action
	6,  // 7: rv.data.Calendar.Event.Action.uuid:type_name -> rv.data.UUID
	4,  // 8: rv.data.Calendar.Event.Action.playlist:type_name -> rv.data.Calendar.Event.Action.Playlist
	5,  // 9: rv.data.Calendar.Event.Action.macro:type_name -> rv.data.Calendar.Event.Action.Macro
	6,  // 10: rv.data.Calendar.Event.Action.Playlist.playlist_uuid:type_name -> rv.data.UUID
	6,  // 11: rv.data.Calendar.Event.Action.Playlist.playlist_item_uuid:type_name -> rv.data.UUID
	8,  // 12: rv.data.Calendar.Event.Action.Macro.identification:type_name -> rv.data.CollectionElementType
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_calendar_proto_init() }
func file_calendar_proto_init() {
	if File_calendar_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_rvtimestamp_proto_init()
	file_calendar_proto_msgTypes[2].OneofWrappers = []any{
		(*Calendar_Event_Action_Playlist_)(nil),
		(*Calendar_Event_Action_Macro_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calendar_proto_rawDesc), len(file_calendar_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_calendar_proto_goTypes,
		DependencyIndexes: file_calendar_proto_depIdxs,
		EnumInfos:         file_calendar_proto_enumTypes,
		MessageInfos:      file_calendar_proto_msgTypes,
	}.Build()
	File_calendar_proto = out.File
	file_calendar_proto_goTypes = nil
	file_calendar_proto_depIdxs = nil
}
