// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ccli.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CCLIDocument_DisplayType int32

const (
	CCLIDocument_DISPLAY_TYPE_FIRST_SLIDE          CCLIDocument_DisplayType = 0
	CCLIDocument_DISPLAY_TYPE_LAST_SLIDE           CCLIDocument_DisplayType = 1
	CCLIDocument_DISPLAY_TYPE_FIRST_AND_LAST_SLIDE CCLIDocument_DisplayType = 2
	CCLIDocument_DISPLAY_TYPE_ALL_SLIDES           CCLIDocument_DisplayType = 3
)

// Enum value maps for CCLIDocument_DisplayType.
var (
	CCLIDocument_DisplayType_name = map[int32]string{
		0: "DISPLAY_TYPE_FIRST_SLIDE",
		1: "DISPLAY_TYPE_LAST_SLIDE",
		2: "DISPLAY_TYPE_FIRST_AND_LAST_SLIDE",
		3: "DISPLAY_TYPE_ALL_SLIDES",
	}
	CCLIDocument_DisplayType_value = map[string]int32{
		"DISPLAY_TYPE_FIRST_SLIDE":          0,
		"DISPLAY_TYPE_LAST_SLIDE":           1,
		"DISPLAY_TYPE_FIRST_AND_LAST_SLIDE": 2,
		"DISPLAY_TYPE_ALL_SLIDES":           3,
	}
)

func (x CCLIDocument_DisplayType) Enum() *CCLIDocument_DisplayType {
	p := new(CCLIDocument_DisplayType)
	*p = x
	return p
}

func (x CCLIDocument_DisplayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CCLIDocument_DisplayType) Descriptor() protoreflect.EnumDescriptor {
	return file_ccli_proto_enumTypes[0].Descriptor()
}

func (CCLIDocument_DisplayType) Type() protoreflect.EnumType {
	return &file_ccli_proto_enumTypes[0]
}

func (x CCLIDocument_DisplayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CCLIDocument_DisplayType.Descriptor instead.
func (CCLIDocument_DisplayType) EnumDescriptor() ([]byte, []int) {
	return file_ccli_proto_rawDescGZIP(), []int{0, 0}
}

type CCLIDocument struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	ApplicationInfo   *ApplicationInfo         `protobuf:"bytes,1,opt,name=application_info,json=applicationInfo,proto3" json:"application_info,omitempty"`
	EnableCcliDisplay bool                     `protobuf:"varint,2,opt,name=enable_ccli_display,json=enableCcliDisplay,proto3" json:"enable_ccli_display,omitempty"`
	CcliLicense       string                   `protobuf:"bytes,3,opt,name=ccli_license,json=ccliLicense,proto3" json:"ccli_license,omitempty"`
	DisplayType       CCLIDocument_DisplayType `protobuf:"varint,4,opt,name=display_type,json=displayType,proto3,enum=rv.data.CCLIDocument_DisplayType" json:"display_type,omitempty"`
	Template          *Template_Slide          `protobuf:"bytes,5,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CCLIDocument) Reset() {
	*x = CCLIDocument{}
	mi := &file_ccli_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCLIDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCLIDocument) ProtoMessage() {}

func (x *CCLIDocument) ProtoReflect() protoreflect.Message {
	mi := &file_ccli_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCLIDocument.ProtoReflect.Descriptor instead.
func (*CCLIDocument) Descriptor() ([]byte, []int) {
	return file_ccli_proto_rawDescGZIP(), []int{0}
}

func (x *CCLIDocument) GetApplicationInfo() *ApplicationInfo {
	if x != nil {
		return x.ApplicationInfo
	}
	return nil
}

func (x *CCLIDocument) GetEnableCcliDisplay() bool {
	if x != nil {
		return x.EnableCcliDisplay
	}
	return false
}

func (x *CCLIDocument) GetCcliLicense() string {
	if x != nil {
		return x.CcliLicense
	}
	return ""
}

func (x *CCLIDocument) GetDisplayType() CCLIDocument_DisplayType {
	if x != nil {
		return x.DisplayType
	}
	return CCLIDocument_DISPLAY_TYPE_FIRST_SLIDE
}

func (x *CCLIDocument) GetTemplate() *Template_Slide {
	if x != nil {
		return x.Template
	}
	return nil
}

var File_ccli_proto protoreflect.FileDescriptor

const file_ccli_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ccli.proto\x12\arv.data\x1a\x10basicTypes.proto\x1a\x0etemplate.proto\"\xb0\x03\n" +
	"\fCCLIDocument\x12C\n" +
	"\x10application_info\x18\x01 \x01(\v2\x18.rv.data.ApplicationInfoR\x0fapplicationInfo\x12.\n" +
	"\x13enable_ccli_display\x18\x02 \x01(\bR\x11enableCcliDisplay\x12!\n" +
	"\fccli_license\x18\x03 \x01(\tR\vccliLicense\x12D\n" +
	"\fdisplay_type\x18\x04 \x01(\x0e2!.rv.data.CCLIDocument.DisplayTypeR\vdisplayType\x123\n" +
	"\btemplate\x18\x05 \x01(\v2\x17.rv.data.Template.SlideR\btemplate\"\x8c\x01\n" +
	"\vDisplayType\x12\x1c\n" +
	"\x18DISPLAY_TYPE_FIRST_SLIDE\x10\x00\x12\x1b\n" +
	"\x17DISPLAY_TYPE_LAST_SLIDE\x10\x01\x12%\n" +
	"!DISPLAY_TYPE_FIRST_AND_LAST_SLIDE\x10\x02\x12\x1b\n" +
	"\x17DISPLAY_TYPE_ALL_SLIDES\x10\x03B\x90\x01\n" +
	"\vcom.rv.dataB\tCcliProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_ccli_proto_rawDescOnce sync.Once
	file_ccli_proto_rawDescData []byte
)

func file_ccli_proto_rawDescGZIP() []byte {
	file_ccli_proto_rawDescOnce.Do(func() {
		file_ccli_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ccli_proto_rawDesc), len(file_ccli_proto_rawDesc)))
	})
	return file_ccli_proto_rawDescData
}

var file_ccli_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ccli_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ccli_proto_goTypes = []any{
	(CCLIDocument_DisplayType)(0), // 0: rv.data.CCLIDocument.DisplayType
	(*CCLIDocument)(nil),          // 1: rv.data.CCLIDocument
	(*ApplicationInfo)(nil),       // 2: rv.data.ApplicationInfo
	(*Template_Slide)(nil),        // 3: rv.data.Template.Slide
}
var file_ccli_proto_depIdxs = []int32{
	2, // 0: rv.data.CCLIDocument.application_info:type_name -> rv.data.ApplicationInfo
	0, // 1: rv.data.CCLIDocument.display_type:type_name -> rv.data.CCLIDocument.DisplayType
	3, // 2: rv.data.CCLIDocument.template:type_name -> rv.data.Template.Slide
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ccli_proto_init() }
func file_ccli_proto_init() {
	if File_ccli_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_template_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ccli_proto_rawDesc), len(file_ccli_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ccli_proto_goTypes,
		DependencyIndexes: file_ccli_proto_depIdxs,
		EnumInfos:         file_ccli_proto_enumTypes,
		MessageInfos:      file_ccli_proto_msgTypes,
	}.Build()
	File_ccli_proto = out.File
	file_ccli_proto_goTypes = nil
	file_ccli_proto_depIdxs = nil
}
