// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cue.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cue_CompletionTargetType int32

const (
	Cue_COMPLETION_TARGET_TYPE_NONE   Cue_CompletionTargetType = 0
	Cue_COMPLETION_TARGET_TYPE_NEXT   Cue_CompletionTargetType = 1
	Cue_COMPLETION_TARGET_TYPE_RANDOM Cue_CompletionTargetType = 2
	Cue_COMPLETION_TARGET_TYPE_CUE    Cue_CompletionTargetType = 3
	Cue_COMPLETION_TARGET_TYPE_FIRST  Cue_CompletionTargetType = 4
)

// Enum value maps for Cue_CompletionTargetType.
var (
	Cue_CompletionTargetType_name = map[int32]string{
		0: "COMPLETION_TARGET_TYPE_NONE",
		1: "COMPLETION_TARGET_TYPE_NEXT",
		2: "COMPLETION_TARGET_TYPE_RANDOM",
		3: "COMPLETION_TARGET_TYPE_CUE",
		4: "COMPLETION_TARGET_TYPE_FIRST",
	}
	Cue_CompletionTargetType_value = map[string]int32{
		"COMPLETION_TARGET_TYPE_NONE":   0,
		"COMPLETION_TARGET_TYPE_NEXT":   1,
		"COMPLETION_TARGET_TYPE_RANDOM": 2,
		"COMPLETION_TARGET_TYPE_CUE":    3,
		"COMPLETION_TARGET_TYPE_FIRST":  4,
	}
)

func (x Cue_CompletionTargetType) Enum() *Cue_CompletionTargetType {
	p := new(Cue_CompletionTargetType)
	*p = x
	return p
}

func (x Cue_CompletionTargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cue_CompletionTargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_cue_proto_enumTypes[0].Descriptor()
}

func (Cue_CompletionTargetType) Type() protoreflect.EnumType {
	return &file_cue_proto_enumTypes[0]
}

func (x Cue_CompletionTargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cue_CompletionTargetType.Descriptor instead.
func (Cue_CompletionTargetType) EnumDescriptor() ([]byte, []int) {
	return file_cue_proto_rawDescGZIP(), []int{0, 0}
}

type Cue_CompletionActionType int32

const (
	Cue_COMPLETION_ACTION_TYPE_FIRST        Cue_CompletionActionType = 0
	Cue_COMPLETION_ACTION_TYPE_LAST         Cue_CompletionActionType = 1
	Cue_COMPLETION_ACTION_TYPE_AFTER_ACTION Cue_CompletionActionType = 2
	Cue_COMPLETION_ACTION_TYPE_AFTER_TIME   Cue_CompletionActionType = 3
)

// Enum value maps for Cue_CompletionActionType.
var (
	Cue_CompletionActionType_name = map[int32]string{
		0: "COMPLETION_ACTION_TYPE_FIRST",
		1: "COMPLETION_ACTION_TYPE_LAST",
		2: "COMPLETION_ACTION_TYPE_AFTER_ACTION",
		3: "COMPLETION_ACTION_TYPE_AFTER_TIME",
	}
	Cue_CompletionActionType_value = map[string]int32{
		"COMPLETION_ACTION_TYPE_FIRST":        0,
		"COMPLETION_ACTION_TYPE_LAST":         1,
		"COMPLETION_ACTION_TYPE_AFTER_ACTION": 2,
		"COMPLETION_ACTION_TYPE_AFTER_TIME":   3,
	}
)

func (x Cue_CompletionActionType) Enum() *Cue_CompletionActionType {
	p := new(Cue_CompletionActionType)
	*p = x
	return p
}

func (x Cue_CompletionActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cue_CompletionActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_cue_proto_enumTypes[1].Descriptor()
}

func (Cue_CompletionActionType) Type() protoreflect.EnumType {
	return &file_cue_proto_enumTypes[1]
}

func (x Cue_CompletionActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cue_CompletionActionType.Descriptor instead.
func (Cue_CompletionActionType) EnumDescriptor() ([]byte, []int) {
	return file_cue_proto_rawDescGZIP(), []int{0, 1}
}

type Cue struct {
	state                protoimpl.MessageState     `protogen:"open.v1"`
	Uuid                 *UUID                      `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CompletionTargetType Cue_CompletionTargetType   `protobuf:"varint,3,opt,name=completion_target_type,json=completionTargetType,proto3,enum=rv.data.Cue_CompletionTargetType" json:"completion_target_type,omitempty"`
	CompletionTargetUuid *UUID                      `protobuf:"bytes,4,opt,name=completion_target_uuid,json=completionTargetUuid,proto3" json:"completion_target_uuid,omitempty"`
	CompletionActionType Cue_CompletionActionType   `protobuf:"varint,5,opt,name=completion_action_type,json=completionActionType,proto3,enum=rv.data.Cue_CompletionActionType" json:"completion_action_type,omitempty"`
	CompletionActionUuid *UUID                      `protobuf:"bytes,6,opt,name=completion_action_uuid,json=completionActionUuid,proto3" json:"completion_action_uuid,omitempty"`
	TriggerTime          *Cue_TimecodeTime          `protobuf:"bytes,7,opt,name=trigger_time,json=triggerTime,proto3" json:"trigger_time,omitempty"`
	HotKey               *HotKey                    `protobuf:"bytes,8,opt,name=hot_key,json=hotKey,proto3" json:"hot_key,omitempty"`
	Actions              []*Action                  `protobuf:"bytes,10,rep,name=actions,proto3" json:"actions,omitempty"`
	PendingImports       []*Cue_PendingImportsEntry `protobuf:"bytes,11,rep,name=pending_imports,json=pendingImports,proto3" json:"pending_imports,omitempty"`
	IsEnabled            bool                       `protobuf:"varint,12,opt,name=isEnabled,proto3" json:"isEnabled,omitempty"`
	CompletionTime       float64                    `protobuf:"fixed64,13,opt,name=completion_time,json=completionTime,proto3" json:"completion_time,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Cue) Reset() {
	*x = Cue{}
	mi := &file_cue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cue) ProtoMessage() {}

func (x *Cue) ProtoReflect() protoreflect.Message {
	mi := &file_cue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cue.ProtoReflect.Descriptor instead.
func (*Cue) Descriptor() ([]byte, []int) {
	return file_cue_proto_rawDescGZIP(), []int{0}
}

func (x *Cue) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Cue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cue) GetCompletionTargetType() Cue_CompletionTargetType {
	if x != nil {
		return x.CompletionTargetType
	}
	return Cue_COMPLETION_TARGET_TYPE_NONE
}

func (x *Cue) GetCompletionTargetUuid() *UUID {
	if x != nil {
		return x.CompletionTargetUuid
	}
	return nil
}

func (x *Cue) GetCompletionActionType() Cue_CompletionActionType {
	if x != nil {
		return x.CompletionActionType
	}
	return Cue_COMPLETION_ACTION_TYPE_FIRST
}

func (x *Cue) GetCompletionActionUuid() *UUID {
	if x != nil {
		return x.CompletionActionUuid
	}
	return nil
}

func (x *Cue) GetTriggerTime() *Cue_TimecodeTime {
	if x != nil {
		return x.TriggerTime
	}
	return nil
}

func (x *Cue) GetHotKey() *HotKey {
	if x != nil {
		return x.HotKey
	}
	return nil
}

func (x *Cue) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Cue) GetPendingImports() []*Cue_PendingImportsEntry {
	if x != nil {
		return x.PendingImports
	}
	return nil
}

func (x *Cue) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *Cue) GetCompletionTime() float64 {
	if x != nil {
		return x.CompletionTime
	}
	return 0
}

type Cue_TimecodeTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          float64                `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cue_TimecodeTime) Reset() {
	*x = Cue_TimecodeTime{}
	mi := &file_cue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cue_TimecodeTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cue_TimecodeTime) ProtoMessage() {}

func (x *Cue_TimecodeTime) ProtoReflect() protoreflect.Message {
	mi := &file_cue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cue_TimecodeTime.ProtoReflect.Descriptor instead.
func (*Cue_TimecodeTime) Descriptor() ([]byte, []int) {
	return file_cue_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Cue_TimecodeTime) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Cue_PendingImportsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *URLs                  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cue_PendingImportsEntry) Reset() {
	*x = Cue_PendingImportsEntry{}
	mi := &file_cue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cue_PendingImportsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cue_PendingImportsEntry) ProtoMessage() {}

func (x *Cue_PendingImportsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cue_PendingImportsEntry.ProtoReflect.Descriptor instead.
func (*Cue_PendingImportsEntry) Descriptor() ([]byte, []int) {
	return file_cue_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Cue_PendingImportsEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Cue_PendingImportsEntry) GetValue() *URLs {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_cue_proto protoreflect.FileDescriptor

const file_cue_proto_rawDesc = "" +
	"\n" +
	"\tcue.proto\x12\arv.data\x1a\x10basicTypes.proto\x1a\fhotKey.proto\x1a\faction.proto\"\xfb\b\n" +
	"\x03Cue\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12W\n" +
	"\x16completion_target_type\x18\x03 \x01(\x0e2!.rv.data.Cue.CompletionTargetTypeR\x14completionTargetType\x12C\n" +
	"\x16completion_target_uuid\x18\x04 \x01(\v2\r.rv.data.UUIDR\x14completionTargetUuid\x12W\n" +
	"\x16completion_action_type\x18\x05 \x01(\x0e2!.rv.data.Cue.CompletionActionTypeR\x14completionActionType\x12C\n" +
	"\x16completion_action_uuid\x18\x06 \x01(\v2\r.rv.data.UUIDR\x14completionActionUuid\x12<\n" +
	"\ftrigger_time\x18\a \x01(\v2\x19.rv.data.Cue.TimecodeTimeR\vtriggerTime\x12(\n" +
	"\ahot_key\x18\b \x01(\v2\x0f.rv.data.HotKeyR\x06hotKey\x12)\n" +
	"\aactions\x18\n" +
	" \x03(\v2\x0f.rv.data.ActionR\aactions\x12I\n" +
	"\x0fpending_imports\x18\v \x03(\v2 .rv.data.Cue.PendingImportsEntryR\x0ependingImports\x12\x1c\n" +
	"\tisEnabled\x18\f \x01(\bR\tisEnabled\x12'\n" +
	"\x0fcompletion_time\x18\r \x01(\x01R\x0ecompletionTime\x1a\"\n" +
	"\fTimecodeTime\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x01R\x04time\x1aL\n" +
	"\x13PendingImportsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.rv.data.URLsR\x05value\"\xbd\x01\n" +
	"\x14CompletionTargetType\x12\x1f\n" +
	"\x1bCOMPLETION_TARGET_TYPE_NONE\x10\x00\x12\x1f\n" +
	"\x1bCOMPLETION_TARGET_TYPE_NEXT\x10\x01\x12!\n" +
	"\x1dCOMPLETION_TARGET_TYPE_RANDOM\x10\x02\x12\x1e\n" +
	"\x1aCOMPLETION_TARGET_TYPE_CUE\x10\x03\x12 \n" +
	"\x1cCOMPLETION_TARGET_TYPE_FIRST\x10\x04\"\xa9\x01\n" +
	"\x14CompletionActionType\x12 \n" +
	"\x1cCOMPLETION_ACTION_TYPE_FIRST\x10\x00\x12\x1f\n" +
	"\x1bCOMPLETION_ACTION_TYPE_LAST\x10\x01\x12'\n" +
	"#COMPLETION_ACTION_TYPE_AFTER_ACTION\x10\x02\x12%\n" +
	"!COMPLETION_ACTION_TYPE_AFTER_TIME\x10\x03B\x8f\x01\n" +
	"\vcom.rv.dataB\bCueProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_cue_proto_rawDescOnce sync.Once
	file_cue_proto_rawDescData []byte
)

func file_cue_proto_rawDescGZIP() []byte {
	file_cue_proto_rawDescOnce.Do(func() {
		file_cue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cue_proto_rawDesc), len(file_cue_proto_rawDesc)))
	})
	return file_cue_proto_rawDescData
}

var file_cue_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cue_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cue_proto_goTypes = []any{
	(Cue_CompletionTargetType)(0),   // 0: rv.data.Cue.CompletionTargetType
	(Cue_CompletionActionType)(0),   // 1: rv.data.Cue.CompletionActionType
	(*Cue)(nil),                     // 2: rv.data.Cue
	(*Cue_TimecodeTime)(nil),        // 3: rv.data.Cue.TimecodeTime
	(*Cue_PendingImportsEntry)(nil), // 4: rv.data.Cue.PendingImportsEntry
	(*UUID)(nil),                    // 5: rv.data.UUID
	(*HotKey)(nil),                  // 6: rv.data.HotKey
	(*Action)(nil),                  // 7: rv.data.Action
	(*URLs)(nil),                    // 8: rv.data.URLs
}
var file_cue_proto_depIdxs = []int32{
	5,  // 0: rv.data.Cue.uuid:type_name -> rv.data.UUID
	0,  // 1: rv.data.Cue.completion_target_type:type_name -> rv.data.Cue.CompletionTargetType
	5,  // 2: rv.data.Cue.completion_target_uuid:type_name -> rv.data.UUID
	1,  // 3: rv.data.Cue.completion_action_type:type_name -> rv.data.Cue.CompletionActionType
	5,  // 4: rv.data.Cue.completion_action_uuid:type_name -> rv.data.UUID
	3,  // 5: rv.data.Cue.trigger_time:type_name -> rv.data.Cue.TimecodeTime
	6,  // 6: rv.data.Cue.hot_key:type_name -> rv.data.HotKey
	7,  // 7: rv.data.Cue.actions:type_name -> rv.data.Action
	4,  // 8: rv.data.Cue.pending_imports:type_name -> rv.data.Cue.PendingImportsEntry
	8,  // 9: rv.data.Cue.PendingImportsEntry.value:type_name -> rv.data.URLs
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cue_proto_init() }
func file_cue_proto_init() {
	if File_cue_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_hotKey_proto_init()
	file_action_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cue_proto_rawDesc), len(file_cue_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cue_proto_goTypes,
		DependencyIndexes: file_cue_proto_depIdxs,
		EnumInfos:         file_cue_proto_enumTypes,
		MessageInfos:      file_cue_proto_msgTypes,
	}.Build()
	File_cue_proto = out.File
	file_cue_proto_goTypes = nil
	file_cue_proto_depIdxs = nil
}
