// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dmxProfiles.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DMXProfiles_DMXProfile_Profile_ProfileType int32

const (
	DMXProfiles_DMXProfile_Profile_BASIC    DMXProfiles_DMXProfile_Profile_ProfileType = 0
	DMXProfiles_DMXProfile_Profile_ADVANCED DMXProfiles_DMXProfile_Profile_ProfileType = 1
	DMXProfiles_DMXProfile_Profile_CUSTOM   DMXProfiles_DMXProfile_Profile_ProfileType = 2
)

// Enum value maps for DMXProfiles_DMXProfile_Profile_ProfileType.
var (
	DMXProfiles_DMXProfile_Profile_ProfileType_name = map[int32]string{
		0: "BASIC",
		1: "ADVANCED",
		2: "CUSTOM",
	}
	DMXProfiles_DMXProfile_Profile_ProfileType_value = map[string]int32{
		"BASIC":    0,
		"ADVANCED": 1,
		"CUSTOM":   2,
	}
)

func (x DMXProfiles_DMXProfile_Profile_ProfileType) Enum() *DMXProfiles_DMXProfile_Profile_ProfileType {
	p := new(DMXProfiles_DMXProfile_Profile_ProfileType)
	*p = x
	return p
}

func (x DMXProfiles_DMXProfile_Profile_ProfileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DMXProfiles_DMXProfile_Profile_ProfileType) Descriptor() protoreflect.EnumDescriptor {
	return file_dmxProfiles_proto_enumTypes[0].Descriptor()
}

func (DMXProfiles_DMXProfile_Profile_ProfileType) Type() protoreflect.EnumType {
	return &file_dmxProfiles_proto_enumTypes[0]
}

func (x DMXProfiles_DMXProfile_Profile_ProfileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DMXProfiles_DMXProfile_Profile_ProfileType.Descriptor instead.
func (DMXProfiles_DMXProfile_Profile_ProfileType) EnumDescriptor() ([]byte, []int) {
	return file_dmxProfiles_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type DMXProfiles_DMXProfile_ChannelMapping_CommandType int32

const (
	DMXProfiles_DMXProfile_ChannelMapping_OPACITY             DMXProfiles_DMXProfile_ChannelMapping_CommandType = 0
	DMXProfiles_DMXProfile_ChannelMapping_BLEND_MODE          DMXProfiles_DMXProfile_ChannelMapping_CommandType = 1
	DMXProfiles_DMXProfile_ChannelMapping_SELECT_CUE          DMXProfiles_DMXProfile_ChannelMapping_CommandType = 2
	DMXProfiles_DMXProfile_ChannelMapping_CONTROL_TYPE        DMXProfiles_DMXProfile_ChannelMapping_CommandType = 3
	DMXProfiles_DMXProfile_ChannelMapping_CONTROL_VALUE       DMXProfiles_DMXProfile_ChannelMapping_CommandType = 4
	DMXProfiles_DMXProfile_ChannelMapping_TRANSITION_DURATION DMXProfiles_DMXProfile_ChannelMapping_CommandType = 5
	DMXProfiles_DMXProfile_ChannelMapping_SELECT_PLAYLIST     DMXProfiles_DMXProfile_ChannelMapping_CommandType = 6
	DMXProfiles_DMXProfile_ChannelMapping_TARGETED_LAYER      DMXProfiles_DMXProfile_ChannelMapping_CommandType = 7
)

// Enum value maps for DMXProfiles_DMXProfile_ChannelMapping_CommandType.
var (
	DMXProfiles_DMXProfile_ChannelMapping_CommandType_name = map[int32]string{
		0: "OPACITY",
		1: "BLEND_MODE",
		2: "SELECT_CUE",
		3: "CONTROL_TYPE",
		4: "CONTROL_VALUE",
		5: "TRANSITION_DURATION",
		6: "SELECT_PLAYLIST",
		7: "TARGETED_LAYER",
	}
	DMXProfiles_DMXProfile_ChannelMapping_CommandType_value = map[string]int32{
		"OPACITY":             0,
		"BLEND_MODE":          1,
		"SELECT_CUE":          2,
		"CONTROL_TYPE":        3,
		"CONTROL_VALUE":       4,
		"TRANSITION_DURATION": 5,
		"SELECT_PLAYLIST":     6,
		"TARGETED_LAYER":      7,
	}
)

func (x DMXProfiles_DMXProfile_ChannelMapping_CommandType) Enum() *DMXProfiles_DMXProfile_ChannelMapping_CommandType {
	p := new(DMXProfiles_DMXProfile_ChannelMapping_CommandType)
	*p = x
	return p
}

func (x DMXProfiles_DMXProfile_ChannelMapping_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DMXProfiles_DMXProfile_ChannelMapping_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_dmxProfiles_proto_enumTypes[1].Descriptor()
}

func (DMXProfiles_DMXProfile_ChannelMapping_CommandType) Type() protoreflect.EnumType {
	return &file_dmxProfiles_proto_enumTypes[1]
}

func (x DMXProfiles_DMXProfile_ChannelMapping_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DMXProfiles_DMXProfile_ChannelMapping_CommandType.Descriptor instead.
func (DMXProfiles_DMXProfile_ChannelMapping_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_dmxProfiles_proto_rawDescGZIP(), []int{0, 0, 1, 0}
}

type DMXProfiles_DMXProfile_Fixture_FixtureType int32

const (
	DMXProfiles_DMXProfile_Fixture_WORKSPACE DMXProfiles_DMXProfile_Fixture_FixtureType = 0
	DMXProfiles_DMXProfile_Fixture_LAYER     DMXProfiles_DMXProfile_Fixture_FixtureType = 1
)

// Enum value maps for DMXProfiles_DMXProfile_Fixture_FixtureType.
var (
	DMXProfiles_DMXProfile_Fixture_FixtureType_name = map[int32]string{
		0: "WORKSPACE",
		1: "LAYER",
	}
	DMXProfiles_DMXProfile_Fixture_FixtureType_value = map[string]int32{
		"WORKSPACE": 0,
		"LAYER":     1,
	}
)

func (x DMXProfiles_DMXProfile_Fixture_FixtureType) Enum() *DMXProfiles_DMXProfile_Fixture_FixtureType {
	p := new(DMXProfiles_DMXProfile_Fixture_FixtureType)
	*p = x
	return p
}

func (x DMXProfiles_DMXProfile_Fixture_FixtureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DMXProfiles_DMXProfile_Fixture_FixtureType) Descriptor() protoreflect.EnumDescriptor {
	return file_dmxProfiles_proto_enumTypes[2].Descriptor()
}

func (DMXProfiles_DMXProfile_Fixture_FixtureType) Type() protoreflect.EnumType {
	return &file_dmxProfiles_proto_enumTypes[2]
}

func (x DMXProfiles_DMXProfile_Fixture_FixtureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DMXProfiles_DMXProfile_Fixture_FixtureType.Descriptor instead.
func (DMXProfiles_DMXProfile_Fixture_FixtureType) EnumDescriptor() ([]byte, []int) {
	return file_dmxProfiles_proto_rawDescGZIP(), []int{0, 0, 2, 0}
}

type DMXProfiles struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	WorkspaceProfile *DMXProfiles_DMXProfile   `protobuf:"bytes,1,opt,name=workspaceProfile,proto3" json:"workspaceProfile,omitempty"`
	LayerProfiles    []*DMXProfiles_DMXProfile `protobuf:"bytes,2,rep,name=layerProfiles,proto3" json:"layerProfiles,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DMXProfiles) Reset() {
	*x = DMXProfiles{}
	mi := &file_dmxProfiles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMXProfiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMXProfiles) ProtoMessage() {}

func (x *DMXProfiles) ProtoReflect() protoreflect.Message {
	mi := &file_dmxProfiles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMXProfiles.ProtoReflect.Descriptor instead.
func (*DMXProfiles) Descriptor() ([]byte, []int) {
	return file_dmxProfiles_proto_rawDescGZIP(), []int{0}
}

func (x *DMXProfiles) GetWorkspaceProfile() *DMXProfiles_DMXProfile {
	if x != nil {
		return x.WorkspaceProfile
	}
	return nil
}

func (x *DMXProfiles) GetLayerProfiles() []*DMXProfiles_DMXProfile {
	if x != nil {
		return x.LayerProfiles
	}
	return nil
}

type DMXProfiles_DMXProfile struct {
	state          protoimpl.MessageState                   `protogen:"open.v1"`
	Profile        *DMXProfiles_DMXProfile_Profile          `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Fixture        *DMXProfiles_DMXProfile_Fixture          `protobuf:"bytes,2,opt,name=fixture,proto3" json:"fixture,omitempty"`
	IsEnabled      bool                                     `protobuf:"varint,3,opt,name=isEnabled,proto3" json:"isEnabled,omitempty"`
	CustomMappings []*DMXProfiles_DMXProfile_ChannelMapping `protobuf:"bytes,4,rep,name=customMappings,proto3" json:"customMappings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DMXProfiles_DMXProfile) Reset() {
	*x = DMXProfiles_DMXProfile{}
	mi := &file_dmxProfiles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMXProfiles_DMXProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMXProfiles_DMXProfile) ProtoMessage() {}

func (x *DMXProfiles_DMXProfile) ProtoReflect() protoreflect.Message {
	mi := &file_dmxProfiles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMXProfiles_DMXProfile.ProtoReflect.Descriptor instead.
func (*DMXProfiles_DMXProfile) Descriptor() ([]byte, []int) {
	return file_dmxProfiles_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DMXProfiles_DMXProfile) GetProfile() *DMXProfiles_DMXProfile_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *DMXProfiles_DMXProfile) GetFixture() *DMXProfiles_DMXProfile_Fixture {
	if x != nil {
		return x.Fixture
	}
	return nil
}

func (x *DMXProfiles_DMXProfile) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *DMXProfiles_DMXProfile) GetCustomMappings() []*DMXProfiles_DMXProfile_ChannelMapping {
	if x != nil {
		return x.CustomMappings
	}
	return nil
}

type DMXProfiles_DMXProfile_Profile struct {
	state       protoimpl.MessageState                     `protogen:"open.v1"`
	ProfileType DMXProfiles_DMXProfile_Profile_ProfileType `protobuf:"varint,1,opt,name=profileType,proto3,enum=rv.data.DMXProfiles_DMXProfile_Profile_ProfileType" json:"profileType,omitempty"`
	// Types that are valid to be assigned to StartingChannelOneof:
	//
	//	*DMXProfiles_DMXProfile_Profile_StartingChannel
	StartingChannelOneof isDMXProfiles_DMXProfile_Profile_StartingChannelOneof `protobuf_oneof:"startingChannel_oneof"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DMXProfiles_DMXProfile_Profile) Reset() {
	*x = DMXProfiles_DMXProfile_Profile{}
	mi := &file_dmxProfiles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMXProfiles_DMXProfile_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMXProfiles_DMXProfile_Profile) ProtoMessage() {}

func (x *DMXProfiles_DMXProfile_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_dmxProfiles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMXProfiles_DMXProfile_Profile.ProtoReflect.Descriptor instead.
func (*DMXProfiles_DMXProfile_Profile) Descriptor() ([]byte, []int) {
	return file_dmxProfiles_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *DMXProfiles_DMXProfile_Profile) GetProfileType() DMXProfiles_DMXProfile_Profile_ProfileType {
	if x != nil {
		return x.ProfileType
	}
	return DMXProfiles_DMXProfile_Profile_BASIC
}

func (x *DMXProfiles_DMXProfile_Profile) GetStartingChannelOneof() isDMXProfiles_DMXProfile_Profile_StartingChannelOneof {
	if x != nil {
		return x.StartingChannelOneof
	}
	return nil
}

func (x *DMXProfiles_DMXProfile_Profile) GetStartingChannel() uint32 {
	if x != nil {
		if x, ok := x.StartingChannelOneof.(*DMXProfiles_DMXProfile_Profile_StartingChannel); ok {
			return x.StartingChannel
		}
	}
	return 0
}

type isDMXProfiles_DMXProfile_Profile_StartingChannelOneof interface {
	isDMXProfiles_DMXProfile_Profile_StartingChannelOneof()
}

type DMXProfiles_DMXProfile_Profile_StartingChannel struct {
	StartingChannel uint32 `protobuf:"varint,2,opt,name=startingChannel,proto3,oneof"`
}

func (*DMXProfiles_DMXProfile_Profile_StartingChannel) isDMXProfiles_DMXProfile_Profile_StartingChannelOneof() {
}

type DMXProfiles_DMXProfile_ChannelMapping struct {
	state         protoimpl.MessageState                            `protogen:"open.v1"`
	ChannelIndex  uint32                                            `protobuf:"varint,1,opt,name=channelIndex,proto3" json:"channelIndex,omitempty"`
	Command       DMXProfiles_DMXProfile_ChannelMapping_CommandType `protobuf:"varint,2,opt,name=command,proto3,enum=rv.data.DMXProfiles_DMXProfile_ChannelMapping_CommandType" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DMXProfiles_DMXProfile_ChannelMapping) Reset() {
	*x = DMXProfiles_DMXProfile_ChannelMapping{}
	mi := &file_dmxProfiles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMXProfiles_DMXProfile_ChannelMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMXProfiles_DMXProfile_ChannelMapping) ProtoMessage() {}

func (x *DMXProfiles_DMXProfile_ChannelMapping) ProtoReflect() protoreflect.Message {
	mi := &file_dmxProfiles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMXProfiles_DMXProfile_ChannelMapping.ProtoReflect.Descriptor instead.
func (*DMXProfiles_DMXProfile_ChannelMapping) Descriptor() ([]byte, []int) {
	return file_dmxProfiles_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *DMXProfiles_DMXProfile_ChannelMapping) GetChannelIndex() uint32 {
	if x != nil {
		return x.ChannelIndex
	}
	return 0
}

func (x *DMXProfiles_DMXProfile_ChannelMapping) GetCommand() DMXProfiles_DMXProfile_ChannelMapping_CommandType {
	if x != nil {
		return x.Command
	}
	return DMXProfiles_DMXProfile_ChannelMapping_OPACITY
}

type DMXProfiles_DMXProfile_Fixture struct {
	state       protoimpl.MessageState                     `protogen:"open.v1"`
	FixtureType DMXProfiles_DMXProfile_Fixture_FixtureType `protobuf:"varint,1,opt,name=fixtureType,proto3,enum=rv.data.DMXProfiles_DMXProfile_Fixture_FixtureType" json:"fixtureType,omitempty"`
	// Types that are valid to be assigned to LayerIndexOneof:
	//
	//	*DMXProfiles_DMXProfile_Fixture_LayerIndex
	LayerIndexOneof isDMXProfiles_DMXProfile_Fixture_LayerIndexOneof `protobuf_oneof:"layerIndex_oneof"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DMXProfiles_DMXProfile_Fixture) Reset() {
	*x = DMXProfiles_DMXProfile_Fixture{}
	mi := &file_dmxProfiles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMXProfiles_DMXProfile_Fixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMXProfiles_DMXProfile_Fixture) ProtoMessage() {}

func (x *DMXProfiles_DMXProfile_Fixture) ProtoReflect() protoreflect.Message {
	mi := &file_dmxProfiles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMXProfiles_DMXProfile_Fixture.ProtoReflect.Descriptor instead.
func (*DMXProfiles_DMXProfile_Fixture) Descriptor() ([]byte, []int) {
	return file_dmxProfiles_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *DMXProfiles_DMXProfile_Fixture) GetFixtureType() DMXProfiles_DMXProfile_Fixture_FixtureType {
	if x != nil {
		return x.FixtureType
	}
	return DMXProfiles_DMXProfile_Fixture_WORKSPACE
}

func (x *DMXProfiles_DMXProfile_Fixture) GetLayerIndexOneof() isDMXProfiles_DMXProfile_Fixture_LayerIndexOneof {
	if x != nil {
		return x.LayerIndexOneof
	}
	return nil
}

func (x *DMXProfiles_DMXProfile_Fixture) GetLayerIndex() uint32 {
	if x != nil {
		if x, ok := x.LayerIndexOneof.(*DMXProfiles_DMXProfile_Fixture_LayerIndex); ok {
			return x.LayerIndex
		}
	}
	return 0
}

type isDMXProfiles_DMXProfile_Fixture_LayerIndexOneof interface {
	isDMXProfiles_DMXProfile_Fixture_LayerIndexOneof()
}

type DMXProfiles_DMXProfile_Fixture_LayerIndex struct {
	LayerIndex uint32 `protobuf:"varint,2,opt,name=layerIndex,proto3,oneof"`
}

func (*DMXProfiles_DMXProfile_Fixture_LayerIndex) isDMXProfiles_DMXProfile_Fixture_LayerIndexOneof() {
}

var File_dmxProfiles_proto protoreflect.FileDescriptor

const file_dmxProfiles_proto_rawDesc = "" +
	"\n" +
	"\x11dmxProfiles.proto\x12\arv.data\"\xfb\b\n" +
	"\vDMXProfiles\x12K\n" +
	"\x10workspaceProfile\x18\x01 \x01(\v2\x1f.rv.data.DMXProfiles.DMXProfileR\x10workspaceProfile\x12E\n" +
	"\rlayerProfiles\x18\x02 \x03(\v2\x1f.rv.data.DMXProfiles.DMXProfileR\rlayerProfiles\x1a\xd7\a\n" +
	"\n" +
	"DMXProfile\x12A\n" +
	"\aprofile\x18\x01 \x01(\v2'.rv.data.DMXProfiles.DMXProfile.ProfileR\aprofile\x12A\n" +
	"\afixture\x18\x02 \x01(\v2'.rv.data.DMXProfiles.DMXProfile.FixtureR\afixture\x12\x1c\n" +
	"\tisEnabled\x18\x03 \x01(\bR\tisEnabled\x12V\n" +
	"\x0ecustomMappings\x18\x04 \x03(\v2..rv.data.DMXProfiles.DMXProfile.ChannelMappingR\x0ecustomMappings\x1a\xd9\x01\n" +
	"\aProfile\x12U\n" +
	"\vprofileType\x18\x01 \x01(\x0e23.rv.data.DMXProfiles.DMXProfile.Profile.ProfileTypeR\vprofileType\x12*\n" +
	"\x0fstartingChannel\x18\x02 \x01(\rH\x00R\x0fstartingChannel\"2\n" +
	"\vProfileType\x12\t\n" +
	"\x05BASIC\x10\x00\x12\f\n" +
	"\bADVANCED\x10\x01\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x02B\x17\n" +
	"\x15startingChannel_oneof\x1a\xae\x02\n" +
	"\x0eChannelMapping\x12\"\n" +
	"\fchannelIndex\x18\x01 \x01(\rR\fchannelIndex\x12T\n" +
	"\acommand\x18\x02 \x01(\x0e2:.rv.data.DMXProfiles.DMXProfile.ChannelMapping.CommandTypeR\acommand\"\xa1\x01\n" +
	"\vCommandType\x12\v\n" +
	"\aOPACITY\x10\x00\x12\x0e\n" +
	"\n" +
	"BLEND_MODE\x10\x01\x12\x0e\n" +
	"\n" +
	"SELECT_CUE\x10\x02\x12\x10\n" +
	"\fCONTROL_TYPE\x10\x03\x12\x11\n" +
	"\rCONTROL_VALUE\x10\x04\x12\x17\n" +
	"\x13TRANSITION_DURATION\x10\x05\x12\x13\n" +
	"\x0fSELECT_PLAYLIST\x10\x06\x12\x12\n" +
	"\x0eTARGETED_LAYER\x10\a\x1a\xbf\x01\n" +
	"\aFixture\x12U\n" +
	"\vfixtureType\x18\x01 \x01(\x0e23.rv.data.DMXProfiles.DMXProfile.Fixture.FixtureTypeR\vfixtureType\x12 \n" +
	"\n" +
	"layerIndex\x18\x02 \x01(\rH\x00R\n" +
	"layerIndex\"'\n" +
	"\vFixtureType\x12\r\n" +
	"\tWORKSPACE\x10\x00\x12\t\n" +
	"\x05LAYER\x10\x01B\x12\n" +
	"\x10layerIndex_oneofB\x97\x01\n" +
	"\vcom.rv.dataB\x10DmxProfilesProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_dmxProfiles_proto_rawDescOnce sync.Once
	file_dmxProfiles_proto_rawDescData []byte
)

func file_dmxProfiles_proto_rawDescGZIP() []byte {
	file_dmxProfiles_proto_rawDescOnce.Do(func() {
		file_dmxProfiles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dmxProfiles_proto_rawDesc), len(file_dmxProfiles_proto_rawDesc)))
	})
	return file_dmxProfiles_proto_rawDescData
}

var file_dmxProfiles_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dmxProfiles_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dmxProfiles_proto_goTypes = []any{
	(DMXProfiles_DMXProfile_Profile_ProfileType)(0),        // 0: rv.data.DMXProfiles.DMXProfile.Profile.ProfileType
	(DMXProfiles_DMXProfile_ChannelMapping_CommandType)(0), // 1: rv.data.DMXProfiles.DMXProfile.ChannelMapping.CommandType
	(DMXProfiles_DMXProfile_Fixture_FixtureType)(0),        // 2: rv.data.DMXProfiles.DMXProfile.Fixture.FixtureType
	(*DMXProfiles)(nil),                           // 3: rv.data.DMXProfiles
	(*DMXProfiles_DMXProfile)(nil),                // 4: rv.data.DMXProfiles.DMXProfile
	(*DMXProfiles_DMXProfile_Profile)(nil),        // 5: rv.data.DMXProfiles.DMXProfile.Profile
	(*DMXProfiles_DMXProfile_ChannelMapping)(nil), // 6: rv.data.DMXProfiles.DMXProfile.ChannelMapping
	(*DMXProfiles_DMXProfile_Fixture)(nil),        // 7: rv.data.DMXProfiles.DMXProfile.Fixture
}
var file_dmxProfiles_proto_depIdxs = []int32{
	4, // 0: rv.data.DMXProfiles.workspaceProfile:type_name -> rv.data.DMXProfiles.DMXProfile
	4, // 1: rv.data.DMXProfiles.layerProfiles:type_name -> rv.data.DMXProfiles.DMXProfile
	5, // 2: rv.data.DMXProfiles.DMXProfile.profile:type_name -> rv.data.DMXProfiles.DMXProfile.Profile
	7, // 3: rv.data.DMXProfiles.DMXProfile.fixture:type_name -> rv.data.DMXProfiles.DMXProfile.Fixture
	6, // 4: rv.data.DMXProfiles.DMXProfile.customMappings:type_name -> rv.data.DMXProfiles.DMXProfile.ChannelMapping
	0, // 5: rv.data.DMXProfiles.DMXProfile.Profile.profileType:type_name -> rv.data.DMXProfiles.DMXProfile.Profile.ProfileType
	1, // 6: rv.data.DMXProfiles.DMXProfile.ChannelMapping.command:type_name -> rv.data.DMXProfiles.DMXProfile.ChannelMapping.CommandType
	2, // 7: rv.data.DMXProfiles.DMXProfile.Fixture.fixtureType:type_name -> rv.data.DMXProfiles.DMXProfile.Fixture.FixtureType
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_dmxProfiles_proto_init() }
func file_dmxProfiles_proto_init() {
	if File_dmxProfiles_proto != nil {
		return
	}
	file_dmxProfiles_proto_msgTypes[2].OneofWrappers = []any{
		(*DMXProfiles_DMXProfile_Profile_StartingChannel)(nil),
	}
	file_dmxProfiles_proto_msgTypes[4].OneofWrappers = []any{
		(*DMXProfiles_DMXProfile_Fixture_LayerIndex)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dmxProfiles_proto_rawDesc), len(file_dmxProfiles_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dmxProfiles_proto_goTypes,
		DependencyIndexes: file_dmxProfiles_proto_depIdxs,
		EnumInfos:         file_dmxProfiles_proto_enumTypes,
		MessageInfos:      file_dmxProfiles_proto_msgTypes,
	}.Build()
	File_dmxProfiles_proto = out.File
	file_dmxProfiles_proto_goTypes = nil
	file_dmxProfiles_proto_depIdxs = nil
}
