// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: effects.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Effect_EffectVariable_EffectDirection_EffectDirection int32

const (
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_NONE         Effect_EffectVariable_EffectDirection_EffectDirection = 0
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_TOP_LEFT     Effect_EffectVariable_EffectDirection_EffectDirection = 1
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_TOP          Effect_EffectVariable_EffectDirection_EffectDirection = 2
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_TOP_RIGHT    Effect_EffectVariable_EffectDirection_EffectDirection = 4
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_LEFT         Effect_EffectVariable_EffectDirection_EffectDirection = 8
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_CENTER       Effect_EffectVariable_EffectDirection_EffectDirection = 16
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_RIGHT        Effect_EffectVariable_EffectDirection_EffectDirection = 32
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_BOTTOM_LEFT  Effect_EffectVariable_EffectDirection_EffectDirection = 64
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_BOTTOM       Effect_EffectVariable_EffectDirection_EffectDirection = 128
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_BOTTOM_RIGHT Effect_EffectVariable_EffectDirection_EffectDirection = 256
)

// Enum value maps for Effect_EffectVariable_EffectDirection_EffectDirection.
var (
	Effect_EffectVariable_EffectDirection_EffectDirection_name = map[int32]string{
		0:   "EFFECT_DIRECTION_NONE",
		1:   "EFFECT_DIRECTION_TOP_LEFT",
		2:   "EFFECT_DIRECTION_TOP",
		4:   "EFFECT_DIRECTION_TOP_RIGHT",
		8:   "EFFECT_DIRECTION_LEFT",
		16:  "EFFECT_DIRECTION_CENTER",
		32:  "EFFECT_DIRECTION_RIGHT",
		64:  "EFFECT_DIRECTION_BOTTOM_LEFT",
		128: "EFFECT_DIRECTION_BOTTOM",
		256: "EFFECT_DIRECTION_BOTTOM_RIGHT",
	}
	Effect_EffectVariable_EffectDirection_EffectDirection_value = map[string]int32{
		"EFFECT_DIRECTION_NONE":         0,
		"EFFECT_DIRECTION_TOP_LEFT":     1,
		"EFFECT_DIRECTION_TOP":          2,
		"EFFECT_DIRECTION_TOP_RIGHT":    4,
		"EFFECT_DIRECTION_LEFT":         8,
		"EFFECT_DIRECTION_CENTER":       16,
		"EFFECT_DIRECTION_RIGHT":        32,
		"EFFECT_DIRECTION_BOTTOM_LEFT":  64,
		"EFFECT_DIRECTION_BOTTOM":       128,
		"EFFECT_DIRECTION_BOTTOM_RIGHT": 256,
	}
)

func (x Effect_EffectVariable_EffectDirection_EffectDirection) Enum() *Effect_EffectVariable_EffectDirection_EffectDirection {
	p := new(Effect_EffectVariable_EffectDirection_EffectDirection)
	*p = x
	return p
}

func (x Effect_EffectVariable_EffectDirection_EffectDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Effect_EffectVariable_EffectDirection_EffectDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_effects_proto_enumTypes[0].Descriptor()
}

func (Effect_EffectVariable_EffectDirection_EffectDirection) Type() protoreflect.EnumType {
	return &file_effects_proto_enumTypes[0]
}

func (x Effect_EffectVariable_EffectDirection_EffectDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Effect_EffectVariable_EffectDirection_EffectDirection.Descriptor instead.
func (Effect_EffectVariable_EffectDirection_EffectDirection) EnumDescriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 4, 0}
}

type Effect struct {
	state               protoimpl.MessageState   `protogen:"open.v1"`
	Uuid                *UUID                    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Enabled             bool                     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name                string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RenderId            string                   `protobuf:"bytes,4,opt,name=render_id,json=renderId,proto3" json:"render_id,omitempty"`
	BehaviorDescription string                   `protobuf:"bytes,5,opt,name=behavior_description,json=behaviorDescription,proto3" json:"behavior_description,omitempty"`
	Category            string                   `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Variables           []*Effect_EffectVariable `protobuf:"bytes,7,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_effects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0}
}

func (x *Effect) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Effect) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Effect) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Effect) GetRenderId() string {
	if x != nil {
		return x.RenderId
	}
	return ""
}

func (x *Effect) GetBehaviorDescription() string {
	if x != nil {
		return x.BehaviorDescription
	}
	return ""
}

func (x *Effect) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Effect) GetVariables() []*Effect_EffectVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type Transition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      float64                `protobuf:"fixed64,1,opt,name=duration,proto3" json:"duration,omitempty"`
	FavoriteUuid  *UUID                  `protobuf:"bytes,2,opt,name=favorite_uuid,json=favoriteUuid,proto3" json:"favorite_uuid,omitempty"`
	Effect        *Effect                `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transition) Reset() {
	*x = Transition{}
	mi := &file_effects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition) ProtoMessage() {}

func (x *Transition) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition.ProtoReflect.Descriptor instead.
func (*Transition) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{1}
}

func (x *Transition) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Transition) GetFavoriteUuid() *UUID {
	if x != nil {
		return x.FavoriteUuid
	}
	return nil
}

func (x *Transition) GetEffect() *Effect {
	if x != nil {
		return x.Effect
	}
	return nil
}

type Effect_EffectVariable struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*Effect_EffectVariable_Int
	//	*Effect_EffectVariable_Float
	//	*Effect_EffectVariable_Color
	//	*Effect_EffectVariable_Direction
	//	*Effect_EffectVariable_Double
	Type          isEffect_EffectVariable_Type `protobuf_oneof:"Type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_EffectVariable) Reset() {
	*x = Effect_EffectVariable{}
	mi := &file_effects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_EffectVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable) ProtoMessage() {}

func (x *Effect_EffectVariable) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Effect_EffectVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Effect_EffectVariable) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Effect_EffectVariable) GetType() isEffect_EffectVariable_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Effect_EffectVariable) GetInt() *Effect_EffectVariable_EffectInt {
	if x != nil {
		if x, ok := x.Type.(*Effect_EffectVariable_Int); ok {
			return x.Int
		}
	}
	return nil
}

func (x *Effect_EffectVariable) GetFloat() *Effect_EffectVariable_EffectFloat {
	if x != nil {
		if x, ok := x.Type.(*Effect_EffectVariable_Float); ok {
			return x.Float
		}
	}
	return nil
}

func (x *Effect_EffectVariable) GetColor() *Effect_EffectVariable_EffectColor {
	if x != nil {
		if x, ok := x.Type.(*Effect_EffectVariable_Color); ok {
			return x.Color
		}
	}
	return nil
}

func (x *Effect_EffectVariable) GetDirection() *Effect_EffectVariable_EffectDirection {
	if x != nil {
		if x, ok := x.Type.(*Effect_EffectVariable_Direction); ok {
			return x.Direction
		}
	}
	return nil
}

func (x *Effect_EffectVariable) GetDouble() *Effect_EffectVariable_EffectDouble {
	if x != nil {
		if x, ok := x.Type.(*Effect_EffectVariable_Double); ok {
			return x.Double
		}
	}
	return nil
}

type isEffect_EffectVariable_Type interface {
	isEffect_EffectVariable_Type()
}

type Effect_EffectVariable_Int struct {
	Int *Effect_EffectVariable_EffectInt `protobuf:"bytes,3,opt,name=int,proto3,oneof"`
}

type Effect_EffectVariable_Float struct {
	Float *Effect_EffectVariable_EffectFloat `protobuf:"bytes,4,opt,name=float,proto3,oneof"`
}

type Effect_EffectVariable_Color struct {
	Color *Effect_EffectVariable_EffectColor `protobuf:"bytes,5,opt,name=color,proto3,oneof"`
}

type Effect_EffectVariable_Direction struct {
	Direction *Effect_EffectVariable_EffectDirection `protobuf:"bytes,6,opt,name=direction,proto3,oneof"`
}

type Effect_EffectVariable_Double struct {
	Double *Effect_EffectVariable_EffectDouble `protobuf:"bytes,7,opt,name=double,proto3,oneof"`
}

func (*Effect_EffectVariable_Int) isEffect_EffectVariable_Type() {}

func (*Effect_EffectVariable_Float) isEffect_EffectVariable_Type() {}

func (*Effect_EffectVariable_Color) isEffect_EffectVariable_Type() {}

func (*Effect_EffectVariable_Direction) isEffect_EffectVariable_Type() {}

func (*Effect_EffectVariable_Double) isEffect_EffectVariable_Type() {}

type Effect_Preset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *UUID                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Effects       []*Effect              `protobuf:"bytes,3,rep,name=effects,proto3" json:"effects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_Preset) Reset() {
	*x = Effect_Preset{}
	mi := &file_effects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_Preset) ProtoMessage() {}

func (x *Effect_Preset) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_Preset.ProtoReflect.Descriptor instead.
func (*Effect_Preset) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Effect_Preset) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Effect_Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Effect_Preset) GetEffects() []*Effect {
	if x != nil {
		return x.Effects
	}
	return nil
}

type Effect_EffectVariable_EffectInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	DefaultValue  int32                  `protobuf:"varint,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Min           int32                  `protobuf:"varint,3,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,4,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_EffectVariable_EffectInt) Reset() {
	*x = Effect_EffectVariable_EffectInt{}
	mi := &file_effects_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_EffectVariable_EffectInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable_EffectInt) ProtoMessage() {}

func (x *Effect_EffectVariable_EffectInt) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable_EffectInt.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable_EffectInt) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Effect_EffectVariable_EffectInt) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Effect_EffectVariable_EffectInt) GetDefaultValue() int32 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

func (x *Effect_EffectVariable_EffectInt) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Effect_EffectVariable_EffectInt) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Effect_EffectVariable_EffectFloat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float32                `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	DefaultValue  float32                `protobuf:"fixed32,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Min           float32                `protobuf:"fixed32,3,opt,name=min,proto3" json:"min,omitempty"`
	Max           float32                `protobuf:"fixed32,4,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_EffectVariable_EffectFloat) Reset() {
	*x = Effect_EffectVariable_EffectFloat{}
	mi := &file_effects_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_EffectVariable_EffectFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable_EffectFloat) ProtoMessage() {}

func (x *Effect_EffectVariable_EffectFloat) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable_EffectFloat.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable_EffectFloat) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Effect_EffectVariable_EffectFloat) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Effect_EffectVariable_EffectFloat) GetDefaultValue() float32 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

func (x *Effect_EffectVariable_EffectFloat) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Effect_EffectVariable_EffectFloat) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Effect_EffectVariable_EffectDouble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	DefaultValue  float64                `protobuf:"fixed64,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Min           float64                `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_EffectVariable_EffectDouble) Reset() {
	*x = Effect_EffectVariable_EffectDouble{}
	mi := &file_effects_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_EffectVariable_EffectDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable_EffectDouble) ProtoMessage() {}

func (x *Effect_EffectVariable_EffectDouble) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable_EffectDouble.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable_EffectDouble) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *Effect_EffectVariable_EffectDouble) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Effect_EffectVariable_EffectDouble) GetDefaultValue() float64 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

func (x *Effect_EffectVariable_EffectDouble) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Effect_EffectVariable_EffectDouble) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Effect_EffectVariable_EffectColor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *Color                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	DefaultColor  *Color                 `protobuf:"bytes,2,opt,name=default_color,json=defaultColor,proto3" json:"default_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_EffectVariable_EffectColor) Reset() {
	*x = Effect_EffectVariable_EffectColor{}
	mi := &file_effects_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_EffectVariable_EffectColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable_EffectColor) ProtoMessage() {}

func (x *Effect_EffectVariable_EffectColor) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable_EffectColor.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable_EffectColor) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *Effect_EffectVariable_EffectColor) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Effect_EffectVariable_EffectColor) GetDefaultColor() *Color {
	if x != nil {
		return x.DefaultColor
	}
	return nil
}

type Effect_EffectVariable_EffectDirection struct {
	state               protoimpl.MessageState                                `protogen:"open.v1"`
	Direction           Effect_EffectVariable_EffectDirection_EffectDirection `protobuf:"varint,1,opt,name=direction,proto3,enum=rv.data.Effect_EffectVariable_EffectDirection_EffectDirection" json:"direction,omitempty"`
	DefaultDirection    Effect_EffectVariable_EffectDirection_EffectDirection `protobuf:"varint,2,opt,name=default_direction,json=defaultDirection,proto3,enum=rv.data.Effect_EffectVariable_EffectDirection_EffectDirection" json:"default_direction,omitempty"`
	AvailableDirections uint32                                                `protobuf:"varint,3,opt,name=available_directions,json=availableDirections,proto3" json:"available_directions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Effect_EffectVariable_EffectDirection) Reset() {
	*x = Effect_EffectVariable_EffectDirection{}
	mi := &file_effects_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_EffectVariable_EffectDirection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable_EffectDirection) ProtoMessage() {}

func (x *Effect_EffectVariable_EffectDirection) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable_EffectDirection.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable_EffectDirection) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 4}
}

func (x *Effect_EffectVariable_EffectDirection) GetDirection() Effect_EffectVariable_EffectDirection_EffectDirection {
	if x != nil {
		return x.Direction
	}
	return Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_NONE
}

func (x *Effect_EffectVariable_EffectDirection) GetDefaultDirection() Effect_EffectVariable_EffectDirection_EffectDirection {
	if x != nil {
		return x.DefaultDirection
	}
	return Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_NONE
}

func (x *Effect_EffectVariable_EffectDirection) GetAvailableDirections() uint32 {
	if x != nil {
		return x.AvailableDirections
	}
	return 0
}

type Transition_Preset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *UUID                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Transition    *Transition            `protobuf:"bytes,3,opt,name=transition,proto3" json:"transition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transition_Preset) Reset() {
	*x = Transition_Preset{}
	mi := &file_effects_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transition_Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition_Preset) ProtoMessage() {}

func (x *Transition_Preset) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition_Preset.ProtoReflect.Descriptor instead.
func (*Transition_Preset) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Transition_Preset) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Transition_Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Transition_Preset) GetTransition() *Transition {
	if x != nil {
		return x.Transition
	}
	return nil
}

var File_effects_proto protoreflect.FileDescriptor

const file_effects_proto_rawDesc = "" +
	"\n" +
	"\reffects.proto\x12\arv.data\x1a\x10basicTypes.proto\"\xa2\x0e\n" +
	"\x06Effect\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\trender_id\x18\x04 \x01(\tR\brenderId\x121\n" +
	"\x14behavior_description\x18\x05 \x01(\tR\x13behaviorDescription\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12<\n" +
	"\tvariables\x18\a \x03(\v2\x1e.rv.data.Effect.EffectVariableR\tvariables\x1a\xb0\v\n" +
	"\x0eEffectVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12<\n" +
	"\x03int\x18\x03 \x01(\v2(.rv.data.Effect.EffectVariable.EffectIntH\x00R\x03int\x12B\n" +
	"\x05float\x18\x04 \x01(\v2*.rv.data.Effect.EffectVariable.EffectFloatH\x00R\x05float\x12B\n" +
	"\x05color\x18\x05 \x01(\v2*.rv.data.Effect.EffectVariable.EffectColorH\x00R\x05color\x12N\n" +
	"\tdirection\x18\x06 \x01(\v2..rv.data.Effect.EffectVariable.EffectDirectionH\x00R\tdirection\x12E\n" +
	"\x06double\x18\a \x01(\v2+.rv.data.Effect.EffectVariable.EffectDoubleH\x00R\x06double\x1aj\n" +
	"\tEffectInt\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12#\n" +
	"\rdefault_value\x18\x02 \x01(\x05R\fdefaultValue\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x05R\x03max\x1al\n" +
	"\vEffectFloat\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x02R\x05value\x12#\n" +
	"\rdefault_value\x18\x02 \x01(\x02R\fdefaultValue\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x02R\x03max\x1am\n" +
	"\fEffectDouble\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12#\n" +
	"\rdefault_value\x18\x02 \x01(\x01R\fdefaultValue\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x01R\x03max\x1ah\n" +
	"\vEffectColor\x12$\n" +
	"\x05color\x18\x01 \x01(\v2\x0e.rv.data.ColorR\x05color\x123\n" +
	"\rdefault_color\x18\x02 \x01(\v2\x0e.rv.data.ColorR\fdefaultColor\x1a\xcf\x04\n" +
	"\x0fEffectDirection\x12\\\n" +
	"\tdirection\x18\x01 \x01(\x0e2>.rv.data.Effect.EffectVariable.EffectDirection.EffectDirectionR\tdirection\x12k\n" +
	"\x11default_direction\x18\x02 \x01(\x0e2>.rv.data.Effect.EffectVariable.EffectDirection.EffectDirectionR\x10defaultDirection\x121\n" +
	"\x14available_directions\x18\x03 \x01(\rR\x13availableDirections\"\xbd\x02\n" +
	"\x0fEffectDirection\x12\x19\n" +
	"\x15EFFECT_DIRECTION_NONE\x10\x00\x12\x1d\n" +
	"\x19EFFECT_DIRECTION_TOP_LEFT\x10\x01\x12\x18\n" +
	"\x14EFFECT_DIRECTION_TOP\x10\x02\x12\x1e\n" +
	"\x1aEFFECT_DIRECTION_TOP_RIGHT\x10\x04\x12\x19\n" +
	"\x15EFFECT_DIRECTION_LEFT\x10\b\x12\x1b\n" +
	"\x17EFFECT_DIRECTION_CENTER\x10\x10\x12\x1a\n" +
	"\x16EFFECT_DIRECTION_RIGHT\x10 \x12 \n" +
	"\x1cEFFECT_DIRECTION_BOTTOM_LEFT\x10@\x12\x1c\n" +
	"\x17EFFECT_DIRECTION_BOTTOM\x10\x80\x01\x12\"\n" +
	"\x1dEFFECT_DIRECTION_BOTTOM_RIGHT\x10\x80\x02B\x06\n" +
	"\x04Type\x1aj\n" +
	"\x06Preset\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\aeffects\x18\x03 \x03(\v2\x0f.rv.data.EffectR\aeffects\"\xfb\x01\n" +
	"\n" +
	"Transition\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\x01R\bduration\x122\n" +
	"\rfavorite_uuid\x18\x02 \x01(\v2\r.rv.data.UUIDR\ffavoriteUuid\x12'\n" +
	"\x06effect\x18\x03 \x01(\v2\x0f.rv.data.EffectR\x06effect\x1at\n" +
	"\x06Preset\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\n" +
	"transition\x18\x03 \x01(\v2\x13.rv.data.TransitionR\n" +
	"transitionB\x93\x01\n" +
	"\vcom.rv.dataB\fEffectsProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_effects_proto_rawDescOnce sync.Once
	file_effects_proto_rawDescData []byte
)

func file_effects_proto_rawDescGZIP() []byte {
	file_effects_proto_rawDescOnce.Do(func() {
		file_effects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_effects_proto_rawDesc), len(file_effects_proto_rawDesc)))
	})
	return file_effects_proto_rawDescData
}

var file_effects_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_effects_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_effects_proto_goTypes = []any{
	(Effect_EffectVariable_EffectDirection_EffectDirection)(0), // 0: rv.data.Effect.EffectVariable.EffectDirection.EffectDirection
	(*Effect)(nil),                                // 1: rv.data.Effect
	(*Transition)(nil),                            // 2: rv.data.Transition
	(*Effect_EffectVariable)(nil),                 // 3: rv.data.Effect.EffectVariable
	(*Effect_Preset)(nil),                         // 4: rv.data.Effect.Preset
	(*Effect_EffectVariable_EffectInt)(nil),       // 5: rv.data.Effect.EffectVariable.EffectInt
	(*Effect_EffectVariable_EffectFloat)(nil),     // 6: rv.data.Effect.EffectVariable.EffectFloat
	(*Effect_EffectVariable_EffectDouble)(nil),    // 7: rv.data.Effect.EffectVariable.EffectDouble
	(*Effect_EffectVariable_EffectColor)(nil),     // 8: rv.data.Effect.EffectVariable.EffectColor
	(*Effect_EffectVariable_EffectDirection)(nil), // 9: rv.data.Effect.EffectVariable.EffectDirection
	(*Transition_Preset)(nil),                     // 10: rv.data.Transition.Preset
	(*UUID)(nil),                                  // 11: rv.data.UUID
	(*Color)(nil),                                 // 12: rv.data.Color
}
var file_effects_proto_depIdxs = []int32{
	11, // 0: rv.data.Effect.uuid:type_name -> rv.data.UUID
	3,  // 1: rv.data.Effect.variables:type_name -> rv.data.Effect.EffectVariable
	11, // 2: rv.data.Transition.favorite_uuid:type_name -> rv.data.UUID
	1,  // 3: rv.data.Transition.effect:type_name -> rv.data.Effect
	5,  // 4: rv.data.Effect.EffectVariable.int:type_name -> rv.data.Effect.EffectVariable.EffectInt
	6,  // 5: rv.data.Effect.EffectVariable.float:type_name -> rv.data.Effect.EffectVariable.EffectFloat
	8,  // 6: rv.data.Effect.EffectVariable.color:type_name -> rv.data.Effect.EffectVariable.EffectColor
	9,  // 7: rv.data.Effect.EffectVariable.direction:type_name -> rv.data.Effect.EffectVariable.EffectDirection
	7,  // 8: rv.data.Effect.EffectVariable.double:type_name -> rv.data.Effect.EffectVariable.EffectDouble
	11, // 9: rv.data.Effect.Preset.uuid:type_name -> rv.data.UUID
	1,  // 10: rv.data.Effect.Preset.effects:type_name -> rv.data.Effect
	12, // 11: rv.data.Effect.EffectVariable.EffectColor.color:type_name -> rv.data.Color
	12, // 12: rv.data.Effect.EffectVariable.EffectColor.default_color:type_name -> rv.data.Color
	0,  // 13: rv.data.Effect.EffectVariable.EffectDirection.direction:type_name -> rv.data.Effect.EffectVariable.EffectDirection.EffectDirection
	0,  // 14: rv.data.Effect.EffectVariable.EffectDirection.default_direction:type_name -> rv.data.Effect.EffectVariable.EffectDirection.EffectDirection
	11, // 15: rv.data.Transition.Preset.uuid:type_name -> rv.data.UUID
	2,  // 16: rv.data.Transition.Preset.transition:type_name -> rv.data.Transition
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_effects_proto_init() }
func file_effects_proto_init() {
	if File_effects_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_effects_proto_msgTypes[2].OneofWrappers = []any{
		(*Effect_EffectVariable_Int)(nil),
		(*Effect_EffectVariable_Float)(nil),
		(*Effect_EffectVariable_Color)(nil),
		(*Effect_EffectVariable_Direction)(nil),
		(*Effect_EffectVariable_Double)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_effects_proto_rawDesc), len(file_effects_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_effects_proto_goTypes,
		DependencyIndexes: file_effects_proto_depIdxs,
		EnumInfos:         file_effects_proto_enumTypes,
		MessageInfos:      file_effects_proto_msgTypes,
	}.Build()
	File_effects_proto = out.File
	file_effects_proto_goTypes = nil
	file_effects_proto_depIdxs = nil
}
