// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: groups.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Group struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Uuid                       *UUID                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color                      *Color                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	HotKey                     *HotKey                `protobuf:"bytes,4,opt,name=hotKey,proto3" json:"hotKey,omitempty"`
	ApplicationGroupIdentifier *UUID                  `protobuf:"bytes,5,opt,name=application_group_identifier,json=applicationGroupIdentifier,proto3" json:"application_group_identifier,omitempty"`
	ApplicationGroupName       string                 `protobuf:"bytes,6,opt,name=application_group_name,json=applicationGroupName,proto3" json:"application_group_name,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_groups_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Group) GetHotKey() *HotKey {
	if x != nil {
		return x.HotKey
	}
	return nil
}

func (x *Group) GetApplicationGroupIdentifier() *UUID {
	if x != nil {
		return x.ApplicationGroupIdentifier
	}
	return nil
}

func (x *Group) GetApplicationGroupName() string {
	if x != nil {
		return x.ApplicationGroupName
	}
	return ""
}

type ProGroupsDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProGroupsDocument) Reset() {
	*x = ProGroupsDocument{}
	mi := &file_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProGroupsDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProGroupsDocument) ProtoMessage() {}

func (x *ProGroupsDocument) ProtoReflect() protoreflect.Message {
	mi := &file_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProGroupsDocument.ProtoReflect.Descriptor instead.
func (*ProGroupsDocument) Descriptor() ([]byte, []int) {
	return file_groups_proto_rawDescGZIP(), []int{1}
}

func (x *ProGroupsDocument) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_groups_proto protoreflect.FileDescriptor

const file_groups_proto_rawDesc = "" +
	"\n" +
	"\fgroups.proto\x12\arv.data\x1a\x10basicTypes.proto\x1a\fhotKey.proto\"\x94\x02\n" +
	"\x05Group\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x05color\x18\x03 \x01(\v2\x0e.rv.data.ColorR\x05color\x12'\n" +
	"\x06hotKey\x18\x04 \x01(\v2\x0f.rv.data.HotKeyR\x06hotKey\x12O\n" +
	"\x1capplication_group_identifier\x18\x05 \x01(\v2\r.rv.data.UUIDR\x1aapplicationGroupIdentifier\x124\n" +
	"\x16application_group_name\x18\x06 \x01(\tR\x14applicationGroupName\";\n" +
	"\x11ProGroupsDocument\x12&\n" +
	"\x06groups\x18\x01 \x03(\v2\x0e.rv.data.GroupR\x06groupsB\x92\x01\n" +
	"\vcom.rv.dataB\vGroupsProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_groups_proto_rawDescOnce sync.Once
	file_groups_proto_rawDescData []byte
)

func file_groups_proto_rawDescGZIP() []byte {
	file_groups_proto_rawDescOnce.Do(func() {
		file_groups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_groups_proto_rawDesc), len(file_groups_proto_rawDesc)))
	})
	return file_groups_proto_rawDescData
}

var file_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_groups_proto_goTypes = []any{
	(*Group)(nil),             // 0: rv.data.Group
	(*ProGroupsDocument)(nil), // 1: rv.data.ProGroupsDocument
	(*UUID)(nil),              // 2: rv.data.UUID
	(*Color)(nil),             // 3: rv.data.Color
	(*HotKey)(nil),            // 4: rv.data.HotKey
}
var file_groups_proto_depIdxs = []int32{
	2, // 0: rv.data.Group.uuid:type_name -> rv.data.UUID
	3, // 1: rv.data.Group.color:type_name -> rv.data.Color
	4, // 2: rv.data.Group.hotKey:type_name -> rv.data.HotKey
	2, // 3: rv.data.Group.application_group_identifier:type_name -> rv.data.UUID
	0, // 4: rv.data.ProGroupsDocument.groups:type_name -> rv.data.Group
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_groups_proto_init() }
func file_groups_proto_init() {
	if File_groups_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_hotKey_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_groups_proto_rawDesc), len(file_groups_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_groups_proto_goTypes,
		DependencyIndexes: file_groups_proto_depIdxs,
		MessageInfos:      file_groups_proto_msgTypes,
	}.Build()
	File_groups_proto = out.File
	file_groups_proto_goTypes = nil
	file_groups_proto_depIdxs = nil
}
