// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: keymapping.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyMapping_ComputerKeyboard_ModifierFlags int32

const (
	KeyMapping_ComputerKeyboard_MODIFIERFLAGS_COMMAND_KEY  KeyMapping_ComputerKeyboard_ModifierFlags = 0
	KeyMapping_ComputerKeyboard_MODIFIERFLAGS_SHIFT_KEY    KeyMapping_ComputerKeyboard_ModifierFlags = 1
	KeyMapping_ComputerKeyboard_MODIFIERFLAGS_OPTION_KEY   KeyMapping_ComputerKeyboard_ModifierFlags = 2
	KeyMapping_ComputerKeyboard_MODIFIERFLAGS_CONTROL_KEY  KeyMapping_ComputerKeyboard_ModifierFlags = 3
	KeyMapping_ComputerKeyboard_MODIFIERFLAGS_FUNCTION_KEY KeyMapping_ComputerKeyboard_ModifierFlags = 4
)

// Enum value maps for KeyMapping_ComputerKeyboard_ModifierFlags.
var (
	KeyMapping_ComputerKeyboard_ModifierFlags_name = map[int32]string{
		0: "MODIFIERFLAGS_COMMAND_KEY",
		1: "MODIFIERFLAGS_SHIFT_KEY",
		2: "MODIFIERFLAGS_OPTION_KEY",
		3: "MODIFIERFLAGS_CONTROL_KEY",
		4: "MODIFIERFLAGS_FUNCTION_KEY",
	}
	KeyMapping_ComputerKeyboard_ModifierFlags_value = map[string]int32{
		"MODIFIERFLAGS_COMMAND_KEY":  0,
		"MODIFIERFLAGS_SHIFT_KEY":    1,
		"MODIFIERFLAGS_OPTION_KEY":   2,
		"MODIFIERFLAGS_CONTROL_KEY":  3,
		"MODIFIERFLAGS_FUNCTION_KEY": 4,
	}
)

func (x KeyMapping_ComputerKeyboard_ModifierFlags) Enum() *KeyMapping_ComputerKeyboard_ModifierFlags {
	p := new(KeyMapping_ComputerKeyboard_ModifierFlags)
	*p = x
	return p
}

func (x KeyMapping_ComputerKeyboard_ModifierFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyMapping_ComputerKeyboard_ModifierFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_keymapping_proto_enumTypes[0].Descriptor()
}

func (KeyMapping_ComputerKeyboard_ModifierFlags) Type() protoreflect.EnumType {
	return &file_keymapping_proto_enumTypes[0]
}

func (x KeyMapping_ComputerKeyboard_ModifierFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyMapping_ComputerKeyboard_ModifierFlags.Descriptor instead.
func (KeyMapping_ComputerKeyboard_ModifierFlags) EnumDescriptor() ([]byte, []int) {
	return file_keymapping_proto_rawDescGZIP(), []int{0, 0, 0}
}

type KeyMapping struct {
	state    protoimpl.MessageState       `protogen:"open.v1"`
	Keyboard *KeyMapping_ComputerKeyboard `protobuf:"bytes,1,opt,name=keyboard,proto3" json:"keyboard,omitempty"`
	Midi     *KeyMapping_MIDIKeyboard     `protobuf:"bytes,2,opt,name=midi,proto3" json:"midi,omitempty"`
	// Types that are valid to be assigned to TargetIdentifier:
	//
	//	*KeyMapping_MenuItem
	//	*KeyMapping_ClearGroupIdentifier
	//	*KeyMapping_CueIdentifier
	//	*KeyMapping_GroupIdentifier
	//	*KeyMapping_MacroIdentifier
	//	*KeyMapping_PropIdentifier
	//	*KeyMapping_TimerIdentifier
	TargetIdentifier isKeyMapping_TargetIdentifier `protobuf_oneof:"TargetIdentifier"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KeyMapping) Reset() {
	*x = KeyMapping{}
	mi := &file_keymapping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMapping) ProtoMessage() {}

func (x *KeyMapping) ProtoReflect() protoreflect.Message {
	mi := &file_keymapping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMapping.ProtoReflect.Descriptor instead.
func (*KeyMapping) Descriptor() ([]byte, []int) {
	return file_keymapping_proto_rawDescGZIP(), []int{0}
}

func (x *KeyMapping) GetKeyboard() *KeyMapping_ComputerKeyboard {
	if x != nil {
		return x.Keyboard
	}
	return nil
}

func (x *KeyMapping) GetMidi() *KeyMapping_MIDIKeyboard {
	if x != nil {
		return x.Midi
	}
	return nil
}

func (x *KeyMapping) GetTargetIdentifier() isKeyMapping_TargetIdentifier {
	if x != nil {
		return x.TargetIdentifier
	}
	return nil
}

func (x *KeyMapping) GetMenuItem() string {
	if x != nil {
		if x, ok := x.TargetIdentifier.(*KeyMapping_MenuItem); ok {
			return x.MenuItem
		}
	}
	return ""
}

func (x *KeyMapping) GetClearGroupIdentifier() *CollectionElementType {
	if x != nil {
		if x, ok := x.TargetIdentifier.(*KeyMapping_ClearGroupIdentifier); ok {
			return x.ClearGroupIdentifier
		}
	}
	return nil
}

func (x *KeyMapping) GetCueIdentifier() *CollectionElementType {
	if x != nil {
		if x, ok := x.TargetIdentifier.(*KeyMapping_CueIdentifier); ok {
			return x.CueIdentifier
		}
	}
	return nil
}

func (x *KeyMapping) GetGroupIdentifier() *CollectionElementType {
	if x != nil {
		if x, ok := x.TargetIdentifier.(*KeyMapping_GroupIdentifier); ok {
			return x.GroupIdentifier
		}
	}
	return nil
}

func (x *KeyMapping) GetMacroIdentifier() *CollectionElementType {
	if x != nil {
		if x, ok := x.TargetIdentifier.(*KeyMapping_MacroIdentifier); ok {
			return x.MacroIdentifier
		}
	}
	return nil
}

func (x *KeyMapping) GetPropIdentifier() *CollectionElementType {
	if x != nil {
		if x, ok := x.TargetIdentifier.(*KeyMapping_PropIdentifier); ok {
			return x.PropIdentifier
		}
	}
	return nil
}

func (x *KeyMapping) GetTimerIdentifier() *CollectionElementType {
	if x != nil {
		if x, ok := x.TargetIdentifier.(*KeyMapping_TimerIdentifier); ok {
			return x.TimerIdentifier
		}
	}
	return nil
}

type isKeyMapping_TargetIdentifier interface {
	isKeyMapping_TargetIdentifier()
}

type KeyMapping_MenuItem struct {
	MenuItem string `protobuf:"bytes,100,opt,name=menu_item,json=menuItem,proto3,oneof"`
}

type KeyMapping_ClearGroupIdentifier struct {
	ClearGroupIdentifier *CollectionElementType `protobuf:"bytes,101,opt,name=clear_group_identifier,json=clearGroupIdentifier,proto3,oneof"`
}

type KeyMapping_CueIdentifier struct {
	CueIdentifier *CollectionElementType `protobuf:"bytes,102,opt,name=cue_identifier,json=cueIdentifier,proto3,oneof"`
}

type KeyMapping_GroupIdentifier struct {
	GroupIdentifier *CollectionElementType `protobuf:"bytes,103,opt,name=group_identifier,json=groupIdentifier,proto3,oneof"`
}

type KeyMapping_MacroIdentifier struct {
	MacroIdentifier *CollectionElementType `protobuf:"bytes,104,opt,name=macro_identifier,json=macroIdentifier,proto3,oneof"`
}

type KeyMapping_PropIdentifier struct {
	PropIdentifier *CollectionElementType `protobuf:"bytes,105,opt,name=prop_identifier,json=propIdentifier,proto3,oneof"`
}

type KeyMapping_TimerIdentifier struct {
	TimerIdentifier *CollectionElementType `protobuf:"bytes,106,opt,name=timer_identifier,json=timerIdentifier,proto3,oneof"`
}

func (*KeyMapping_MenuItem) isKeyMapping_TargetIdentifier() {}

func (*KeyMapping_ClearGroupIdentifier) isKeyMapping_TargetIdentifier() {}

func (*KeyMapping_CueIdentifier) isKeyMapping_TargetIdentifier() {}

func (*KeyMapping_GroupIdentifier) isKeyMapping_TargetIdentifier() {}

func (*KeyMapping_MacroIdentifier) isKeyMapping_TargetIdentifier() {}

func (*KeyMapping_PropIdentifier) isKeyMapping_TargetIdentifier() {}

func (*KeyMapping_TimerIdentifier) isKeyMapping_TargetIdentifier() {}

type KeyMappingDocument struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApplicationInfo    *ApplicationInfo       `protobuf:"bytes,1,opt,name=application_info,json=applicationInfo,proto3" json:"application_info,omitempty"`
	Keymappings        []*KeyMapping          `protobuf:"bytes,2,rep,name=keymappings,proto3" json:"keymappings,omitempty"`
	MacosKeymappings   []*KeyMapping          `protobuf:"bytes,3,rep,name=macos_keymappings,json=macosKeymappings,proto3" json:"macos_keymappings,omitempty"`
	WindowsKeymappings []*KeyMapping          `protobuf:"bytes,4,rep,name=windows_keymappings,json=windowsKeymappings,proto3" json:"windows_keymappings,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *KeyMappingDocument) Reset() {
	*x = KeyMappingDocument{}
	mi := &file_keymapping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMappingDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMappingDocument) ProtoMessage() {}

func (x *KeyMappingDocument) ProtoReflect() protoreflect.Message {
	mi := &file_keymapping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMappingDocument.ProtoReflect.Descriptor instead.
func (*KeyMappingDocument) Descriptor() ([]byte, []int) {
	return file_keymapping_proto_rawDescGZIP(), []int{1}
}

func (x *KeyMappingDocument) GetApplicationInfo() *ApplicationInfo {
	if x != nil {
		return x.ApplicationInfo
	}
	return nil
}

func (x *KeyMappingDocument) GetKeymappings() []*KeyMapping {
	if x != nil {
		return x.Keymappings
	}
	return nil
}

func (x *KeyMappingDocument) GetMacosKeymappings() []*KeyMapping {
	if x != nil {
		return x.MacosKeymappings
	}
	return nil
}

func (x *KeyMappingDocument) GetWindowsKeymappings() []*KeyMapping {
	if x != nil {
		return x.WindowsKeymappings
	}
	return nil
}

type KeyMapping_ComputerKeyboard struct {
	state                      protoimpl.MessageState                      `protogen:"open.v1"`
	KeyEquivalent              string                                      `protobuf:"bytes,1,opt,name=key_equivalent,json=keyEquivalent,proto3" json:"key_equivalent,omitempty"`
	KeyEquivalentModifierFlags []KeyMapping_ComputerKeyboard_ModifierFlags `protobuf:"varint,2,rep,packed,name=key_equivalent_modifier_flags,json=keyEquivalentModifierFlags,proto3,enum=rv.data.KeyMapping_ComputerKeyboard_ModifierFlags" json:"key_equivalent_modifier_flags,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *KeyMapping_ComputerKeyboard) Reset() {
	*x = KeyMapping_ComputerKeyboard{}
	mi := &file_keymapping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMapping_ComputerKeyboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMapping_ComputerKeyboard) ProtoMessage() {}

func (x *KeyMapping_ComputerKeyboard) ProtoReflect() protoreflect.Message {
	mi := &file_keymapping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMapping_ComputerKeyboard.ProtoReflect.Descriptor instead.
func (*KeyMapping_ComputerKeyboard) Descriptor() ([]byte, []int) {
	return file_keymapping_proto_rawDescGZIP(), []int{0, 0}
}

func (x *KeyMapping_ComputerKeyboard) GetKeyEquivalent() string {
	if x != nil {
		return x.KeyEquivalent
	}
	return ""
}

func (x *KeyMapping_ComputerKeyboard) GetKeyEquivalentModifierFlags() []KeyMapping_ComputerKeyboard_ModifierFlags {
	if x != nil {
		return x.KeyEquivalentModifierFlags
	}
	return nil
}

type KeyMapping_MIDIKeyboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       int32                  `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Pitch         int32                  `protobuf:"varint,2,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Velocity      int32                  `protobuf:"varint,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyMapping_MIDIKeyboard) Reset() {
	*x = KeyMapping_MIDIKeyboard{}
	mi := &file_keymapping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMapping_MIDIKeyboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMapping_MIDIKeyboard) ProtoMessage() {}

func (x *KeyMapping_MIDIKeyboard) ProtoReflect() protoreflect.Message {
	mi := &file_keymapping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMapping_MIDIKeyboard.ProtoReflect.Descriptor instead.
func (*KeyMapping_MIDIKeyboard) Descriptor() ([]byte, []int) {
	return file_keymapping_proto_rawDescGZIP(), []int{0, 1}
}

func (x *KeyMapping_MIDIKeyboard) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *KeyMapping_MIDIKeyboard) GetPitch() int32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *KeyMapping_MIDIKeyboard) GetVelocity() int32 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

var File_keymapping_proto protoreflect.FileDescriptor

const file_keymapping_proto_rawDesc = "" +
	"\n" +
	"\x10keymapping.proto\x12\arv.data\x1a\x10basicTypes.proto\"\xc4\b\n" +
	"\n" +
	"KeyMapping\x12@\n" +
	"\bkeyboard\x18\x01 \x01(\v2$.rv.data.KeyMapping.ComputerKeyboardR\bkeyboard\x124\n" +
	"\x04midi\x18\x02 \x01(\v2 .rv.data.KeyMapping.MIDIKeyboardR\x04midi\x12\x1d\n" +
	"\tmenu_item\x18d \x01(\tH\x00R\bmenuItem\x12V\n" +
	"\x16clear_group_identifier\x18e \x01(\v2\x1e.rv.data.CollectionElementTypeH\x00R\x14clearGroupIdentifier\x12G\n" +
	"\x0ecue_identifier\x18f \x01(\v2\x1e.rv.data.CollectionElementTypeH\x00R\rcueIdentifier\x12K\n" +
	"\x10group_identifier\x18g \x01(\v2\x1e.rv.data.CollectionElementTypeH\x00R\x0fgroupIdentifier\x12K\n" +
	"\x10macro_identifier\x18h \x01(\v2\x1e.rv.data.CollectionElementTypeH\x00R\x0fmacroIdentifier\x12I\n" +
	"\x0fprop_identifier\x18i \x01(\v2\x1e.rv.data.CollectionElementTypeH\x00R\x0epropIdentifier\x12K\n" +
	"\x10timer_identifier\x18j \x01(\v2\x1e.rv.data.CollectionElementTypeH\x00R\x0ftimerIdentifier\x1a\xdb\x02\n" +
	"\x10ComputerKeyboard\x12%\n" +
	"\x0ekey_equivalent\x18\x01 \x01(\tR\rkeyEquivalent\x12u\n" +
	"\x1dkey_equivalent_modifier_flags\x18\x02 \x03(\x0e22.rv.data.KeyMapping.ComputerKeyboard.ModifierFlagsR\x1akeyEquivalentModifierFlags\"\xa8\x01\n" +
	"\rModifierFlags\x12\x1d\n" +
	"\x19MODIFIERFLAGS_COMMAND_KEY\x10\x00\x12\x1b\n" +
	"\x17MODIFIERFLAGS_SHIFT_KEY\x10\x01\x12\x1c\n" +
	"\x18MODIFIERFLAGS_OPTION_KEY\x10\x02\x12\x1d\n" +
	"\x19MODIFIERFLAGS_CONTROL_KEY\x10\x03\x12\x1e\n" +
	"\x1aMODIFIERFLAGS_FUNCTION_KEY\x10\x04\x1aZ\n" +
	"\fMIDIKeyboard\x12\x18\n" +
	"\achannel\x18\x01 \x01(\x05R\achannel\x12\x14\n" +
	"\x05pitch\x18\x02 \x01(\x05R\x05pitch\x12\x1a\n" +
	"\bvelocity\x18\x03 \x01(\x05R\bvelocityB\x12\n" +
	"\x10TargetIdentifier\"\x98\x02\n" +
	"\x12KeyMappingDocument\x12C\n" +
	"\x10application_info\x18\x01 \x01(\v2\x18.rv.data.ApplicationInfoR\x0fapplicationInfo\x125\n" +
	"\vkeymappings\x18\x02 \x03(\v2\x13.rv.data.KeyMappingR\vkeymappings\x12@\n" +
	"\x11macos_keymappings\x18\x03 \x03(\v2\x13.rv.data.KeyMappingR\x10macosKeymappings\x12D\n" +
	"\x13windows_keymappings\x18\x04 \x03(\v2\x13.rv.data.KeyMappingR\x12windowsKeymappingsB\x96\x01\n" +
	"\vcom.rv.dataB\x0fKeymappingProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_keymapping_proto_rawDescOnce sync.Once
	file_keymapping_proto_rawDescData []byte
)

func file_keymapping_proto_rawDescGZIP() []byte {
	file_keymapping_proto_rawDescOnce.Do(func() {
		file_keymapping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keymapping_proto_rawDesc), len(file_keymapping_proto_rawDesc)))
	})
	return file_keymapping_proto_rawDescData
}

var file_keymapping_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keymapping_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_keymapping_proto_goTypes = []any{
	(KeyMapping_ComputerKeyboard_ModifierFlags)(0), // 0: rv.data.KeyMapping.ComputerKeyboard.ModifierFlags
	(*KeyMapping)(nil),                  // 1: rv.data.KeyMapping
	(*KeyMappingDocument)(nil),          // 2: rv.data.KeyMappingDocument
	(*KeyMapping_ComputerKeyboard)(nil), // 3: rv.data.KeyMapping.ComputerKeyboard
	(*KeyMapping_MIDIKeyboard)(nil),     // 4: rv.data.KeyMapping.MIDIKeyboard
	(*CollectionElementType)(nil),       // 5: rv.data.CollectionElementType
	(*ApplicationInfo)(nil),             // 6: rv.data.ApplicationInfo
}
var file_keymapping_proto_depIdxs = []int32{
	3,  // 0: rv.data.KeyMapping.keyboard:type_name -> rv.data.KeyMapping.ComputerKeyboard
	4,  // 1: rv.data.KeyMapping.midi:type_name -> rv.data.KeyMapping.MIDIKeyboard
	5,  // 2: rv.data.KeyMapping.clear_group_identifier:type_name -> rv.data.CollectionElementType
	5,  // 3: rv.data.KeyMapping.cue_identifier:type_name -> rv.data.CollectionElementType
	5,  // 4: rv.data.KeyMapping.group_identifier:type_name -> rv.data.CollectionElementType
	5,  // 5: rv.data.KeyMapping.macro_identifier:type_name -> rv.data.CollectionElementType
	5,  // 6: rv.data.KeyMapping.prop_identifier:type_name -> rv.data.CollectionElementType
	5,  // 7: rv.data.KeyMapping.timer_identifier:type_name -> rv.data.CollectionElementType
	6,  // 8: rv.data.KeyMappingDocument.application_info:type_name -> rv.data.ApplicationInfo
	1,  // 9: rv.data.KeyMappingDocument.keymappings:type_name -> rv.data.KeyMapping
	1,  // 10: rv.data.KeyMappingDocument.macos_keymappings:type_name -> rv.data.KeyMapping
	1,  // 11: rv.data.KeyMappingDocument.windows_keymappings:type_name -> rv.data.KeyMapping
	0,  // 12: rv.data.KeyMapping.ComputerKeyboard.key_equivalent_modifier_flags:type_name -> rv.data.KeyMapping.ComputerKeyboard.ModifierFlags
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_keymapping_proto_init() }
func file_keymapping_proto_init() {
	if File_keymapping_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_keymapping_proto_msgTypes[0].OneofWrappers = []any{
		(*KeyMapping_MenuItem)(nil),
		(*KeyMapping_ClearGroupIdentifier)(nil),
		(*KeyMapping_CueIdentifier)(nil),
		(*KeyMapping_GroupIdentifier)(nil),
		(*KeyMapping_MacroIdentifier)(nil),
		(*KeyMapping_PropIdentifier)(nil),
		(*KeyMapping_TimerIdentifier)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keymapping_proto_rawDesc), len(file_keymapping_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keymapping_proto_goTypes,
		DependencyIndexes: file_keymapping_proto_depIdxs,
		EnumInfos:         file_keymapping_proto_enumTypes,
		MessageInfos:      file_keymapping_proto_msgTypes,
	}.Build()
	File_keymapping_proto = out.File
	file_keymapping_proto_goTypes = nil
	file_keymapping_proto_depIdxs = nil
}
