// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: labels.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProLabelsDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*Action_Label        `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProLabelsDocument) Reset() {
	*x = ProLabelsDocument{}
	mi := &file_labels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProLabelsDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProLabelsDocument) ProtoMessage() {}

func (x *ProLabelsDocument) ProtoReflect() protoreflect.Message {
	mi := &file_labels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProLabelsDocument.ProtoReflect.Descriptor instead.
func (*ProLabelsDocument) Descriptor() ([]byte, []int) {
	return file_labels_proto_rawDescGZIP(), []int{0}
}

func (x *ProLabelsDocument) GetLabels() []*Action_Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_labels_proto protoreflect.FileDescriptor

const file_labels_proto_rawDesc = "" +
	"\n" +
	"\flabels.proto\x12\arv.data\x1a\faction.proto\"B\n" +
	"\x11ProLabelsDocument\x12-\n" +
	"\x06labels\x18\x01 \x03(\v2\x15.rv.data.Action.LabelR\x06labelsB\x91\x01\n" +
	"\vcom.rv.dataB\vLabelsProtoP\x01Z8github.com/thatguycleeb/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_labels_proto_rawDescOnce sync.Once
	file_labels_proto_rawDescData []byte
)

func file_labels_proto_rawDescGZIP() []byte {
	file_labels_proto_rawDescOnce.Do(func() {
		file_labels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_labels_proto_rawDesc), len(file_labels_proto_rawDesc)))
	})
	return file_labels_proto_rawDescData
}

var file_labels_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_labels_proto_goTypes = []any{
	(*ProLabelsDocument)(nil), // 0: rv.data.ProLabelsDocument
	(*Action_Label)(nil),      // 1: rv.data.Action.Label
}
var file_labels_proto_depIdxs = []int32{
	1, // 0: rv.data.ProLabelsDocument.labels:type_name -> rv.data.Action.Label
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_labels_proto_init() }
func file_labels_proto_init() {
	if File_labels_proto != nil {
		return
	}
	file_action_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_labels_proto_rawDesc), len(file_labels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_labels_proto_goTypes,
		DependencyIndexes: file_labels_proto_depIdxs,
		MessageInfos:      file_labels_proto_msgTypes,
	}.Build()
	File_labels_proto = out.File
	file_labels_proto_goTypes = nil
	file_labels_proto_depIdxs = nil
}
