// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: layers.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Layer_BlendMode int32

const (
	Layer_BLEND_MODE_NORMAL        Layer_BlendMode = 0
	Layer_BLEND_MODE_DISSOLVE      Layer_BlendMode = 1
	Layer_BLEND_MODE_DARKEN        Layer_BlendMode = 2
	Layer_BLEND_MODE_MULTIPLY      Layer_BlendMode = 3
	Layer_BLEND_MODE_COLOR_BURN    Layer_BlendMode = 4
	Layer_BLEND_MODE_LINEAR_BURN   Layer_BlendMode = 5
	Layer_BLEND_MODE_DARKER_COLOR  Layer_BlendMode = 6
	Layer_BLEND_MODE_LIGHTEN       Layer_BlendMode = 7
	Layer_BLEND_MODE_SCREEN        Layer_BlendMode = 8
	Layer_BLEND_MODE_COLOR_DODGE   Layer_BlendMode = 9
	Layer_BLEND_MODE_LINEAR_DODGE  Layer_BlendMode = 10
	Layer_BLEND_MODE_LIGHTER_COLOR Layer_BlendMode = 11
	Layer_BLEND_MODE_OVERLAY       Layer_BlendMode = 12
	Layer_BLEND_MODE_SOFT_LIGHT    Layer_BlendMode = 13
	Layer_BLEND_MODE_HARD_LIGHT    Layer_BlendMode = 14
	Layer_BLEND_MODE_VIVID_LIGHT   Layer_BlendMode = 15
	Layer_BLEND_MODE_LINEAR_LIGHT  Layer_BlendMode = 16
	Layer_BLEND_MODE_PIN_LIGHT     Layer_BlendMode = 17
	Layer_BLEND_MODE_HARD_MIX      Layer_BlendMode = 18
	Layer_BLEND_MODE_DIFFERENCE    Layer_BlendMode = 19
	Layer_BLEND_MODE_EXCLUSION     Layer_BlendMode = 20
	Layer_BLEND_MODE_SUBTRACT      Layer_BlendMode = 21
	Layer_BLEND_MODE_DIVIDE        Layer_BlendMode = 22
	Layer_BLEND_MODE_HUE           Layer_BlendMode = 23
	Layer_BLEND_MODE_SATURATION    Layer_BlendMode = 24
	Layer_BLEND_MODE_COLOR         Layer_BlendMode = 25
	Layer_BLEND_MODE_LUMINOSITY    Layer_BlendMode = 26
)

// Enum value maps for Layer_BlendMode.
var (
	Layer_BlendMode_name = map[int32]string{
		0:  "BLEND_MODE_NORMAL",
		1:  "BLEND_MODE_DISSOLVE",
		2:  "BLEND_MODE_DARKEN",
		3:  "BLEND_MODE_MULTIPLY",
		4:  "BLEND_MODE_COLOR_BURN",
		5:  "BLEND_MODE_LINEAR_BURN",
		6:  "BLEND_MODE_DARKER_COLOR",
		7:  "BLEND_MODE_LIGHTEN",
		8:  "BLEND_MODE_SCREEN",
		9:  "BLEND_MODE_COLOR_DODGE",
		10: "BLEND_MODE_LINEAR_DODGE",
		11: "BLEND_MODE_LIGHTER_COLOR",
		12: "BLEND_MODE_OVERLAY",
		13: "BLEND_MODE_SOFT_LIGHT",
		14: "BLEND_MODE_HARD_LIGHT",
		15: "BLEND_MODE_VIVID_LIGHT",
		16: "BLEND_MODE_LINEAR_LIGHT",
		17: "BLEND_MODE_PIN_LIGHT",
		18: "BLEND_MODE_HARD_MIX",
		19: "BLEND_MODE_DIFFERENCE",
		20: "BLEND_MODE_EXCLUSION",
		21: "BLEND_MODE_SUBTRACT",
		22: "BLEND_MODE_DIVIDE",
		23: "BLEND_MODE_HUE",
		24: "BLEND_MODE_SATURATION",
		25: "BLEND_MODE_COLOR",
		26: "BLEND_MODE_LUMINOSITY",
	}
	Layer_BlendMode_value = map[string]int32{
		"BLEND_MODE_NORMAL":        0,
		"BLEND_MODE_DISSOLVE":      1,
		"BLEND_MODE_DARKEN":        2,
		"BLEND_MODE_MULTIPLY":      3,
		"BLEND_MODE_COLOR_BURN":    4,
		"BLEND_MODE_LINEAR_BURN":   5,
		"BLEND_MODE_DARKER_COLOR":  6,
		"BLEND_MODE_LIGHTEN":       7,
		"BLEND_MODE_SCREEN":        8,
		"BLEND_MODE_COLOR_DODGE":   9,
		"BLEND_MODE_LINEAR_DODGE":  10,
		"BLEND_MODE_LIGHTER_COLOR": 11,
		"BLEND_MODE_OVERLAY":       12,
		"BLEND_MODE_SOFT_LIGHT":    13,
		"BLEND_MODE_HARD_LIGHT":    14,
		"BLEND_MODE_VIVID_LIGHT":   15,
		"BLEND_MODE_LINEAR_LIGHT":  16,
		"BLEND_MODE_PIN_LIGHT":     17,
		"BLEND_MODE_HARD_MIX":      18,
		"BLEND_MODE_DIFFERENCE":    19,
		"BLEND_MODE_EXCLUSION":     20,
		"BLEND_MODE_SUBTRACT":      21,
		"BLEND_MODE_DIVIDE":        22,
		"BLEND_MODE_HUE":           23,
		"BLEND_MODE_SATURATION":    24,
		"BLEND_MODE_COLOR":         25,
		"BLEND_MODE_LUMINOSITY":    26,
	}
)

func (x Layer_BlendMode) Enum() *Layer_BlendMode {
	p := new(Layer_BlendMode)
	*p = x
	return p
}

func (x Layer_BlendMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layer_BlendMode) Descriptor() protoreflect.EnumDescriptor {
	return file_layers_proto_enumTypes[0].Descriptor()
}

func (Layer_BlendMode) Type() protoreflect.EnumType {
	return &file_layers_proto_enumTypes[0]
}

func (x Layer_BlendMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layer_BlendMode.Descriptor instead.
func (Layer_BlendMode) EnumDescriptor() ([]byte, []int) {
	return file_layers_proto_rawDescGZIP(), []int{0, 0}
}

type Layer_Blending_Standard_BlendMode int32

const (
	Layer_Blending_Standard_BLEND_MODE_NORMAL        Layer_Blending_Standard_BlendMode = 0
	Layer_Blending_Standard_BLEND_MODE_DISSOLVE      Layer_Blending_Standard_BlendMode = 1
	Layer_Blending_Standard_BLEND_MODE_DARKEN        Layer_Blending_Standard_BlendMode = 2
	Layer_Blending_Standard_BLEND_MODE_MULTIPLY      Layer_Blending_Standard_BlendMode = 3
	Layer_Blending_Standard_BLEND_MODE_COLOR_BURN    Layer_Blending_Standard_BlendMode = 4
	Layer_Blending_Standard_BLEND_MODE_LINEAR_BURN   Layer_Blending_Standard_BlendMode = 5
	Layer_Blending_Standard_BLEND_MODE_DARKER_COLOR  Layer_Blending_Standard_BlendMode = 6
	Layer_Blending_Standard_BLEND_MODE_LIGHTEN       Layer_Blending_Standard_BlendMode = 7
	Layer_Blending_Standard_BLEND_MODE_SCREEN        Layer_Blending_Standard_BlendMode = 8
	Layer_Blending_Standard_BLEND_MODE_COLOR_DODGE   Layer_Blending_Standard_BlendMode = 9
	Layer_Blending_Standard_BLEND_MODE_LINEAR_DODGE  Layer_Blending_Standard_BlendMode = 10
	Layer_Blending_Standard_BLEND_MODE_LIGHTER_COLOR Layer_Blending_Standard_BlendMode = 11
	Layer_Blending_Standard_BLEND_MODE_OVERLAY       Layer_Blending_Standard_BlendMode = 12
	Layer_Blending_Standard_BLEND_MODE_SOFT_LIGHT    Layer_Blending_Standard_BlendMode = 13
	Layer_Blending_Standard_BLEND_MODE_HARD_LIGHT    Layer_Blending_Standard_BlendMode = 14
	Layer_Blending_Standard_BLEND_MODE_VIVID_LIGHT   Layer_Blending_Standard_BlendMode = 15
	Layer_Blending_Standard_BLEND_MODE_LINEAR_LIGHT  Layer_Blending_Standard_BlendMode = 16
	Layer_Blending_Standard_BLEND_MODE_PIN_LIGHT     Layer_Blending_Standard_BlendMode = 17
	Layer_Blending_Standard_BLEND_MODE_HARD_MIX      Layer_Blending_Standard_BlendMode = 18
	Layer_Blending_Standard_BLEND_MODE_DIFFERENCE    Layer_Blending_Standard_BlendMode = 19
	Layer_Blending_Standard_BLEND_MODE_EXCLUSION     Layer_Blending_Standard_BlendMode = 20
	Layer_Blending_Standard_BLEND_MODE_SUBTRACT      Layer_Blending_Standard_BlendMode = 21
	Layer_Blending_Standard_BLEND_MODE_DIVIDE        Layer_Blending_Standard_BlendMode = 22
	Layer_Blending_Standard_BLEND_MODE_HUE           Layer_Blending_Standard_BlendMode = 23
	Layer_Blending_Standard_BLEND_MODE_SATURATION    Layer_Blending_Standard_BlendMode = 24
	Layer_Blending_Standard_BLEND_MODE_COLOR         Layer_Blending_Standard_BlendMode = 25
	Layer_Blending_Standard_BLEND_MODE_LUMINOSITY    Layer_Blending_Standard_BlendMode = 26
)

// Enum value maps for Layer_Blending_Standard_BlendMode.
var (
	Layer_Blending_Standard_BlendMode_name = map[int32]string{
		0:  "BLEND_MODE_NORMAL",
		1:  "BLEND_MODE_DISSOLVE",
		2:  "BLEND_MODE_DARKEN",
		3:  "BLEND_MODE_MULTIPLY",
		4:  "BLEND_MODE_COLOR_BURN",
		5:  "BLEND_MODE_LINEAR_BURN",
		6:  "BLEND_MODE_DARKER_COLOR",
		7:  "BLEND_MODE_LIGHTEN",
		8:  "BLEND_MODE_SCREEN",
		9:  "BLEND_MODE_COLOR_DODGE",
		10: "BLEND_MODE_LINEAR_DODGE",
		11: "BLEND_MODE_LIGHTER_COLOR",
		12: "BLEND_MODE_OVERLAY",
		13: "BLEND_MODE_SOFT_LIGHT",
		14: "BLEND_MODE_HARD_LIGHT",
		15: "BLEND_MODE_VIVID_LIGHT",
		16: "BLEND_MODE_LINEAR_LIGHT",
		17: "BLEND_MODE_PIN_LIGHT",
		18: "BLEND_MODE_HARD_MIX",
		19: "BLEND_MODE_DIFFERENCE",
		20: "BLEND_MODE_EXCLUSION",
		21: "BLEND_MODE_SUBTRACT",
		22: "BLEND_MODE_DIVIDE",
		23: "BLEND_MODE_HUE",
		24: "BLEND_MODE_SATURATION",
		25: "BLEND_MODE_COLOR",
		26: "BLEND_MODE_LUMINOSITY",
	}
	Layer_Blending_Standard_BlendMode_value = map[string]int32{
		"BLEND_MODE_NORMAL":        0,
		"BLEND_MODE_DISSOLVE":      1,
		"BLEND_MODE_DARKEN":        2,
		"BLEND_MODE_MULTIPLY":      3,
		"BLEND_MODE_COLOR_BURN":    4,
		"BLEND_MODE_LINEAR_BURN":   5,
		"BLEND_MODE_DARKER_COLOR":  6,
		"BLEND_MODE_LIGHTEN":       7,
		"BLEND_MODE_SCREEN":        8,
		"BLEND_MODE_COLOR_DODGE":   9,
		"BLEND_MODE_LINEAR_DODGE":  10,
		"BLEND_MODE_LIGHTER_COLOR": 11,
		"BLEND_MODE_OVERLAY":       12,
		"BLEND_MODE_SOFT_LIGHT":    13,
		"BLEND_MODE_HARD_LIGHT":    14,
		"BLEND_MODE_VIVID_LIGHT":   15,
		"BLEND_MODE_LINEAR_LIGHT":  16,
		"BLEND_MODE_PIN_LIGHT":     17,
		"BLEND_MODE_HARD_MIX":      18,
		"BLEND_MODE_DIFFERENCE":    19,
		"BLEND_MODE_EXCLUSION":     20,
		"BLEND_MODE_SUBTRACT":      21,
		"BLEND_MODE_DIVIDE":        22,
		"BLEND_MODE_HUE":           23,
		"BLEND_MODE_SATURATION":    24,
		"BLEND_MODE_COLOR":         25,
		"BLEND_MODE_LUMINOSITY":    26,
	}
)

func (x Layer_Blending_Standard_BlendMode) Enum() *Layer_Blending_Standard_BlendMode {
	p := new(Layer_Blending_Standard_BlendMode)
	*p = x
	return p
}

func (x Layer_Blending_Standard_BlendMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layer_Blending_Standard_BlendMode) Descriptor() protoreflect.EnumDescriptor {
	return file_layers_proto_enumTypes[1].Descriptor()
}

func (Layer_Blending_Standard_BlendMode) Type() protoreflect.EnumType {
	return &file_layers_proto_enumTypes[1]
}

func (x Layer_Blending_Standard_BlendMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layer_Blending_Standard_BlendMode.Descriptor instead.
func (Layer_Blending_Standard_BlendMode) EnumDescriptor() ([]byte, []int) {
	return file_layers_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

type Layer struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Uuid                  *UUID                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color                 *Color                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Muted                 bool                   `protobuf:"varint,4,opt,name=muted,proto3" json:"muted,omitempty"`
	Hidden                bool                   `protobuf:"varint,5,opt,name=hidden,proto3" json:"hidden,omitempty"`
	BlendMode             Layer_BlendMode        `protobuf:"varint,6,opt,name=blend_mode,json=blendMode,proto3,enum=rv.data.Layer_BlendMode" json:"blend_mode,omitempty"`
	Opacity               float64                `protobuf:"fixed64,7,opt,name=opacity,proto3" json:"opacity,omitempty"`
	SelectedTargetSetUuid *UUID                  `protobuf:"bytes,8,opt,name=selected_target_set_uuid,json=selectedTargetSetUuid,proto3" json:"selected_target_set_uuid,omitempty"`
	EffectsPresetUuid     *UUID                  `protobuf:"bytes,9,opt,name=effects_preset_uuid,json=effectsPresetUuid,proto3" json:"effects_preset_uuid,omitempty"`
	EffectsBuildDuration  float64                `protobuf:"fixed64,10,opt,name=effects_build_duration,json=effectsBuildDuration,proto3" json:"effects_build_duration,omitempty"`
	LayerPresetUuid       *UUID                  `protobuf:"bytes,11,opt,name=layer_preset_uuid,json=layerPresetUuid,proto3" json:"layer_preset_uuid,omitempty"`
	HotKey                *HotKey                `protobuf:"bytes,12,opt,name=hot_key,json=hotKey,proto3" json:"hot_key,omitempty"`
	Transition            *Transition            `protobuf:"bytes,13,opt,name=transition,proto3" json:"transition,omitempty"`
	Effects               []*Effect              `protobuf:"bytes,14,rep,name=effects,proto3" json:"effects,omitempty"`
	Blend                 *Layer_Blending        `protobuf:"bytes,15,opt,name=blend,proto3" json:"blend,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Layer) Reset() {
	*x = Layer{}
	mi := &file_layers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_layers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_layers_proto_rawDescGZIP(), []int{0}
}

func (x *Layer) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Layer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Layer) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Layer) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *Layer) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Layer) GetBlendMode() Layer_BlendMode {
	if x != nil {
		return x.BlendMode
	}
	return Layer_BLEND_MODE_NORMAL
}

func (x *Layer) GetOpacity() float64 {
	if x != nil {
		return x.Opacity
	}
	return 0
}

func (x *Layer) GetSelectedTargetSetUuid() *UUID {
	if x != nil {
		return x.SelectedTargetSetUuid
	}
	return nil
}

func (x *Layer) GetEffectsPresetUuid() *UUID {
	if x != nil {
		return x.EffectsPresetUuid
	}
	return nil
}

func (x *Layer) GetEffectsBuildDuration() float64 {
	if x != nil {
		return x.EffectsBuildDuration
	}
	return 0
}

func (x *Layer) GetLayerPresetUuid() *UUID {
	if x != nil {
		return x.LayerPresetUuid
	}
	return nil
}

func (x *Layer) GetHotKey() *HotKey {
	if x != nil {
		return x.HotKey
	}
	return nil
}

func (x *Layer) GetTransition() *Transition {
	if x != nil {
		return x.Transition
	}
	return nil
}

func (x *Layer) GetEffects() []*Effect {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *Layer) GetBlend() *Layer_Blending {
	if x != nil {
		return x.Blend
	}
	return nil
}

type Layer_Preset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *UUID                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Layer         *Layer                 `protobuf:"bytes,3,opt,name=layer,proto3" json:"layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer_Preset) Reset() {
	*x = Layer_Preset{}
	mi := &file_layers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer_Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer_Preset) ProtoMessage() {}

func (x *Layer_Preset) ProtoReflect() protoreflect.Message {
	mi := &file_layers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer_Preset.ProtoReflect.Descriptor instead.
func (*Layer_Preset) Descriptor() ([]byte, []int) {
	return file_layers_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Layer_Preset) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Layer_Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Layer_Preset) GetLayer() *Layer {
	if x != nil {
		return x.Layer
	}
	return nil
}

type Layer_Blending struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to BlendingType:
	//
	//	*Layer_Blending_Standard_
	//	*Layer_Blending_Matte_
	BlendingType  isLayer_Blending_BlendingType `protobuf_oneof:"BlendingType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer_Blending) Reset() {
	*x = Layer_Blending{}
	mi := &file_layers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer_Blending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer_Blending) ProtoMessage() {}

func (x *Layer_Blending) ProtoReflect() protoreflect.Message {
	mi := &file_layers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer_Blending.ProtoReflect.Descriptor instead.
func (*Layer_Blending) Descriptor() ([]byte, []int) {
	return file_layers_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Layer_Blending) GetBlendingType() isLayer_Blending_BlendingType {
	if x != nil {
		return x.BlendingType
	}
	return nil
}

func (x *Layer_Blending) GetStandard() *Layer_Blending_Standard {
	if x != nil {
		if x, ok := x.BlendingType.(*Layer_Blending_Standard_); ok {
			return x.Standard
		}
	}
	return nil
}

func (x *Layer_Blending) GetMatte() *Layer_Blending_Matte {
	if x != nil {
		if x, ok := x.BlendingType.(*Layer_Blending_Matte_); ok {
			return x.Matte
		}
	}
	return nil
}

type isLayer_Blending_BlendingType interface {
	isLayer_Blending_BlendingType()
}

type Layer_Blending_Standard_ struct {
	Standard *Layer_Blending_Standard `protobuf:"bytes,1,opt,name=standard,proto3,oneof"`
}

type Layer_Blending_Matte_ struct {
	Matte *Layer_Blending_Matte `protobuf:"bytes,2,opt,name=matte,proto3,oneof"`
}

func (*Layer_Blending_Standard_) isLayer_Blending_BlendingType() {}

func (*Layer_Blending_Matte_) isLayer_Blending_BlendingType() {}

type Layer_Blending_Standard struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Mode          Layer_Blending_Standard_BlendMode `protobuf:"varint,1,opt,name=mode,proto3,enum=rv.data.Layer_Blending_Standard_BlendMode" json:"mode,omitempty"`
	Opacity       float64                           `protobuf:"fixed64,2,opt,name=opacity,proto3" json:"opacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer_Blending_Standard) Reset() {
	*x = Layer_Blending_Standard{}
	mi := &file_layers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer_Blending_Standard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer_Blending_Standard) ProtoMessage() {}

func (x *Layer_Blending_Standard) ProtoReflect() protoreflect.Message {
	mi := &file_layers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer_Blending_Standard.ProtoReflect.Descriptor instead.
func (*Layer_Blending_Standard) Descriptor() ([]byte, []int) {
	return file_layers_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Layer_Blending_Standard) GetMode() Layer_Blending_Standard_BlendMode {
	if x != nil {
		return x.Mode
	}
	return Layer_Blending_Standard_BLEND_MODE_NORMAL
}

func (x *Layer_Blending_Standard) GetOpacity() float64 {
	if x != nil {
		return x.Opacity
	}
	return 0
}

type Layer_Blending_Matte struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MatteType:
	//
	//	*Layer_Blending_Matte_Alpha_
	//	*Layer_Blending_Matte_Luma_
	//	*Layer_Blending_Matte_White_
	MatteType     isLayer_Blending_Matte_MatteType `protobuf_oneof:"MatteType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer_Blending_Matte) Reset() {
	*x = Layer_Blending_Matte{}
	mi := &file_layers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer_Blending_Matte) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer_Blending_Matte) ProtoMessage() {}

func (x *Layer_Blending_Matte) ProtoReflect() protoreflect.Message {
	mi := &file_layers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer_Blending_Matte.ProtoReflect.Descriptor instead.
func (*Layer_Blending_Matte) Descriptor() ([]byte, []int) {
	return file_layers_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Layer_Blending_Matte) GetMatteType() isLayer_Blending_Matte_MatteType {
	if x != nil {
		return x.MatteType
	}
	return nil
}

func (x *Layer_Blending_Matte) GetAlpha() *Layer_Blending_Matte_Alpha {
	if x != nil {
		if x, ok := x.MatteType.(*Layer_Blending_Matte_Alpha_); ok {
			return x.Alpha
		}
	}
	return nil
}

func (x *Layer_Blending_Matte) GetLuma() *Layer_Blending_Matte_Luma {
	if x != nil {
		if x, ok := x.MatteType.(*Layer_Blending_Matte_Luma_); ok {
			return x.Luma
		}
	}
	return nil
}

func (x *Layer_Blending_Matte) GetWhite() *Layer_Blending_Matte_White {
	if x != nil {
		if x, ok := x.MatteType.(*Layer_Blending_Matte_White_); ok {
			return x.White
		}
	}
	return nil
}

type isLayer_Blending_Matte_MatteType interface {
	isLayer_Blending_Matte_MatteType()
}

type Layer_Blending_Matte_Alpha_ struct {
	Alpha *Layer_Blending_Matte_Alpha `protobuf:"bytes,1,opt,name=alpha,proto3,oneof"`
}

type Layer_Blending_Matte_Luma_ struct {
	Luma *Layer_Blending_Matte_Luma `protobuf:"bytes,2,opt,name=luma,proto3,oneof"`
}

type Layer_Blending_Matte_White_ struct {
	White *Layer_Blending_Matte_White `protobuf:"bytes,4,opt,name=white,proto3,oneof"`
}

func (*Layer_Blending_Matte_Alpha_) isLayer_Blending_Matte_MatteType() {}

func (*Layer_Blending_Matte_Luma_) isLayer_Blending_Matte_MatteType() {}

func (*Layer_Blending_Matte_White_) isLayer_Blending_Matte_MatteType() {}

type Layer_Blending_Matte_Alpha struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inverted      bool                   `protobuf:"varint,1,opt,name=inverted,proto3" json:"inverted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer_Blending_Matte_Alpha) Reset() {
	*x = Layer_Blending_Matte_Alpha{}
	mi := &file_layers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer_Blending_Matte_Alpha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer_Blending_Matte_Alpha) ProtoMessage() {}

func (x *Layer_Blending_Matte_Alpha) ProtoReflect() protoreflect.Message {
	mi := &file_layers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer_Blending_Matte_Alpha.ProtoReflect.Descriptor instead.
func (*Layer_Blending_Matte_Alpha) Descriptor() ([]byte, []int) {
	return file_layers_proto_rawDescGZIP(), []int{0, 1, 1, 0}
}

func (x *Layer_Blending_Matte_Alpha) GetInverted() bool {
	if x != nil {
		return x.Inverted
	}
	return false
}

type Layer_Blending_Matte_Luma struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inverted      bool                   `protobuf:"varint,1,opt,name=inverted,proto3" json:"inverted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer_Blending_Matte_Luma) Reset() {
	*x = Layer_Blending_Matte_Luma{}
	mi := &file_layers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer_Blending_Matte_Luma) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer_Blending_Matte_Luma) ProtoMessage() {}

func (x *Layer_Blending_Matte_Luma) ProtoReflect() protoreflect.Message {
	mi := &file_layers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer_Blending_Matte_Luma.ProtoReflect.Descriptor instead.
func (*Layer_Blending_Matte_Luma) Descriptor() ([]byte, []int) {
	return file_layers_proto_rawDescGZIP(), []int{0, 1, 1, 1}
}

func (x *Layer_Blending_Matte_Luma) GetInverted() bool {
	if x != nil {
		return x.Inverted
	}
	return false
}

type Layer_Blending_Matte_White struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer_Blending_Matte_White) Reset() {
	*x = Layer_Blending_Matte_White{}
	mi := &file_layers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer_Blending_Matte_White) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer_Blending_Matte_White) ProtoMessage() {}

func (x *Layer_Blending_Matte_White) ProtoReflect() protoreflect.Message {
	mi := &file_layers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer_Blending_Matte_White.ProtoReflect.Descriptor instead.
func (*Layer_Blending_Matte_White) Descriptor() ([]byte, []int) {
	return file_layers_proto_rawDescGZIP(), []int{0, 1, 1, 2}
}

var File_layers_proto protoreflect.FileDescriptor

const file_layers_proto_rawDesc = "" +
	"\n" +
	"\flayers.proto\x12\arv.data\x1a\fhotKey.proto\x1a\reffects.proto\x1a\x10basicTypes.proto\"\xa3\x15\n" +
	"\x05Layer\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x05color\x18\x03 \x01(\v2\x0e.rv.data.ColorR\x05color\x12\x14\n" +
	"\x05muted\x18\x04 \x01(\bR\x05muted\x12\x16\n" +
	"\x06hidden\x18\x05 \x01(\bR\x06hidden\x127\n" +
	"\n" +
	"blend_mode\x18\x06 \x01(\x0e2\x18.rv.data.Layer.BlendModeR\tblendMode\x12\x18\n" +
	"\aopacity\x18\a \x01(\x01R\aopacity\x12F\n" +
	"\x18selected_target_set_uuid\x18\b \x01(\v2\r.rv.data.UUIDR\x15selectedTargetSetUuid\x12=\n" +
	"\x13effects_preset_uuid\x18\t \x01(\v2\r.rv.data.UUIDR\x11effectsPresetUuid\x124\n" +
	"\x16effects_build_duration\x18\n" +
	" \x01(\x01R\x14effectsBuildDuration\x129\n" +
	"\x11layer_preset_uuid\x18\v \x01(\v2\r.rv.data.UUIDR\x0flayerPresetUuid\x12(\n" +
	"\ahot_key\x18\f \x01(\v2\x0f.rv.data.HotKeyR\x06hotKey\x123\n" +
	"\n" +
	"transition\x18\r \x01(\v2\x13.rv.data.TransitionR\n" +
	"transition\x12)\n" +
	"\aeffects\x18\x0e \x03(\v2\x0f.rv.data.EffectR\aeffects\x12-\n" +
	"\x05blend\x18\x0f \x01(\v2\x17.rv.data.Layer.BlendingR\x05blend\x1ae\n" +
	"\x06Preset\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x05layer\x18\x03 \x01(\v2\x0e.rv.data.LayerR\x05layer\x1a\xdc\t\n" +
	"\bBlending\x12>\n" +
	"\bstandard\x18\x01 \x01(\v2 .rv.data.Layer.Blending.StandardH\x00R\bstandard\x125\n" +
	"\x05matte\x18\x02 \x01(\v2\x1d.rv.data.Layer.Blending.MatteH\x00R\x05matte\x1a\xab\x06\n" +
	"\bStandard\x12>\n" +
	"\x04mode\x18\x01 \x01(\x0e2*.rv.data.Layer.Blending.Standard.BlendModeR\x04mode\x12\x18\n" +
	"\aopacity\x18\x02 \x01(\x01R\aopacity\"\xc4\x05\n" +
	"\tBlendMode\x12\x15\n" +
	"\x11BLEND_MODE_NORMAL\x10\x00\x12\x17\n" +
	"\x13BLEND_MODE_DISSOLVE\x10\x01\x12\x15\n" +
	"\x11BLEND_MODE_DARKEN\x10\x02\x12\x17\n" +
	"\x13BLEND_MODE_MULTIPLY\x10\x03\x12\x19\n" +
	"\x15BLEND_MODE_COLOR_BURN\x10\x04\x12\x1a\n" +
	"\x16BLEND_MODE_LINEAR_BURN\x10\x05\x12\x1b\n" +
	"\x17BLEND_MODE_DARKER_COLOR\x10\x06\x12\x16\n" +
	"\x12BLEND_MODE_LIGHTEN\x10\a\x12\x15\n" +
	"\x11BLEND_MODE_SCREEN\x10\b\x12\x1a\n" +
	"\x16BLEND_MODE_COLOR_DODGE\x10\t\x12\x1b\n" +
	"\x17BLEND_MODE_LINEAR_DODGE\x10\n" +
	"\x12\x1c\n" +
	"\x18BLEND_MODE_LIGHTER_COLOR\x10\v\x12\x16\n" +
	"\x12BLEND_MODE_OVERLAY\x10\f\x12\x19\n" +
	"\x15BLEND_MODE_SOFT_LIGHT\x10\r\x12\x19\n" +
	"\x15BLEND_MODE_HARD_LIGHT\x10\x0e\x12\x1a\n" +
	"\x16BLEND_MODE_VIVID_LIGHT\x10\x0f\x12\x1b\n" +
	"\x17BLEND_MODE_LINEAR_LIGHT\x10\x10\x12\x18\n" +
	"\x14BLEND_MODE_PIN_LIGHT\x10\x11\x12\x17\n" +
	"\x13BLEND_MODE_HARD_MIX\x10\x12\x12\x19\n" +
	"\x15BLEND_MODE_DIFFERENCE\x10\x13\x12\x18\n" +
	"\x14BLEND_MODE_EXCLUSION\x10\x14\x12\x17\n" +
	"\x13BLEND_MODE_SUBTRACT\x10\x15\x12\x15\n" +
	"\x11BLEND_MODE_DIVIDE\x10\x16\x12\x12\n" +
	"\x0eBLEND_MODE_HUE\x10\x17\x12\x19\n" +
	"\x15BLEND_MODE_SATURATION\x10\x18\x12\x14\n" +
	"\x10BLEND_MODE_COLOR\x10\x19\x12\x19\n" +
	"\x15BLEND_MODE_LUMINOSITY\x10\x1a\x1a\x9a\x02\n" +
	"\x05Matte\x12;\n" +
	"\x05alpha\x18\x01 \x01(\v2#.rv.data.Layer.Blending.Matte.AlphaH\x00R\x05alpha\x128\n" +
	"\x04luma\x18\x02 \x01(\v2\".rv.data.Layer.Blending.Matte.LumaH\x00R\x04luma\x12;\n" +
	"\x05white\x18\x04 \x01(\v2#.rv.data.Layer.Blending.Matte.WhiteH\x00R\x05white\x1a#\n" +
	"\x05Alpha\x12\x1a\n" +
	"\binverted\x18\x01 \x01(\bR\binverted\x1a\"\n" +
	"\x04Luma\x12\x1a\n" +
	"\binverted\x18\x01 \x01(\bR\binverted\x1a\a\n" +
	"\x05WhiteB\v\n" +
	"\tMatteTypeB\x0e\n" +
	"\fBlendingType\"\xc4\x05\n" +
	"\tBlendMode\x12\x15\n" +
	"\x11BLEND_MODE_NORMAL\x10\x00\x12\x17\n" +
	"\x13BLEND_MODE_DISSOLVE\x10\x01\x12\x15\n" +
	"\x11BLEND_MODE_DARKEN\x10\x02\x12\x17\n" +
	"\x13BLEND_MODE_MULTIPLY\x10\x03\x12\x19\n" +
	"\x15BLEND_MODE_COLOR_BURN\x10\x04\x12\x1a\n" +
	"\x16BLEND_MODE_LINEAR_BURN\x10\x05\x12\x1b\n" +
	"\x17BLEND_MODE_DARKER_COLOR\x10\x06\x12\x16\n" +
	"\x12BLEND_MODE_LIGHTEN\x10\a\x12\x15\n" +
	"\x11BLEND_MODE_SCREEN\x10\b\x12\x1a\n" +
	"\x16BLEND_MODE_COLOR_DODGE\x10\t\x12\x1b\n" +
	"\x17BLEND_MODE_LINEAR_DODGE\x10\n" +
	"\x12\x1c\n" +
	"\x18BLEND_MODE_LIGHTER_COLOR\x10\v\x12\x16\n" +
	"\x12BLEND_MODE_OVERLAY\x10\f\x12\x19\n" +
	"\x15BLEND_MODE_SOFT_LIGHT\x10\r\x12\x19\n" +
	"\x15BLEND_MODE_HARD_LIGHT\x10\x0e\x12\x1a\n" +
	"\x16BLEND_MODE_VIVID_LIGHT\x10\x0f\x12\x1b\n" +
	"\x17BLEND_MODE_LINEAR_LIGHT\x10\x10\x12\x18\n" +
	"\x14BLEND_MODE_PIN_LIGHT\x10\x11\x12\x17\n" +
	"\x13BLEND_MODE_HARD_MIX\x10\x12\x12\x19\n" +
	"\x15BLEND_MODE_DIFFERENCE\x10\x13\x12\x18\n" +
	"\x14BLEND_MODE_EXCLUSION\x10\x14\x12\x17\n" +
	"\x13BLEND_MODE_SUBTRACT\x10\x15\x12\x15\n" +
	"\x11BLEND_MODE_DIVIDE\x10\x16\x12\x12\n" +
	"\x0eBLEND_MODE_HUE\x10\x17\x12\x19\n" +
	"\x15BLEND_MODE_SATURATION\x10\x18\x12\x14\n" +
	"\x10BLEND_MODE_COLOR\x10\x19\x12\x19\n" +
	"\x15BLEND_MODE_LUMINOSITY\x10\x1aB\x92\x01\n" +
	"\vcom.rv.dataB\vLayersProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_layers_proto_rawDescOnce sync.Once
	file_layers_proto_rawDescData []byte
)

func file_layers_proto_rawDescGZIP() []byte {
	file_layers_proto_rawDescOnce.Do(func() {
		file_layers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_layers_proto_rawDesc), len(file_layers_proto_rawDesc)))
	})
	return file_layers_proto_rawDescData
}

var file_layers_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_layers_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_layers_proto_goTypes = []any{
	(Layer_BlendMode)(0),                   // 0: rv.data.Layer.BlendMode
	(Layer_Blending_Standard_BlendMode)(0), // 1: rv.data.Layer.Blending.Standard.BlendMode
	(*Layer)(nil),                          // 2: rv.data.Layer
	(*Layer_Preset)(nil),                   // 3: rv.data.Layer.Preset
	(*Layer_Blending)(nil),                 // 4: rv.data.Layer.Blending
	(*Layer_Blending_Standard)(nil),        // 5: rv.data.Layer.Blending.Standard
	(*Layer_Blending_Matte)(nil),           // 6: rv.data.Layer.Blending.Matte
	(*Layer_Blending_Matte_Alpha)(nil),     // 7: rv.data.Layer.Blending.Matte.Alpha
	(*Layer_Blending_Matte_Luma)(nil),      // 8: rv.data.Layer.Blending.Matte.Luma
	(*Layer_Blending_Matte_White)(nil),     // 9: rv.data.Layer.Blending.Matte.White
	(*UUID)(nil),                           // 10: rv.data.UUID
	(*Color)(nil),                          // 11: rv.data.Color
	(*HotKey)(nil),                         // 12: rv.data.HotKey
	(*Transition)(nil),                     // 13: rv.data.Transition
	(*Effect)(nil),                         // 14: rv.data.Effect
}
var file_layers_proto_depIdxs = []int32{
	10, // 0: rv.data.Layer.uuid:type_name -> rv.data.UUID
	11, // 1: rv.data.Layer.color:type_name -> rv.data.Color
	0,  // 2: rv.data.Layer.blend_mode:type_name -> rv.data.Layer.BlendMode
	10, // 3: rv.data.Layer.selected_target_set_uuid:type_name -> rv.data.UUID
	10, // 4: rv.data.Layer.effects_preset_uuid:type_name -> rv.data.UUID
	10, // 5: rv.data.Layer.layer_preset_uuid:type_name -> rv.data.UUID
	12, // 6: rv.data.Layer.hot_key:type_name -> rv.data.HotKey
	13, // 7: rv.data.Layer.transition:type_name -> rv.data.Transition
	14, // 8: rv.data.Layer.effects:type_name -> rv.data.Effect
	4,  // 9: rv.data.Layer.blend:type_name -> rv.data.Layer.Blending
	10, // 10: rv.data.Layer.Preset.uuid:type_name -> rv.data.UUID
	2,  // 11: rv.data.Layer.Preset.layer:type_name -> rv.data.Layer
	5,  // 12: rv.data.Layer.Blending.standard:type_name -> rv.data.Layer.Blending.Standard
	6,  // 13: rv.data.Layer.Blending.matte:type_name -> rv.data.Layer.Blending.Matte
	1,  // 14: rv.data.Layer.Blending.Standard.mode:type_name -> rv.data.Layer.Blending.Standard.BlendMode
	7,  // 15: rv.data.Layer.Blending.Matte.alpha:type_name -> rv.data.Layer.Blending.Matte.Alpha
	8,  // 16: rv.data.Layer.Blending.Matte.luma:type_name -> rv.data.Layer.Blending.Matte.Luma
	9,  // 17: rv.data.Layer.Blending.Matte.white:type_name -> rv.data.Layer.Blending.Matte.White
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_layers_proto_init() }
func file_layers_proto_init() {
	if File_layers_proto != nil {
		return
	}
	file_hotKey_proto_init()
	file_effects_proto_init()
	file_basicTypes_proto_init()
	file_layers_proto_msgTypes[2].OneofWrappers = []any{
		(*Layer_Blending_Standard_)(nil),
		(*Layer_Blending_Matte_)(nil),
	}
	file_layers_proto_msgTypes[4].OneofWrappers = []any{
		(*Layer_Blending_Matte_Alpha_)(nil),
		(*Layer_Blending_Matte_Luma_)(nil),
		(*Layer_Blending_Matte_White_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_layers_proto_rawDesc), len(file_layers_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_layers_proto_goTypes,
		DependencyIndexes: file_layers_proto_depIdxs,
		EnumInfos:         file_layers_proto_enumTypes,
		MessageInfos:      file_layers_proto_msgTypes,
	}.Build()
	File_layers_proto = out.File
	file_layers_proto_goTypes = nil
	file_layers_proto_depIdxs = nil
}
