// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: library.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Library struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Url   *URL                   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Types that are valid to be assigned to ChildType:
	//
	//	*Library_LibraryChildren
	//	*Library_LibraryItems_
	ChildType     isLibrary_ChildType `protobuf_oneof:"ChildType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Library) Reset() {
	*x = Library{}
	mi := &file_library_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Library) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Library) ProtoMessage() {}

func (x *Library) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Library.ProtoReflect.Descriptor instead.
func (*Library) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{0}
}

func (x *Library) GetUrl() *URL {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *Library) GetChildType() isLibrary_ChildType {
	if x != nil {
		return x.ChildType
	}
	return nil
}

func (x *Library) GetLibraryChildren() *Library_LibraryArray {
	if x != nil {
		if x, ok := x.ChildType.(*Library_LibraryChildren); ok {
			return x.LibraryChildren
		}
	}
	return nil
}

func (x *Library) GetLibraryItems() *Library_LibraryItems {
	if x != nil {
		if x, ok := x.ChildType.(*Library_LibraryItems_); ok {
			return x.LibraryItems
		}
	}
	return nil
}

type isLibrary_ChildType interface {
	isLibrary_ChildType()
}

type Library_LibraryChildren struct {
	LibraryChildren *Library_LibraryArray `protobuf:"bytes,2,opt,name=libraryChildren,proto3,oneof"`
}

type Library_LibraryItems_ struct {
	LibraryItems *Library_LibraryItems `protobuf:"bytes,3,opt,name=libraryItems,proto3,oneof"`
}

func (*Library_LibraryChildren) isLibrary_ChildType() {}

func (*Library_LibraryItems_) isLibrary_ChildType() {}

type LibraryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *URL                   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryItem) Reset() {
	*x = LibraryItem{}
	mi := &file_library_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryItem) ProtoMessage() {}

func (x *LibraryItem) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryItem.ProtoReflect.Descriptor instead.
func (*LibraryItem) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{1}
}

func (x *LibraryItem) GetUrl() *URL {
	if x != nil {
		return x.Url
	}
	return nil
}

type Library_LibraryArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Libraries     []*Library             `protobuf:"bytes,1,rep,name=libraries,proto3" json:"libraries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Library_LibraryArray) Reset() {
	*x = Library_LibraryArray{}
	mi := &file_library_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Library_LibraryArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Library_LibraryArray) ProtoMessage() {}

func (x *Library_LibraryArray) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Library_LibraryArray.ProtoReflect.Descriptor instead.
func (*Library_LibraryArray) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Library_LibraryArray) GetLibraries() []*Library {
	if x != nil {
		return x.Libraries
	}
	return nil
}

type Library_LibraryItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LibraryItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Library_LibraryItems) Reset() {
	*x = Library_LibraryItems{}
	mi := &file_library_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Library_LibraryItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Library_LibraryItems) ProtoMessage() {}

func (x *Library_LibraryItems) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Library_LibraryItems.ProtoReflect.Descriptor instead.
func (*Library_LibraryItems) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Library_LibraryItems) GetItems() []*LibraryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_library_proto protoreflect.FileDescriptor

const file_library_proto_rawDesc = "" +
	"\n" +
	"\rlibrary.proto\x12\arv.data\x1a\x10basicTypes.proto\"\xc2\x02\n" +
	"\aLibrary\x12\x1e\n" +
	"\x03url\x18\x01 \x01(\v2\f.rv.data.URLR\x03url\x12I\n" +
	"\x0flibraryChildren\x18\x02 \x01(\v2\x1d.rv.data.Library.LibraryArrayH\x00R\x0flibraryChildren\x12C\n" +
	"\flibraryItems\x18\x03 \x01(\v2\x1d.rv.data.Library.LibraryItemsH\x00R\flibraryItems\x1a>\n" +
	"\fLibraryArray\x12.\n" +
	"\tlibraries\x18\x01 \x03(\v2\x10.rv.data.LibraryR\tlibraries\x1a:\n" +
	"\fLibraryItems\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.rv.data.LibraryItemR\x05itemsB\v\n" +
	"\tChildType\"-\n" +
	"\vLibraryItem\x12\x1e\n" +
	"\x03url\x18\x01 \x01(\v2\f.rv.data.URLR\x03urlB\x92\x01\n" +
	"\vcom.rv.dataB\fLibraryProtoP\x01Z8github.com/thatguycleeb/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_library_proto_rawDescOnce sync.Once
	file_library_proto_rawDescData []byte
)

func file_library_proto_rawDescGZIP() []byte {
	file_library_proto_rawDescOnce.Do(func() {
		file_library_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_library_proto_rawDesc), len(file_library_proto_rawDesc)))
	})
	return file_library_proto_rawDescData
}

var file_library_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_library_proto_goTypes = []any{
	(*Library)(nil),              // 0: rv.data.Library
	(*LibraryItem)(nil),          // 1: rv.data.LibraryItem
	(*Library_LibraryArray)(nil), // 2: rv.data.Library.LibraryArray
	(*Library_LibraryItems)(nil), // 3: rv.data.Library.LibraryItems
	(*URL)(nil),                  // 4: rv.data.URL
}
var file_library_proto_depIdxs = []int32{
	4, // 0: rv.data.Library.url:type_name -> rv.data.URL
	2, // 1: rv.data.Library.libraryChildren:type_name -> rv.data.Library.LibraryArray
	3, // 2: rv.data.Library.libraryItems:type_name -> rv.data.Library.LibraryItems
	4, // 3: rv.data.LibraryItem.url:type_name -> rv.data.URL
	0, // 4: rv.data.Library.LibraryArray.libraries:type_name -> rv.data.Library
	1, // 5: rv.data.Library.LibraryItems.items:type_name -> rv.data.LibraryItem
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_library_proto_init() }
func file_library_proto_init() {
	if File_library_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_library_proto_msgTypes[0].OneofWrappers = []any{
		(*Library_LibraryChildren)(nil),
		(*Library_LibraryItems_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_library_proto_rawDesc), len(file_library_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_library_proto_goTypes,
		DependencyIndexes: file_library_proto_depIdxs,
		MessageInfos:      file_library_proto_msgTypes,
	}.Build()
	File_library_proto = out.File
	file_library_proto_goTypes = nil
	file_library_proto_depIdxs = nil
}
