// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: playlistTemplate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaylistTemplate struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Templates     []*PlaylistTemplate_Template `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistTemplate) Reset() {
	*x = PlaylistTemplate{}
	mi := &file_playlistTemplate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistTemplate) ProtoMessage() {}

func (x *PlaylistTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_playlistTemplate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistTemplate.ProtoReflect.Descriptor instead.
func (*PlaylistTemplate) Descriptor() ([]byte, []int) {
	return file_playlistTemplate_proto_rawDescGZIP(), []int{0}
}

func (x *PlaylistTemplate) GetTemplates() []*PlaylistTemplate_Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

type PlaylistTemplate_Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PlaylistItems []*PlaylistItem        `protobuf:"bytes,2,rep,name=playlist_items,json=playlistItems,proto3" json:"playlist_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistTemplate_Template) Reset() {
	*x = PlaylistTemplate_Template{}
	mi := &file_playlistTemplate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistTemplate_Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistTemplate_Template) ProtoMessage() {}

func (x *PlaylistTemplate_Template) ProtoReflect() protoreflect.Message {
	mi := &file_playlistTemplate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistTemplate_Template.ProtoReflect.Descriptor instead.
func (*PlaylistTemplate_Template) Descriptor() ([]byte, []int) {
	return file_playlistTemplate_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PlaylistTemplate_Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlaylistTemplate_Template) GetPlaylistItems() []*PlaylistItem {
	if x != nil {
		return x.PlaylistItems
	}
	return nil
}

var File_playlistTemplate_proto protoreflect.FileDescriptor

const file_playlistTemplate_proto_rawDesc = "" +
	"\n" +
	"\x16playlistTemplate.proto\x12\arv.data\x1a\x0eplaylist.proto\"\xb2\x01\n" +
	"\x10PlaylistTemplate\x12@\n" +
	"\ttemplates\x18\x01 \x03(\v2\".rv.data.PlaylistTemplate.TemplateR\ttemplates\x1a\\\n" +
	"\bTemplate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x0eplaylist_items\x18\x02 \x03(\v2\x15.rv.data.PlaylistItemR\rplaylistItemsB\x9c\x01\n" +
	"\vcom.rv.dataB\x15PlaylistTemplateProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_playlistTemplate_proto_rawDescOnce sync.Once
	file_playlistTemplate_proto_rawDescData []byte
)

func file_playlistTemplate_proto_rawDescGZIP() []byte {
	file_playlistTemplate_proto_rawDescOnce.Do(func() {
		file_playlistTemplate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_playlistTemplate_proto_rawDesc), len(file_playlistTemplate_proto_rawDesc)))
	})
	return file_playlistTemplate_proto_rawDescData
}

var file_playlistTemplate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_playlistTemplate_proto_goTypes = []any{
	(*PlaylistTemplate)(nil),          // 0: rv.data.PlaylistTemplate
	(*PlaylistTemplate_Template)(nil), // 1: rv.data.PlaylistTemplate.Template
	(*PlaylistItem)(nil),              // 2: rv.data.PlaylistItem
}
var file_playlistTemplate_proto_depIdxs = []int32{
	1, // 0: rv.data.PlaylistTemplate.templates:type_name -> rv.data.PlaylistTemplate.Template
	2, // 1: rv.data.PlaylistTemplate.Template.playlist_items:type_name -> rv.data.PlaylistItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_playlistTemplate_proto_init() }
func file_playlistTemplate_proto_init() {
	if File_playlistTemplate_proto != nil {
		return
	}
	file_playlist_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_playlistTemplate_proto_rawDesc), len(file_playlistTemplate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playlistTemplate_proto_goTypes,
		DependencyIndexes: file_playlistTemplate_proto_depIdxs,
		MessageInfos:      file_playlistTemplate_proto_msgTypes,
	}.Build()
	File_playlistTemplate_proto = out.File
	file_playlistTemplate_proto_goTypes = nil
	file_playlistTemplate_proto_depIdxs = nil
}
