// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: presentationSlide.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresentationSlide struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	BaseSlide          *Slide                   `protobuf:"bytes,1,opt,name=base_slide,json=baseSlide,proto3" json:"base_slide,omitempty"`
	Notes              *PresentationSlide_Notes `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	TemplateGuidelines []*AlignmentGuide        `protobuf:"bytes,3,rep,name=template_guidelines,json=templateGuidelines,proto3" json:"template_guidelines,omitempty"`
	ChordChart         *URL                     `protobuf:"bytes,4,opt,name=chord_chart,json=chordChart,proto3" json:"chord_chart,omitempty"`
	Transition         *Transition              `protobuf:"bytes,5,opt,name=transition,proto3" json:"transition,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PresentationSlide) Reset() {
	*x = PresentationSlide{}
	mi := &file_presentationSlide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentationSlide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentationSlide) ProtoMessage() {}

func (x *PresentationSlide) ProtoReflect() protoreflect.Message {
	mi := &file_presentationSlide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentationSlide.ProtoReflect.Descriptor instead.
func (*PresentationSlide) Descriptor() ([]byte, []int) {
	return file_presentationSlide_proto_rawDescGZIP(), []int{0}
}

func (x *PresentationSlide) GetBaseSlide() *Slide {
	if x != nil {
		return x.BaseSlide
	}
	return nil
}

func (x *PresentationSlide) GetNotes() *PresentationSlide_Notes {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *PresentationSlide) GetTemplateGuidelines() []*AlignmentGuide {
	if x != nil {
		return x.TemplateGuidelines
	}
	return nil
}

func (x *PresentationSlide) GetChordChart() *URL {
	if x != nil {
		return x.ChordChart
	}
	return nil
}

func (x *PresentationSlide) GetTransition() *Transition {
	if x != nil {
		return x.Transition
	}
	return nil
}

type PresentationSlide_Notes struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	RtfData       []byte                    `protobuf:"bytes,1,opt,name=rtf_data,json=rtfData,proto3" json:"rtf_data,omitempty"`
	Attributes    *Graphics_Text_Attributes `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresentationSlide_Notes) Reset() {
	*x = PresentationSlide_Notes{}
	mi := &file_presentationSlide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentationSlide_Notes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentationSlide_Notes) ProtoMessage() {}

func (x *PresentationSlide_Notes) ProtoReflect() protoreflect.Message {
	mi := &file_presentationSlide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentationSlide_Notes.ProtoReflect.Descriptor instead.
func (*PresentationSlide_Notes) Descriptor() ([]byte, []int) {
	return file_presentationSlide_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PresentationSlide_Notes) GetRtfData() []byte {
	if x != nil {
		return x.RtfData
	}
	return nil
}

func (x *PresentationSlide_Notes) GetAttributes() *Graphics_Text_Attributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_presentationSlide_proto protoreflect.FileDescriptor

const file_presentationSlide_proto_rawDesc = "" +
	"\n" +
	"\x17presentationSlide.proto\x12\arv.data\x1a\vslide.proto\x1a\x10basicTypes.proto\x1a\x14alignmentGuide.proto\x1a\reffects.proto\x1a\x12graphicsData.proto\"\x8f\x03\n" +
	"\x11PresentationSlide\x12-\n" +
	"\n" +
	"base_slide\x18\x01 \x01(\v2\x0e.rv.data.SlideR\tbaseSlide\x126\n" +
	"\x05notes\x18\x02 \x01(\v2 .rv.data.PresentationSlide.NotesR\x05notes\x12H\n" +
	"\x13template_guidelines\x18\x03 \x03(\v2\x17.rv.data.AlignmentGuideR\x12templateGuidelines\x12-\n" +
	"\vchord_chart\x18\x04 \x01(\v2\f.rv.data.URLR\n" +
	"chordChart\x123\n" +
	"\n" +
	"transition\x18\x05 \x01(\v2\x13.rv.data.TransitionR\n" +
	"transition\x1ae\n" +
	"\x05Notes\x12\x19\n" +
	"\brtf_data\x18\x01 \x01(\fR\artfData\x12A\n" +
	"\n" +
	"attributes\x18\x02 \x01(\v2!.rv.data.Graphics.Text.AttributesR\n" +
	"attributesB\x9d\x01\n" +
	"\vcom.rv.dataB\x16PresentationSlideProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_presentationSlide_proto_rawDescOnce sync.Once
	file_presentationSlide_proto_rawDescData []byte
)

func file_presentationSlide_proto_rawDescGZIP() []byte {
	file_presentationSlide_proto_rawDescOnce.Do(func() {
		file_presentationSlide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_presentationSlide_proto_rawDesc), len(file_presentationSlide_proto_rawDesc)))
	})
	return file_presentationSlide_proto_rawDescData
}

var file_presentationSlide_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_presentationSlide_proto_goTypes = []any{
	(*PresentationSlide)(nil),        // 0: rv.data.PresentationSlide
	(*PresentationSlide_Notes)(nil),  // 1: rv.data.PresentationSlide.Notes
	(*Slide)(nil),                    // 2: rv.data.Slide
	(*AlignmentGuide)(nil),           // 3: rv.data.AlignmentGuide
	(*URL)(nil),                      // 4: rv.data.URL
	(*Transition)(nil),               // 5: rv.data.Transition
	(*Graphics_Text_Attributes)(nil), // 6: rv.data.Graphics.Text.Attributes
}
var file_presentationSlide_proto_depIdxs = []int32{
	2, // 0: rv.data.PresentationSlide.base_slide:type_name -> rv.data.Slide
	1, // 1: rv.data.PresentationSlide.notes:type_name -> rv.data.PresentationSlide.Notes
	3, // 2: rv.data.PresentationSlide.template_guidelines:type_name -> rv.data.AlignmentGuide
	4, // 3: rv.data.PresentationSlide.chord_chart:type_name -> rv.data.URL
	5, // 4: rv.data.PresentationSlide.transition:type_name -> rv.data.Transition
	6, // 5: rv.data.PresentationSlide.Notes.attributes:type_name -> rv.data.Graphics.Text.Attributes
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_presentationSlide_proto_init() }
func file_presentationSlide_proto_init() {
	if File_presentationSlide_proto != nil {
		return
	}
	file_slide_proto_init()
	file_basicTypes_proto_init()
	file_alignmentGuide_proto_init()
	file_effects_proto_init()
	file_graphicsData_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_presentationSlide_proto_rawDesc), len(file_presentationSlide_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_presentationSlide_proto_goTypes,
		DependencyIndexes: file_presentationSlide_proto_depIdxs,
		MessageInfos:      file_presentationSlide_proto_msgTypes,
	}.Build()
	File_presentationSlide_proto = out.File
	file_presentationSlide_proto_goTypes = nil
	file_presentationSlide_proto_depIdxs = nil
}
