// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: proAudienceLook.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProAudienceLook struct {
	state            protoimpl.MessageState           `protogen:"open.v1"`
	Uuid             *UUID                            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name             string                           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ScreenLooks      []*ProAudienceLook_ProScreenLook `protobuf:"bytes,3,rep,name=screen_looks,json=screenLooks,proto3" json:"screen_looks,omitempty"`
	OriginalLookUuid *UUID                            `protobuf:"bytes,4,opt,name=original_look_uuid,json=originalLookUuid,proto3" json:"original_look_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProAudienceLook) Reset() {
	*x = ProAudienceLook{}
	mi := &file_proAudienceLook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProAudienceLook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProAudienceLook) ProtoMessage() {}

func (x *ProAudienceLook) ProtoReflect() protoreflect.Message {
	mi := &file_proAudienceLook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProAudienceLook.ProtoReflect.Descriptor instead.
func (*ProAudienceLook) Descriptor() ([]byte, []int) {
	return file_proAudienceLook_proto_rawDescGZIP(), []int{0}
}

func (x *ProAudienceLook) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *ProAudienceLook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProAudienceLook) GetScreenLooks() []*ProAudienceLook_ProScreenLook {
	if x != nil {
		return x.ScreenLooks
	}
	return nil
}

func (x *ProAudienceLook) GetOriginalLookUuid() *UUID {
	if x != nil {
		return x.OriginalLookUuid
	}
	return nil
}

type ProAudienceLook_ProScreenLook struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	ProScreenUuid                 *UUID                  `protobuf:"bytes,1,opt,name=pro_screen_uuid,json=proScreenUuid,proto3" json:"pro_screen_uuid,omitempty"`
	PropsEnabled                  bool                   `protobuf:"varint,2,opt,name=props_enabled,json=propsEnabled,proto3" json:"props_enabled,omitempty"`
	LiveVideoEnabled              bool                   `protobuf:"varint,3,opt,name=live_video_enabled,json=liveVideoEnabled,proto3" json:"live_video_enabled,omitempty"`
	PresentationBackgroundEnabled bool                   `protobuf:"varint,4,opt,name=presentation_background_enabled,json=presentationBackgroundEnabled,proto3" json:"presentation_background_enabled,omitempty"`
	TemplateDocumentFilePath      *URL                   `protobuf:"bytes,5,opt,name=template_document_file_path,json=templateDocumentFilePath,proto3" json:"template_document_file_path,omitempty"`
	TemplateSlideUuid             *UUID                  `protobuf:"bytes,6,opt,name=template_slide_uuid,json=templateSlideUuid,proto3" json:"template_slide_uuid,omitempty"`
	PresentationForegroundEnabled bool                   `protobuf:"varint,7,opt,name=presentation_foreground_enabled,json=presentationForegroundEnabled,proto3" json:"presentation_foreground_enabled,omitempty"`
	MaskUuid                      *UUID                  `protobuf:"bytes,8,opt,name=mask_uuid,json=maskUuid,proto3" json:"mask_uuid,omitempty"`
	AnnouncementsEnabled          bool                   `protobuf:"varint,9,opt,name=announcements_enabled,json=announcementsEnabled,proto3" json:"announcements_enabled,omitempty"`
	PropsLayerEnabled             bool                   `protobuf:"varint,10,opt,name=props_layer_enabled,json=propsLayerEnabled,proto3" json:"props_layer_enabled,omitempty"`
	MessagesLayerEnabled          bool                   `protobuf:"varint,11,opt,name=messages_layer_enabled,json=messagesLayerEnabled,proto3" json:"messages_layer_enabled,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ProAudienceLook_ProScreenLook) Reset() {
	*x = ProAudienceLook_ProScreenLook{}
	mi := &file_proAudienceLook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProAudienceLook_ProScreenLook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProAudienceLook_ProScreenLook) ProtoMessage() {}

func (x *ProAudienceLook_ProScreenLook) ProtoReflect() protoreflect.Message {
	mi := &file_proAudienceLook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProAudienceLook_ProScreenLook.ProtoReflect.Descriptor instead.
func (*ProAudienceLook_ProScreenLook) Descriptor() ([]byte, []int) {
	return file_proAudienceLook_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProAudienceLook_ProScreenLook) GetProScreenUuid() *UUID {
	if x != nil {
		return x.ProScreenUuid
	}
	return nil
}

func (x *ProAudienceLook_ProScreenLook) GetPropsEnabled() bool {
	if x != nil {
		return x.PropsEnabled
	}
	return false
}

func (x *ProAudienceLook_ProScreenLook) GetLiveVideoEnabled() bool {
	if x != nil {
		return x.LiveVideoEnabled
	}
	return false
}

func (x *ProAudienceLook_ProScreenLook) GetPresentationBackgroundEnabled() bool {
	if x != nil {
		return x.PresentationBackgroundEnabled
	}
	return false
}

func (x *ProAudienceLook_ProScreenLook) GetTemplateDocumentFilePath() *URL {
	if x != nil {
		return x.TemplateDocumentFilePath
	}
	return nil
}

func (x *ProAudienceLook_ProScreenLook) GetTemplateSlideUuid() *UUID {
	if x != nil {
		return x.TemplateSlideUuid
	}
	return nil
}

func (x *ProAudienceLook_ProScreenLook) GetPresentationForegroundEnabled() bool {
	if x != nil {
		return x.PresentationForegroundEnabled
	}
	return false
}

func (x *ProAudienceLook_ProScreenLook) GetMaskUuid() *UUID {
	if x != nil {
		return x.MaskUuid
	}
	return nil
}

func (x *ProAudienceLook_ProScreenLook) GetAnnouncementsEnabled() bool {
	if x != nil {
		return x.AnnouncementsEnabled
	}
	return false
}

func (x *ProAudienceLook_ProScreenLook) GetPropsLayerEnabled() bool {
	if x != nil {
		return x.PropsLayerEnabled
	}
	return false
}

func (x *ProAudienceLook_ProScreenLook) GetMessagesLayerEnabled() bool {
	if x != nil {
		return x.MessagesLayerEnabled
	}
	return false
}

var File_proAudienceLook_proto protoreflect.FileDescriptor

const file_proAudienceLook_proto_rawDesc = "" +
	"\n" +
	"\x15proAudienceLook.proto\x12\arv.data\x1a\x10basicTypes.proto\"\xcf\x06\n" +
	"\x0fProAudienceLook\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12I\n" +
	"\fscreen_looks\x18\x03 \x03(\v2&.rv.data.ProAudienceLook.ProScreenLookR\vscreenLooks\x12;\n" +
	"\x12original_look_uuid\x18\x04 \x01(\v2\r.rv.data.UUIDR\x10originalLookUuid\x1a\xfc\x04\n" +
	"\rProScreenLook\x125\n" +
	"\x0fpro_screen_uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\rproScreenUuid\x12#\n" +
	"\rprops_enabled\x18\x02 \x01(\bR\fpropsEnabled\x12,\n" +
	"\x12live_video_enabled\x18\x03 \x01(\bR\x10liveVideoEnabled\x12F\n" +
	"\x1fpresentation_background_enabled\x18\x04 \x01(\bR\x1dpresentationBackgroundEnabled\x12K\n" +
	"\x1btemplate_document_file_path\x18\x05 \x01(\v2\f.rv.data.URLR\x18templateDocumentFilePath\x12=\n" +
	"\x13template_slide_uuid\x18\x06 \x01(\v2\r.rv.data.UUIDR\x11templateSlideUuid\x12F\n" +
	"\x1fpresentation_foreground_enabled\x18\a \x01(\bR\x1dpresentationForegroundEnabled\x12*\n" +
	"\tmask_uuid\x18\b \x01(\v2\r.rv.data.UUIDR\bmaskUuid\x123\n" +
	"\x15announcements_enabled\x18\t \x01(\bR\x14announcementsEnabled\x12.\n" +
	"\x13props_layer_enabled\x18\n" +
	" \x01(\bR\x11propsLayerEnabled\x124\n" +
	"\x16messages_layer_enabled\x18\v \x01(\bR\x14messagesLayerEnabledB\x9a\x01\n" +
	"\vcom.rv.dataB\x14ProAudienceLookProtoP\x01Z8github.com/thatguycleeb/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_proAudienceLook_proto_rawDescOnce sync.Once
	file_proAudienceLook_proto_rawDescData []byte
)

func file_proAudienceLook_proto_rawDescGZIP() []byte {
	file_proAudienceLook_proto_rawDescOnce.Do(func() {
		file_proAudienceLook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proAudienceLook_proto_rawDesc), len(file_proAudienceLook_proto_rawDesc)))
	})
	return file_proAudienceLook_proto_rawDescData
}

var file_proAudienceLook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proAudienceLook_proto_goTypes = []any{
	(*ProAudienceLook)(nil),               // 0: rv.data.ProAudienceLook
	(*ProAudienceLook_ProScreenLook)(nil), // 1: rv.data.ProAudienceLook.ProScreenLook
	(*UUID)(nil),                          // 2: rv.data.UUID
	(*URL)(nil),                           // 3: rv.data.URL
}
var file_proAudienceLook_proto_depIdxs = []int32{
	2, // 0: rv.data.ProAudienceLook.uuid:type_name -> rv.data.UUID
	1, // 1: rv.data.ProAudienceLook.screen_looks:type_name -> rv.data.ProAudienceLook.ProScreenLook
	2, // 2: rv.data.ProAudienceLook.original_look_uuid:type_name -> rv.data.UUID
	2, // 3: rv.data.ProAudienceLook.ProScreenLook.pro_screen_uuid:type_name -> rv.data.UUID
	3, // 4: rv.data.ProAudienceLook.ProScreenLook.template_document_file_path:type_name -> rv.data.URL
	2, // 5: rv.data.ProAudienceLook.ProScreenLook.template_slide_uuid:type_name -> rv.data.UUID
	2, // 6: rv.data.ProAudienceLook.ProScreenLook.mask_uuid:type_name -> rv.data.UUID
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proAudienceLook_proto_init() }
func file_proAudienceLook_proto_init() {
	if File_proAudienceLook_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proAudienceLook_proto_rawDesc), len(file_proAudienceLook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proAudienceLook_proto_goTypes,
		DependencyIndexes: file_proAudienceLook_proto_depIdxs,
		MessageInfos:      file_proAudienceLook_proto_msgTypes,
	}.Build()
	File_proAudienceLook_proto = out.File
	file_proAudienceLook_proto_goTypes = nil
	file_proAudienceLook_proto_depIdxs = nil
}
