// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: proMask.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProMask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseSlide     *Slide                 `protobuf:"bytes,1,opt,name=base_slide,json=baseSlide,proto3" json:"base_slide,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProMask) Reset() {
	*x = ProMask{}
	mi := &file_proMask_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProMask) ProtoMessage() {}

func (x *ProMask) ProtoReflect() protoreflect.Message {
	mi := &file_proMask_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProMask.ProtoReflect.Descriptor instead.
func (*ProMask) Descriptor() ([]byte, []int) {
	return file_proMask_proto_rawDescGZIP(), []int{0}
}

func (x *ProMask) GetBaseSlide() *Slide {
	if x != nil {
		return x.BaseSlide
	}
	return nil
}

func (x *ProMask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proMask_proto protoreflect.FileDescriptor

const file_proMask_proto_rawDesc = "" +
	"\n" +
	"\rproMask.proto\x12\arv.data\x1a\vslide.proto\"L\n" +
	"\aProMask\x12-\n" +
	"\n" +
	"base_slide\x18\x01 \x01(\v2\x0e.rv.data.SlideR\tbaseSlide\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB\x93\x01\n" +
	"\vcom.rv.dataB\fProMaskProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_proMask_proto_rawDescOnce sync.Once
	file_proMask_proto_rawDescData []byte
)

func file_proMask_proto_rawDescGZIP() []byte {
	file_proMask_proto_rawDescOnce.Do(func() {
		file_proMask_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proMask_proto_rawDesc), len(file_proMask_proto_rawDesc)))
	})
	return file_proMask_proto_rawDescData
}

var file_proMask_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proMask_proto_goTypes = []any{
	(*ProMask)(nil), // 0: rv.data.ProMask
	(*Slide)(nil),   // 1: rv.data.Slide
}
var file_proMask_proto_depIdxs = []int32{
	1, // 0: rv.data.ProMask.base_slide:type_name -> rv.data.Slide
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proMask_proto_init() }
func file_proMask_proto_init() {
	if File_proMask_proto != nil {
		return
	}
	file_slide_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proMask_proto_rawDesc), len(file_proMask_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proMask_proto_goTypes,
		DependencyIndexes: file_proMask_proto_depIdxs,
		MessageInfos:      file_proMask_proto_msgTypes,
	}.Build()
	File_proMask_proto = out.File
	file_proMask_proto_goTypes = nil
	file_proMask_proto_depIdxs = nil
}
