// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: propSlide.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropSlide struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseSlide     *Slide                 `protobuf:"bytes,1,opt,name=base_slide,json=baseSlide,proto3" json:"base_slide,omitempty"`
	Transition    *Transition            `protobuf:"bytes,2,opt,name=transition,proto3" json:"transition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropSlide) Reset() {
	*x = PropSlide{}
	mi := &file_propSlide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropSlide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropSlide) ProtoMessage() {}

func (x *PropSlide) ProtoReflect() protoreflect.Message {
	mi := &file_propSlide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropSlide.ProtoReflect.Descriptor instead.
func (*PropSlide) Descriptor() ([]byte, []int) {
	return file_propSlide_proto_rawDescGZIP(), []int{0}
}

func (x *PropSlide) GetBaseSlide() *Slide {
	if x != nil {
		return x.BaseSlide
	}
	return nil
}

func (x *PropSlide) GetTransition() *Transition {
	if x != nil {
		return x.Transition
	}
	return nil
}

var File_propSlide_proto protoreflect.FileDescriptor

const file_propSlide_proto_rawDesc = "" +
	"\n" +
	"\x0fpropSlide.proto\x12\arv.data\x1a\vslide.proto\x1a\reffects.proto\"o\n" +
	"\tPropSlide\x12-\n" +
	"\n" +
	"base_slide\x18\x01 \x01(\v2\x0e.rv.data.SlideR\tbaseSlide\x123\n" +
	"\n" +
	"transition\x18\x02 \x01(\v2\x13.rv.data.TransitionR\n" +
	"transitionB\x95\x01\n" +
	"\vcom.rv.dataB\x0ePropSlideProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_propSlide_proto_rawDescOnce sync.Once
	file_propSlide_proto_rawDescData []byte
)

func file_propSlide_proto_rawDescGZIP() []byte {
	file_propSlide_proto_rawDescOnce.Do(func() {
		file_propSlide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_propSlide_proto_rawDesc), len(file_propSlide_proto_rawDesc)))
	})
	return file_propSlide_proto_rawDescData
}

var file_propSlide_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_propSlide_proto_goTypes = []any{
	(*PropSlide)(nil),  // 0: rv.data.PropSlide
	(*Slide)(nil),      // 1: rv.data.Slide
	(*Transition)(nil), // 2: rv.data.Transition
}
var file_propSlide_proto_depIdxs = []int32{
	1, // 0: rv.data.PropSlide.base_slide:type_name -> rv.data.Slide
	2, // 1: rv.data.PropSlide.transition:type_name -> rv.data.Transition
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_propSlide_proto_init() }
func file_propSlide_proto_init() {
	if File_propSlide_proto != nil {
		return
	}
	file_slide_proto_init()
	file_effects_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_propSlide_proto_rawDesc), len(file_propSlide_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_propSlide_proto_goTypes,
		DependencyIndexes: file_propSlide_proto_depIdxs,
		MessageInfos:      file_propSlide_proto_msgTypes,
	}.Build()
	File_propSlide_proto = out.File
	file_propSlide_proto_goTypes = nil
	file_propSlide_proto_depIdxs = nil
}
