// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: propDocument.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropDocument struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationInfo *ApplicationInfo       `protobuf:"bytes,1,opt,name=application_info,json=applicationInfo,proto3" json:"application_info,omitempty"`
	Cues            []*Cue                 `protobuf:"bytes,2,rep,name=cues,proto3" json:"cues,omitempty"`
	Transition      *Transition            `protobuf:"bytes,3,opt,name=transition,proto3" json:"transition,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PropDocument) Reset() {
	*x = PropDocument{}
	mi := &file_propDocument_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropDocument) ProtoMessage() {}

func (x *PropDocument) ProtoReflect() protoreflect.Message {
	mi := &file_propDocument_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropDocument.ProtoReflect.Descriptor instead.
func (*PropDocument) Descriptor() ([]byte, []int) {
	return file_propDocument_proto_rawDescGZIP(), []int{0}
}

func (x *PropDocument) GetApplicationInfo() *ApplicationInfo {
	if x != nil {
		return x.ApplicationInfo
	}
	return nil
}

func (x *PropDocument) GetCues() []*Cue {
	if x != nil {
		return x.Cues
	}
	return nil
}

func (x *PropDocument) GetTransition() *Transition {
	if x != nil {
		return x.Transition
	}
	return nil
}

var File_propDocument_proto protoreflect.FileDescriptor

const file_propDocument_proto_rawDesc = "" +
	"\n" +
	"\x12propDocument.proto\x12\arv.data\x1a\x10basicTypes.proto\x1a\tcue.proto\x1a\reffects.proto\"\xaa\x01\n" +
	"\fPropDocument\x12C\n" +
	"\x10application_info\x18\x01 \x01(\v2\x18.rv.data.ApplicationInfoR\x0fapplicationInfo\x12 \n" +
	"\x04cues\x18\x02 \x03(\v2\f.rv.data.CueR\x04cues\x123\n" +
	"\n" +
	"transition\x18\x03 \x01(\v2\x13.rv.data.TransitionR\n" +
	"transitionB\x98\x01\n" +
	"\vcom.rv.dataB\x11PropDocumentProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_propDocument_proto_rawDescOnce sync.Once
	file_propDocument_proto_rawDescData []byte
)

func file_propDocument_proto_rawDescGZIP() []byte {
	file_propDocument_proto_rawDescOnce.Do(func() {
		file_propDocument_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_propDocument_proto_rawDesc), len(file_propDocument_proto_rawDesc)))
	})
	return file_propDocument_proto_rawDescData
}

var file_propDocument_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_propDocument_proto_goTypes = []any{
	(*PropDocument)(nil),    // 0: rv.data.PropDocument
	(*ApplicationInfo)(nil), // 1: rv.data.ApplicationInfo
	(*Cue)(nil),             // 2: rv.data.Cue
	(*Transition)(nil),      // 3: rv.data.Transition
}
var file_propDocument_proto_depIdxs = []int32{
	1, // 0: rv.data.PropDocument.application_info:type_name -> rv.data.ApplicationInfo
	2, // 1: rv.data.PropDocument.cues:type_name -> rv.data.Cue
	3, // 2: rv.data.PropDocument.transition:type_name -> rv.data.Transition
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_propDocument_proto_init() }
func file_propDocument_proto_init() {
	if File_propDocument_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_cue_proto_init()
	file_effects_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_propDocument_proto_rawDesc), len(file_propDocument_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_propDocument_proto_goTypes,
		DependencyIndexes: file_propDocument_proto_depIdxs,
		MessageInfos:      file_propDocument_proto_msgTypes,
	}.Build()
	File_propDocument_proto = out.File
	file_propDocument_proto_goTypes = nil
	file_propDocument_proto_depIdxs = nil
}
