// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: proscreen.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProPresenterScreen_ScreenType int32

const (
	ProPresenterScreen_SCREEN_TYPE_UNKNOWN  ProPresenterScreen_ScreenType = 0
	ProPresenterScreen_SCREEN_TYPE_AUDIENCE ProPresenterScreen_ScreenType = 1
	ProPresenterScreen_SCREEN_TYPE_STAGE    ProPresenterScreen_ScreenType = 2
)

// Enum value maps for ProPresenterScreen_ScreenType.
var (
	ProPresenterScreen_ScreenType_name = map[int32]string{
		0: "SCREEN_TYPE_UNKNOWN",
		1: "SCREEN_TYPE_AUDIENCE",
		2: "SCREEN_TYPE_STAGE",
	}
	ProPresenterScreen_ScreenType_value = map[string]int32{
		"SCREEN_TYPE_UNKNOWN":  0,
		"SCREEN_TYPE_AUDIENCE": 1,
		"SCREEN_TYPE_STAGE":    2,
	}
)

func (x ProPresenterScreen_ScreenType) Enum() *ProPresenterScreen_ScreenType {
	p := new(ProPresenterScreen_ScreenType)
	*p = x
	return p
}

func (x ProPresenterScreen_ScreenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProPresenterScreen_ScreenType) Descriptor() protoreflect.EnumDescriptor {
	return file_proscreen_proto_enumTypes[0].Descriptor()
}

func (ProPresenterScreen_ScreenType) Type() protoreflect.EnumType {
	return &file_proscreen_proto_enumTypes[0]
}

func (x ProPresenterScreen_ScreenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProPresenterScreen_ScreenType.Descriptor instead.
func (ProPresenterScreen_ScreenType) EnumDescriptor() ([]byte, []int) {
	return file_proscreen_proto_rawDescGZIP(), []int{0, 0}
}

type ProPresenterScreen struct {
	state                  protoimpl.MessageState        `protogen:"open.v1"`
	Name                   string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ScreenType             ProPresenterScreen_ScreenType `protobuf:"varint,2,opt,name=screen_type,json=screenType,proto3,enum=rv.data.ProPresenterScreen_ScreenType" json:"screen_type,omitempty"`
	BackgroundColor        *Color                        `protobuf:"bytes,6,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	Uuid                   *UUID                         `protobuf:"bytes,7,opt,name=uuid,proto3" json:"uuid,omitempty"`
	BackgroundColorEnabled bool                          `protobuf:"varint,8,opt,name=background_color_enabled,json=backgroundColorEnabled,proto3" json:"background_color_enabled,omitempty"`
	// Types that are valid to be assigned to Arrangement:
	//
	//	*ProPresenterScreen_ArrangementSingle
	//	*ProPresenterScreen_ArrangementCombined
	//	*ProPresenterScreen_ArrangementEdgeBlend
	Arrangement   isProPresenterScreen_Arrangement `protobuf_oneof:"Arrangement"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProPresenterScreen) Reset() {
	*x = ProPresenterScreen{}
	mi := &file_proscreen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProPresenterScreen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProPresenterScreen) ProtoMessage() {}

func (x *ProPresenterScreen) ProtoReflect() protoreflect.Message {
	mi := &file_proscreen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProPresenterScreen.ProtoReflect.Descriptor instead.
func (*ProPresenterScreen) Descriptor() ([]byte, []int) {
	return file_proscreen_proto_rawDescGZIP(), []int{0}
}

func (x *ProPresenterScreen) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProPresenterScreen) GetScreenType() ProPresenterScreen_ScreenType {
	if x != nil {
		return x.ScreenType
	}
	return ProPresenterScreen_SCREEN_TYPE_UNKNOWN
}

func (x *ProPresenterScreen) GetBackgroundColor() *Color {
	if x != nil {
		return x.BackgroundColor
	}
	return nil
}

func (x *ProPresenterScreen) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *ProPresenterScreen) GetBackgroundColorEnabled() bool {
	if x != nil {
		return x.BackgroundColorEnabled
	}
	return false
}

func (x *ProPresenterScreen) GetArrangement() isProPresenterScreen_Arrangement {
	if x != nil {
		return x.Arrangement
	}
	return nil
}

func (x *ProPresenterScreen) GetArrangementSingle() *ProPresenterScreen_SingleArrangement {
	if x != nil {
		if x, ok := x.Arrangement.(*ProPresenterScreen_ArrangementSingle); ok {
			return x.ArrangementSingle
		}
	}
	return nil
}

func (x *ProPresenterScreen) GetArrangementCombined() *ProPresenterScreen_CombinedArrangement {
	if x != nil {
		if x, ok := x.Arrangement.(*ProPresenterScreen_ArrangementCombined); ok {
			return x.ArrangementCombined
		}
	}
	return nil
}

func (x *ProPresenterScreen) GetArrangementEdgeBlend() *ProPresenterScreen_EdgeBlendArrangement {
	if x != nil {
		if x, ok := x.Arrangement.(*ProPresenterScreen_ArrangementEdgeBlend); ok {
			return x.ArrangementEdgeBlend
		}
	}
	return nil
}

type isProPresenterScreen_Arrangement interface {
	isProPresenterScreen_Arrangement()
}

type ProPresenterScreen_ArrangementSingle struct {
	ArrangementSingle *ProPresenterScreen_SingleArrangement `protobuf:"bytes,3,opt,name=arrangement_single,json=arrangementSingle,proto3,oneof"`
}

type ProPresenterScreen_ArrangementCombined struct {
	ArrangementCombined *ProPresenterScreen_CombinedArrangement `protobuf:"bytes,4,opt,name=arrangement_combined,json=arrangementCombined,proto3,oneof"`
}

type ProPresenterScreen_ArrangementEdgeBlend struct {
	ArrangementEdgeBlend *ProPresenterScreen_EdgeBlendArrangement `protobuf:"bytes,5,opt,name=arrangement_edge_blend,json=arrangementEdgeBlend,proto3,oneof"`
}

func (*ProPresenterScreen_ArrangementSingle) isProPresenterScreen_Arrangement() {}

func (*ProPresenterScreen_ArrangementCombined) isProPresenterScreen_Arrangement() {}

func (*ProPresenterScreen_ArrangementEdgeBlend) isProPresenterScreen_Arrangement() {}

type ProPresenterScreen_SingleArrangement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Screens       []*Screen              `protobuf:"bytes,1,rep,name=screens,proto3" json:"screens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProPresenterScreen_SingleArrangement) Reset() {
	*x = ProPresenterScreen_SingleArrangement{}
	mi := &file_proscreen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProPresenterScreen_SingleArrangement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProPresenterScreen_SingleArrangement) ProtoMessage() {}

func (x *ProPresenterScreen_SingleArrangement) ProtoReflect() protoreflect.Message {
	mi := &file_proscreen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProPresenterScreen_SingleArrangement.ProtoReflect.Descriptor instead.
func (*ProPresenterScreen_SingleArrangement) Descriptor() ([]byte, []int) {
	return file_proscreen_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProPresenterScreen_SingleArrangement) GetScreens() []*Screen {
	if x != nil {
		return x.Screens
	}
	return nil
}

type ProPresenterScreen_CombinedArrangement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Screens       []*Screen              `protobuf:"bytes,1,rep,name=screens,proto3" json:"screens,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns       uint32                 `protobuf:"varint,3,opt,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProPresenterScreen_CombinedArrangement) Reset() {
	*x = ProPresenterScreen_CombinedArrangement{}
	mi := &file_proscreen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProPresenterScreen_CombinedArrangement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProPresenterScreen_CombinedArrangement) ProtoMessage() {}

func (x *ProPresenterScreen_CombinedArrangement) ProtoReflect() protoreflect.Message {
	mi := &file_proscreen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProPresenterScreen_CombinedArrangement.ProtoReflect.Descriptor instead.
func (*ProPresenterScreen_CombinedArrangement) Descriptor() ([]byte, []int) {
	return file_proscreen_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ProPresenterScreen_CombinedArrangement) GetScreens() []*Screen {
	if x != nil {
		return x.Screens
	}
	return nil
}

func (x *ProPresenterScreen_CombinedArrangement) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ProPresenterScreen_CombinedArrangement) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

type ProPresenterScreen_EdgeBlendArrangement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenCount   uint32                 `protobuf:"varint,1,opt,name=screen_count,json=screenCount,proto3" json:"screen_count,omitempty"`
	Screens       []*Screen              `protobuf:"bytes,2,rep,name=screens,proto3" json:"screens,omitempty"`
	EdgeBlends    []*EdgeBlend           `protobuf:"bytes,3,rep,name=edge_blends,json=edgeBlends,proto3" json:"edge_blends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProPresenterScreen_EdgeBlendArrangement) Reset() {
	*x = ProPresenterScreen_EdgeBlendArrangement{}
	mi := &file_proscreen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProPresenterScreen_EdgeBlendArrangement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProPresenterScreen_EdgeBlendArrangement) ProtoMessage() {}

func (x *ProPresenterScreen_EdgeBlendArrangement) ProtoReflect() protoreflect.Message {
	mi := &file_proscreen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProPresenterScreen_EdgeBlendArrangement.ProtoReflect.Descriptor instead.
func (*ProPresenterScreen_EdgeBlendArrangement) Descriptor() ([]byte, []int) {
	return file_proscreen_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ProPresenterScreen_EdgeBlendArrangement) GetScreenCount() uint32 {
	if x != nil {
		return x.ScreenCount
	}
	return 0
}

func (x *ProPresenterScreen_EdgeBlendArrangement) GetScreens() []*Screen {
	if x != nil {
		return x.Screens
	}
	return nil
}

func (x *ProPresenterScreen_EdgeBlendArrangement) GetEdgeBlends() []*EdgeBlend {
	if x != nil {
		return x.EdgeBlends
	}
	return nil
}

var File_proscreen_proto protoreflect.FileDescriptor

const file_proscreen_proto_rawDesc = "" +
	"\n" +
	"\x0fproscreen.proto\x12\arv.data\x1a\rscreens.proto\x1a\x10basicTypes.proto\"\xec\a\n" +
	"\x12ProPresenterScreen\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12G\n" +
	"\vscreen_type\x18\x02 \x01(\x0e2&.rv.data.ProPresenterScreen.ScreenTypeR\n" +
	"screenType\x129\n" +
	"\x10background_color\x18\x06 \x01(\v2\x0e.rv.data.ColorR\x0fbackgroundColor\x12!\n" +
	"\x04uuid\x18\a \x01(\v2\r.rv.data.UUIDR\x04uuid\x128\n" +
	"\x18background_color_enabled\x18\b \x01(\bR\x16backgroundColorEnabled\x12^\n" +
	"\x12arrangement_single\x18\x03 \x01(\v2-.rv.data.ProPresenterScreen.SingleArrangementH\x00R\x11arrangementSingle\x12d\n" +
	"\x14arrangement_combined\x18\x04 \x01(\v2/.rv.data.ProPresenterScreen.CombinedArrangementH\x00R\x13arrangementCombined\x12h\n" +
	"\x16arrangement_edge_blend\x18\x05 \x01(\v20.rv.data.ProPresenterScreen.EdgeBlendArrangementH\x00R\x14arrangementEdgeBlend\x1a>\n" +
	"\x11SingleArrangement\x12)\n" +
	"\ascreens\x18\x01 \x03(\v2\x0f.rv.data.ScreenR\ascreens\x1an\n" +
	"\x13CombinedArrangement\x12)\n" +
	"\ascreens\x18\x01 \x03(\v2\x0f.rv.data.ScreenR\ascreens\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x18\n" +
	"\acolumns\x18\x03 \x01(\rR\acolumns\x1a\x99\x01\n" +
	"\x14EdgeBlendArrangement\x12!\n" +
	"\fscreen_count\x18\x01 \x01(\rR\vscreenCount\x12)\n" +
	"\ascreens\x18\x02 \x03(\v2\x0f.rv.data.ScreenR\ascreens\x123\n" +
	"\vedge_blends\x18\x03 \x03(\v2\x12.rv.data.EdgeBlendR\n" +
	"edgeBlends\"V\n" +
	"\n" +
	"ScreenType\x12\x17\n" +
	"\x13SCREEN_TYPE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14SCREEN_TYPE_AUDIENCE\x10\x01\x12\x15\n" +
	"\x11SCREEN_TYPE_STAGE\x10\x02B\r\n" +
	"\vArrangementB\x94\x01\n" +
	"\vcom.rv.dataB\x0eProscreenProtoP\x01Z8github.com/thatguycleeb/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_proscreen_proto_rawDescOnce sync.Once
	file_proscreen_proto_rawDescData []byte
)

func file_proscreen_proto_rawDescGZIP() []byte {
	file_proscreen_proto_rawDescOnce.Do(func() {
		file_proscreen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proscreen_proto_rawDesc), len(file_proscreen_proto_rawDesc)))
	})
	return file_proscreen_proto_rawDescData
}

var file_proscreen_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proscreen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proscreen_proto_goTypes = []any{
	(ProPresenterScreen_ScreenType)(0),              // 0: rv.data.ProPresenterScreen.ScreenType
	(*ProPresenterScreen)(nil),                      // 1: rv.data.ProPresenterScreen
	(*ProPresenterScreen_SingleArrangement)(nil),    // 2: rv.data.ProPresenterScreen.SingleArrangement
	(*ProPresenterScreen_CombinedArrangement)(nil),  // 3: rv.data.ProPresenterScreen.CombinedArrangement
	(*ProPresenterScreen_EdgeBlendArrangement)(nil), // 4: rv.data.ProPresenterScreen.EdgeBlendArrangement
	(*Color)(nil),     // 5: rv.data.Color
	(*UUID)(nil),      // 6: rv.data.UUID
	(*Screen)(nil),    // 7: rv.data.Screen
	(*EdgeBlend)(nil), // 8: rv.data.EdgeBlend
}
var file_proscreen_proto_depIdxs = []int32{
	0,  // 0: rv.data.ProPresenterScreen.screen_type:type_name -> rv.data.ProPresenterScreen.ScreenType
	5,  // 1: rv.data.ProPresenterScreen.background_color:type_name -> rv.data.Color
	6,  // 2: rv.data.ProPresenterScreen.uuid:type_name -> rv.data.UUID
	2,  // 3: rv.data.ProPresenterScreen.arrangement_single:type_name -> rv.data.ProPresenterScreen.SingleArrangement
	3,  // 4: rv.data.ProPresenterScreen.arrangement_combined:type_name -> rv.data.ProPresenterScreen.CombinedArrangement
	4,  // 5: rv.data.ProPresenterScreen.arrangement_edge_blend:type_name -> rv.data.ProPresenterScreen.EdgeBlendArrangement
	7,  // 6: rv.data.ProPresenterScreen.SingleArrangement.screens:type_name -> rv.data.Screen
	7,  // 7: rv.data.ProPresenterScreen.CombinedArrangement.screens:type_name -> rv.data.Screen
	7,  // 8: rv.data.ProPresenterScreen.EdgeBlendArrangement.screens:type_name -> rv.data.Screen
	8,  // 9: rv.data.ProPresenterScreen.EdgeBlendArrangement.edge_blends:type_name -> rv.data.EdgeBlend
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proscreen_proto_init() }
func file_proscreen_proto_init() {
	if File_proscreen_proto != nil {
		return
	}
	file_screens_proto_init()
	file_basicTypes_proto_init()
	file_proscreen_proto_msgTypes[0].OneofWrappers = []any{
		(*ProPresenterScreen_ArrangementSingle)(nil),
		(*ProPresenterScreen_ArrangementCombined)(nil),
		(*ProPresenterScreen_ArrangementEdgeBlend)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proscreen_proto_rawDesc), len(file_proscreen_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proscreen_proto_goTypes,
		DependencyIndexes: file_proscreen_proto_depIdxs,
		EnumInfos:         file_proscreen_proto_enumTypes,
		MessageInfos:      file_proscreen_proto_msgTypes,
	}.Build()
	File_proscreen_proto = out.File
	file_proscreen_proto_goTypes = nil
	file_proscreen_proto_depIdxs = nil
}
