// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: stage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_stage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_stage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_stage_proto_rawDescGZIP(), []int{0}
}

type Stage_Layout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *UUID                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slide         *Slide                 `protobuf:"bytes,3,opt,name=slide,proto3" json:"slide,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage_Layout) Reset() {
	*x = Stage_Layout{}
	mi := &file_stage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage_Layout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage_Layout) ProtoMessage() {}

func (x *Stage_Layout) ProtoReflect() protoreflect.Message {
	mi := &file_stage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage_Layout.ProtoReflect.Descriptor instead.
func (*Stage_Layout) Descriptor() ([]byte, []int) {
	return file_stage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Stage_Layout) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Stage_Layout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stage_Layout) GetSlide() *Slide {
	if x != nil {
		return x.Slide
	}
	return nil
}

type Stage_Document struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationInfo *ApplicationInfo       `protobuf:"bytes,1,opt,name=application_info,json=applicationInfo,proto3" json:"application_info,omitempty"`
	Layouts         []*Stage_Layout        `protobuf:"bytes,2,rep,name=layouts,proto3" json:"layouts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Stage_Document) Reset() {
	*x = Stage_Document{}
	mi := &file_stage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage_Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage_Document) ProtoMessage() {}

func (x *Stage_Document) ProtoReflect() protoreflect.Message {
	mi := &file_stage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage_Document.ProtoReflect.Descriptor instead.
func (*Stage_Document) Descriptor() ([]byte, []int) {
	return file_stage_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Stage_Document) GetApplicationInfo() *ApplicationInfo {
	if x != nil {
		return x.ApplicationInfo
	}
	return nil
}

func (x *Stage_Document) GetLayouts() []*Stage_Layout {
	if x != nil {
		return x.Layouts
	}
	return nil
}

type Stage_ScreenAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Screen        *CollectionElementType `protobuf:"bytes,1,opt,name=screen,proto3" json:"screen,omitempty"`
	Layout        *CollectionElementType `protobuf:"bytes,2,opt,name=layout,proto3" json:"layout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage_ScreenAssignment) Reset() {
	*x = Stage_ScreenAssignment{}
	mi := &file_stage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage_ScreenAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage_ScreenAssignment) ProtoMessage() {}

func (x *Stage_ScreenAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_stage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage_ScreenAssignment.ProtoReflect.Descriptor instead.
func (*Stage_ScreenAssignment) Descriptor() ([]byte, []int) {
	return file_stage_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Stage_ScreenAssignment) GetScreen() *CollectionElementType {
	if x != nil {
		return x.Screen
	}
	return nil
}

func (x *Stage_ScreenAssignment) GetLayout() *CollectionElementType {
	if x != nil {
		return x.Layout
	}
	return nil
}

var File_stage_proto protoreflect.FileDescriptor

const file_stage_proto_rawDesc = "" +
	"\n" +
	"\vstage.proto\x12\arv.data\x1a\x10basicTypes.proto\x1a\vslide.proto\"\xf6\x02\n" +
	"\x05Stage\x1ae\n" +
	"\x06Layout\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x05slide\x18\x03 \x01(\v2\x0e.rv.data.SlideR\x05slide\x1a\x80\x01\n" +
	"\bDocument\x12C\n" +
	"\x10application_info\x18\x01 \x01(\v2\x18.rv.data.ApplicationInfoR\x0fapplicationInfo\x12/\n" +
	"\alayouts\x18\x02 \x03(\v2\x15.rv.data.Stage.LayoutR\alayouts\x1a\x82\x01\n" +
	"\x10ScreenAssignment\x126\n" +
	"\x06screen\x18\x01 \x01(\v2\x1e.rv.data.CollectionElementTypeR\x06screen\x126\n" +
	"\x06layout\x18\x02 \x01(\v2\x1e.rv.data.CollectionElementTypeR\x06layoutB\x90\x01\n" +
	"\vcom.rv.dataB\n" +
	"StageProtoP\x01Z8github.com/thatguycleeb/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_stage_proto_rawDescOnce sync.Once
	file_stage_proto_rawDescData []byte
)

func file_stage_proto_rawDescGZIP() []byte {
	file_stage_proto_rawDescOnce.Do(func() {
		file_stage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stage_proto_rawDesc), len(file_stage_proto_rawDesc)))
	})
	return file_stage_proto_rawDescData
}

var file_stage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stage_proto_goTypes = []any{
	(*Stage)(nil),                  // 0: rv.data.Stage
	(*Stage_Layout)(nil),           // 1: rv.data.Stage.Layout
	(*Stage_Document)(nil),         // 2: rv.data.Stage.Document
	(*Stage_ScreenAssignment)(nil), // 3: rv.data.Stage.ScreenAssignment
	(*UUID)(nil),                   // 4: rv.data.UUID
	(*Slide)(nil),                  // 5: rv.data.Slide
	(*ApplicationInfo)(nil),        // 6: rv.data.ApplicationInfo
	(*CollectionElementType)(nil),  // 7: rv.data.CollectionElementType
}
var file_stage_proto_depIdxs = []int32{
	4, // 0: rv.data.Stage.Layout.uuid:type_name -> rv.data.UUID
	5, // 1: rv.data.Stage.Layout.slide:type_name -> rv.data.Slide
	6, // 2: rv.data.Stage.Document.application_info:type_name -> rv.data.ApplicationInfo
	1, // 3: rv.data.Stage.Document.layouts:type_name -> rv.data.Stage.Layout
	7, // 4: rv.data.Stage.ScreenAssignment.screen:type_name -> rv.data.CollectionElementType
	7, // 5: rv.data.Stage.ScreenAssignment.layout:type_name -> rv.data.CollectionElementType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_stage_proto_init() }
func file_stage_proto_init() {
	if File_stage_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_slide_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stage_proto_rawDesc), len(file_stage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stage_proto_goTypes,
		DependencyIndexes: file_stage_proto_depIdxs,
		MessageInfos:      file_stage_proto_msgTypes,
	}.Build()
	File_stage_proto = out.File
	file_stage_proto_goTypes = nil
	file_stage_proto_depIdxs = nil
}
