// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: templateIdentification.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplateIdentification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *UUID                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SlideUuid     *UUID                  `protobuf:"bytes,3,opt,name=slide_uuid,json=slideUuid,proto3" json:"slide_uuid,omitempty"`
	SlideName     string                 `protobuf:"bytes,4,opt,name=slide_name,json=slideName,proto3" json:"slide_name,omitempty"`
	SlideIndex    uint32                 `protobuf:"varint,5,opt,name=slide_index,json=slideIndex,proto3" json:"slide_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateIdentification) Reset() {
	*x = TemplateIdentification{}
	mi := &file_templateIdentification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateIdentification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateIdentification) ProtoMessage() {}

func (x *TemplateIdentification) ProtoReflect() protoreflect.Message {
	mi := &file_templateIdentification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateIdentification.ProtoReflect.Descriptor instead.
func (*TemplateIdentification) Descriptor() ([]byte, []int) {
	return file_templateIdentification_proto_rawDescGZIP(), []int{0}
}

func (x *TemplateIdentification) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *TemplateIdentification) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateIdentification) GetSlideUuid() *UUID {
	if x != nil {
		return x.SlideUuid
	}
	return nil
}

func (x *TemplateIdentification) GetSlideName() string {
	if x != nil {
		return x.SlideName
	}
	return ""
}

func (x *TemplateIdentification) GetSlideIndex() uint32 {
	if x != nil {
		return x.SlideIndex
	}
	return 0
}

var File_templateIdentification_proto protoreflect.FileDescriptor

const file_templateIdentification_proto_rawDesc = "" +
	"\n" +
	"\x1ctemplateIdentification.proto\x12\arv.data\x1a\x10basicTypes.proto\"\xbd\x01\n" +
	"\x16TemplateIdentification\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\n" +
	"slide_uuid\x18\x03 \x01(\v2\r.rv.data.UUIDR\tslideUuid\x12\x1d\n" +
	"\n" +
	"slide_name\x18\x04 \x01(\tR\tslideName\x12\x1f\n" +
	"\vslide_index\x18\x05 \x01(\rR\n" +
	"slideIndexB\xa2\x01\n" +
	"\vcom.rv.dataB\x1bTemplateIdentificationProtoP\x01Z9github.com/rivers-church/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_templateIdentification_proto_rawDescOnce sync.Once
	file_templateIdentification_proto_rawDescData []byte
)

func file_templateIdentification_proto_rawDescGZIP() []byte {
	file_templateIdentification_proto_rawDescOnce.Do(func() {
		file_templateIdentification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_templateIdentification_proto_rawDesc), len(file_templateIdentification_proto_rawDesc)))
	})
	return file_templateIdentification_proto_rawDescData
}

var file_templateIdentification_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_templateIdentification_proto_goTypes = []any{
	(*TemplateIdentification)(nil), // 0: rv.data.TemplateIdentification
	(*UUID)(nil),                   // 1: rv.data.UUID
}
var file_templateIdentification_proto_depIdxs = []int32{
	1, // 0: rv.data.TemplateIdentification.uuid:type_name -> rv.data.UUID
	1, // 1: rv.data.TemplateIdentification.slide_uuid:type_name -> rv.data.UUID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_templateIdentification_proto_init() }
func file_templateIdentification_proto_init() {
	if File_templateIdentification_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_templateIdentification_proto_rawDesc), len(file_templateIdentification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_templateIdentification_proto_goTypes,
		DependencyIndexes: file_templateIdentification_proto_depIdxs,
		MessageInfos:      file_templateIdentification_proto_msgTypes,
	}.Build()
	File_templateIdentification_proto = out.File
	file_templateIdentification_proto_goTypes = nil
	file_templateIdentification_proto_depIdxs = nil
}
