// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: testPattern.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestPattern_Type int32

const (
	TestPattern_TYPE_UNKNOWN      TestPattern_Type = 0
	TestPattern_TYPE_BLEND_GRID   TestPattern_Type = 1
	TestPattern_TYPE_COLOR_BARS   TestPattern_Type = 2
	TestPattern_TYPE_FOCUS        TestPattern_Type = 3
	TestPattern_TYPE_GRAY_SCALE   TestPattern_Type = 4
	TestPattern_TYPE_BLACK_COLOR  TestPattern_Type = 5
	TestPattern_TYPE_WHITE_COLOR  TestPattern_Type = 6
	TestPattern_TYPE_CUSTOM_COLOR TestPattern_Type = 7
)

// Enum value maps for TestPattern_Type.
var (
	TestPattern_Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_BLEND_GRID",
		2: "TYPE_COLOR_BARS",
		3: "TYPE_FOCUS",
		4: "TYPE_GRAY_SCALE",
		5: "TYPE_BLACK_COLOR",
		6: "TYPE_WHITE_COLOR",
		7: "TYPE_CUSTOM_COLOR",
	}
	TestPattern_Type_value = map[string]int32{
		"TYPE_UNKNOWN":      0,
		"TYPE_BLEND_GRID":   1,
		"TYPE_COLOR_BARS":   2,
		"TYPE_FOCUS":        3,
		"TYPE_GRAY_SCALE":   4,
		"TYPE_BLACK_COLOR":  5,
		"TYPE_WHITE_COLOR":  6,
		"TYPE_CUSTOM_COLOR": 7,
	}
)

func (x TestPattern_Type) Enum() *TestPattern_Type {
	p := new(TestPattern_Type)
	*p = x
	return p
}

func (x TestPattern_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestPattern_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_testPattern_proto_enumTypes[0].Descriptor()
}

func (TestPattern_Type) Type() protoreflect.EnumType {
	return &file_testPattern_proto_enumTypes[0]
}

func (x TestPattern_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestPattern_Type.Descriptor instead.
func (TestPattern_Type) EnumDescriptor() ([]byte, []int) {
	return file_testPattern_proto_rawDescGZIP(), []int{0, 0}
}

type TestPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  TestPattern_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=rv.data.TestPattern_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to PatternProperties:
	//
	//	*TestPattern_BlendGrid_
	//	*TestPattern_CustomColor_
	//	*TestPattern_Intensity
	PatternProperties isTestPattern_PatternProperties `protobuf_oneof:"PatternProperties"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TestPattern) Reset() {
	*x = TestPattern{}
	mi := &file_testPattern_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPattern) ProtoMessage() {}

func (x *TestPattern) ProtoReflect() protoreflect.Message {
	mi := &file_testPattern_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPattern.ProtoReflect.Descriptor instead.
func (*TestPattern) Descriptor() ([]byte, []int) {
	return file_testPattern_proto_rawDescGZIP(), []int{0}
}

func (x *TestPattern) GetType() TestPattern_Type {
	if x != nil {
		return x.Type
	}
	return TestPattern_TYPE_UNKNOWN
}

func (x *TestPattern) GetPatternProperties() isTestPattern_PatternProperties {
	if x != nil {
		return x.PatternProperties
	}
	return nil
}

func (x *TestPattern) GetBlendGrid() *TestPattern_BlendGrid {
	if x != nil {
		if x, ok := x.PatternProperties.(*TestPattern_BlendGrid_); ok {
			return x.BlendGrid
		}
	}
	return nil
}

func (x *TestPattern) GetCustomColor() *TestPattern_CustomColor {
	if x != nil {
		if x, ok := x.PatternProperties.(*TestPattern_CustomColor_); ok {
			return x.CustomColor
		}
	}
	return nil
}

func (x *TestPattern) GetIntensity() *TestPattern_IntensityColor {
	if x != nil {
		if x, ok := x.PatternProperties.(*TestPattern_Intensity); ok {
			return x.Intensity
		}
	}
	return nil
}

type isTestPattern_PatternProperties interface {
	isTestPattern_PatternProperties()
}

type TestPattern_BlendGrid_ struct {
	BlendGrid *TestPattern_BlendGrid `protobuf:"bytes,2,opt,name=blend_grid,json=blendGrid,proto3,oneof"`
}

type TestPattern_CustomColor_ struct {
	CustomColor *TestPattern_CustomColor `protobuf:"bytes,3,opt,name=custom_color,json=customColor,proto3,oneof"`
}

type TestPattern_Intensity struct {
	Intensity *TestPattern_IntensityColor `protobuf:"bytes,4,opt,name=intensity,proto3,oneof"`
}

func (*TestPattern_BlendGrid_) isTestPattern_PatternProperties() {}

func (*TestPattern_CustomColor_) isTestPattern_PatternProperties() {}

func (*TestPattern_Intensity) isTestPattern_PatternProperties() {}

type TestPattern_BlendGrid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrawGrid      bool                   `protobuf:"varint,1,opt,name=draw_grid,json=drawGrid,proto3" json:"draw_grid,omitempty"`
	DrawCircles   bool                   `protobuf:"varint,2,opt,name=draw_circles,json=drawCircles,proto3" json:"draw_circles,omitempty"`
	DrawLines     bool                   `protobuf:"varint,3,opt,name=draw_lines,json=drawLines,proto3" json:"draw_lines,omitempty"`
	InvertColors  bool                   `protobuf:"varint,4,opt,name=invert_colors,json=invertColors,proto3" json:"invert_colors,omitempty"`
	GridSpacing   float64                `protobuf:"fixed64,5,opt,name=grid_spacing,json=gridSpacing,proto3" json:"grid_spacing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPattern_BlendGrid) Reset() {
	*x = TestPattern_BlendGrid{}
	mi := &file_testPattern_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPattern_BlendGrid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPattern_BlendGrid) ProtoMessage() {}

func (x *TestPattern_BlendGrid) ProtoReflect() protoreflect.Message {
	mi := &file_testPattern_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPattern_BlendGrid.ProtoReflect.Descriptor instead.
func (*TestPattern_BlendGrid) Descriptor() ([]byte, []int) {
	return file_testPattern_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TestPattern_BlendGrid) GetDrawGrid() bool {
	if x != nil {
		return x.DrawGrid
	}
	return false
}

func (x *TestPattern_BlendGrid) GetDrawCircles() bool {
	if x != nil {
		return x.DrawCircles
	}
	return false
}

func (x *TestPattern_BlendGrid) GetDrawLines() bool {
	if x != nil {
		return x.DrawLines
	}
	return false
}

func (x *TestPattern_BlendGrid) GetInvertColors() bool {
	if x != nil {
		return x.InvertColors
	}
	return false
}

func (x *TestPattern_BlendGrid) GetGridSpacing() float64 {
	if x != nil {
		return x.GridSpacing
	}
	return 0
}

type TestPattern_CustomColor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *Color                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPattern_CustomColor) Reset() {
	*x = TestPattern_CustomColor{}
	mi := &file_testPattern_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPattern_CustomColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPattern_CustomColor) ProtoMessage() {}

func (x *TestPattern_CustomColor) ProtoReflect() protoreflect.Message {
	mi := &file_testPattern_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPattern_CustomColor.ProtoReflect.Descriptor instead.
func (*TestPattern_CustomColor) Descriptor() ([]byte, []int) {
	return file_testPattern_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TestPattern_CustomColor) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type TestPattern_IntensityColor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intensity     float64                `protobuf:"fixed64,1,opt,name=intensity,proto3" json:"intensity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPattern_IntensityColor) Reset() {
	*x = TestPattern_IntensityColor{}
	mi := &file_testPattern_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPattern_IntensityColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPattern_IntensityColor) ProtoMessage() {}

func (x *TestPattern_IntensityColor) ProtoReflect() protoreflect.Message {
	mi := &file_testPattern_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPattern_IntensityColor.ProtoReflect.Descriptor instead.
func (*TestPattern_IntensityColor) Descriptor() ([]byte, []int) {
	return file_testPattern_proto_rawDescGZIP(), []int{0, 2}
}

func (x *TestPattern_IntensityColor) GetIntensity() float64 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

var File_testPattern_proto protoreflect.FileDescriptor

const file_testPattern_proto_rawDesc = "" +
	"\n" +
	"\x11testPattern.proto\x12\arv.data\x1a\x10basicTypes.proto\"\xe5\x05\n" +
	"\vTestPattern\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.rv.data.TestPattern.TypeR\x04type\x12?\n" +
	"\n" +
	"blend_grid\x18\x02 \x01(\v2\x1e.rv.data.TestPattern.BlendGridH\x00R\tblendGrid\x12E\n" +
	"\fcustom_color\x18\x03 \x01(\v2 .rv.data.TestPattern.CustomColorH\x00R\vcustomColor\x12C\n" +
	"\tintensity\x18\x04 \x01(\v2#.rv.data.TestPattern.IntensityColorH\x00R\tintensity\x1a\xb2\x01\n" +
	"\tBlendGrid\x12\x1b\n" +
	"\tdraw_grid\x18\x01 \x01(\bR\bdrawGrid\x12!\n" +
	"\fdraw_circles\x18\x02 \x01(\bR\vdrawCircles\x12\x1d\n" +
	"\n" +
	"draw_lines\x18\x03 \x01(\bR\tdrawLines\x12#\n" +
	"\rinvert_colors\x18\x04 \x01(\bR\finvertColors\x12!\n" +
	"\fgrid_spacing\x18\x05 \x01(\x01R\vgridSpacing\x1a3\n" +
	"\vCustomColor\x12$\n" +
	"\x05color\x18\x01 \x01(\v2\x0e.rv.data.ColorR\x05color\x1a.\n" +
	"\x0eIntensityColor\x12\x1c\n" +
	"\tintensity\x18\x01 \x01(\x01R\tintensity\"\xaa\x01\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fTYPE_BLEND_GRID\x10\x01\x12\x13\n" +
	"\x0fTYPE_COLOR_BARS\x10\x02\x12\x0e\n" +
	"\n" +
	"TYPE_FOCUS\x10\x03\x12\x13\n" +
	"\x0fTYPE_GRAY_SCALE\x10\x04\x12\x14\n" +
	"\x10TYPE_BLACK_COLOR\x10\x05\x12\x14\n" +
	"\x10TYPE_WHITE_COLOR\x10\x06\x12\x15\n" +
	"\x11TYPE_CUSTOM_COLOR\x10\aB\x13\n" +
	"\x11PatternPropertiesB\x96\x01\n" +
	"\vcom.rv.dataB\x10TestPatternProtoP\x01Z8github.com/thatguycleeb/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_testPattern_proto_rawDescOnce sync.Once
	file_testPattern_proto_rawDescData []byte
)

func file_testPattern_proto_rawDescGZIP() []byte {
	file_testPattern_proto_rawDescOnce.Do(func() {
		file_testPattern_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testPattern_proto_rawDesc), len(file_testPattern_proto_rawDesc)))
	})
	return file_testPattern_proto_rawDescData
}

var file_testPattern_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testPattern_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testPattern_proto_goTypes = []any{
	(TestPattern_Type)(0),              // 0: rv.data.TestPattern.Type
	(*TestPattern)(nil),                // 1: rv.data.TestPattern
	(*TestPattern_BlendGrid)(nil),      // 2: rv.data.TestPattern.BlendGrid
	(*TestPattern_CustomColor)(nil),    // 3: rv.data.TestPattern.CustomColor
	(*TestPattern_IntensityColor)(nil), // 4: rv.data.TestPattern.IntensityColor
	(*Color)(nil),                      // 5: rv.data.Color
}
var file_testPattern_proto_depIdxs = []int32{
	0, // 0: rv.data.TestPattern.type:type_name -> rv.data.TestPattern.Type
	2, // 1: rv.data.TestPattern.blend_grid:type_name -> rv.data.TestPattern.BlendGrid
	3, // 2: rv.data.TestPattern.custom_color:type_name -> rv.data.TestPattern.CustomColor
	4, // 3: rv.data.TestPattern.intensity:type_name -> rv.data.TestPattern.IntensityColor
	5, // 4: rv.data.TestPattern.CustomColor.color:type_name -> rv.data.Color
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_testPattern_proto_init() }
func file_testPattern_proto_init() {
	if File_testPattern_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_testPattern_proto_msgTypes[0].OneofWrappers = []any{
		(*TestPattern_BlendGrid_)(nil),
		(*TestPattern_CustomColor_)(nil),
		(*TestPattern_Intensity)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testPattern_proto_rawDesc), len(file_testPattern_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testPattern_proto_goTypes,
		DependencyIndexes: file_testPattern_proto_depIdxs,
		EnumInfos:         file_testPattern_proto_enumTypes,
		MessageInfos:      file_testPattern_proto_msgTypes,
	}.Build()
	File_testPattern_proto = out.File
	file_testPattern_proto_goTypes = nil
	file_testPattern_proto_depIdxs = nil
}
