// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: workspace.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workspace_UnitScaling_UnitType int32

const (
	Workspace_UnitScaling_UNIT_TYPE_POINTS      Workspace_UnitScaling_UnitType = 0
	Workspace_UnitScaling_UNIT_TYPE_MILLIMETERS Workspace_UnitScaling_UnitType = 1
	Workspace_UnitScaling_UNIT_TYPE_CENTIMETERS Workspace_UnitScaling_UnitType = 2
	Workspace_UnitScaling_UNIT_TYPE_METERS      Workspace_UnitScaling_UnitType = 3
	Workspace_UnitScaling_UNIT_TYPE_INCHES      Workspace_UnitScaling_UnitType = 4
	Workspace_UnitScaling_UNIT_TYPE_FEET        Workspace_UnitScaling_UnitType = 5
)

// Enum value maps for Workspace_UnitScaling_UnitType.
var (
	Workspace_UnitScaling_UnitType_name = map[int32]string{
		0: "UNIT_TYPE_POINTS",
		1: "UNIT_TYPE_MILLIMETERS",
		2: "UNIT_TYPE_CENTIMETERS",
		3: "UNIT_TYPE_METERS",
		4: "UNIT_TYPE_INCHES",
		5: "UNIT_TYPE_FEET",
	}
	Workspace_UnitScaling_UnitType_value = map[string]int32{
		"UNIT_TYPE_POINTS":      0,
		"UNIT_TYPE_MILLIMETERS": 1,
		"UNIT_TYPE_CENTIMETERS": 2,
		"UNIT_TYPE_METERS":      3,
		"UNIT_TYPE_INCHES":      4,
		"UNIT_TYPE_FEET":        5,
	}
)

func (x Workspace_UnitScaling_UnitType) Enum() *Workspace_UnitScaling_UnitType {
	p := new(Workspace_UnitScaling_UnitType)
	*p = x
	return p
}

func (x Workspace_UnitScaling_UnitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Workspace_UnitScaling_UnitType) Descriptor() protoreflect.EnumDescriptor {
	return file_workspace_proto_enumTypes[0].Descriptor()
}

func (Workspace_UnitScaling_UnitType) Type() protoreflect.EnumType {
	return &file_workspace_proto_enumTypes[0]
}

func (x Workspace_UnitScaling_UnitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Workspace_UnitScaling_UnitType.Descriptor instead.
func (Workspace_UnitScaling_UnitType) EnumDescriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{0, 1, 0}
}

type Workspace struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	Uuid                 *UUID                       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Muted                bool                        `protobuf:"varint,2,opt,name=muted,proto3" json:"muted,omitempty"`
	Hidden               bool                        `protobuf:"varint,3,opt,name=hidden,proto3" json:"hidden,omitempty"`
	EditorBackground     *Workspace_EditorBackground `protobuf:"bytes,4,opt,name=editor_background,json=editorBackground,proto3" json:"editor_background,omitempty"`
	EffectPresetUuid     *UUID                       `protobuf:"bytes,5,opt,name=effect_preset_uuid,json=effectPresetUuid,proto3" json:"effect_preset_uuid,omitempty"`
	EffectBuildDuration  float64                     `protobuf:"fixed64,6,opt,name=effect_build_duration,json=effectBuildDuration,proto3" json:"effect_build_duration,omitempty"`
	Transition           *Transition                 `protobuf:"bytes,7,opt,name=transition,proto3" json:"transition,omitempty"`
	ActiveMaskUuid       *UUID                       `protobuf:"bytes,8,opt,name=active_mask_uuid,json=activeMaskUuid,proto3" json:"active_mask_uuid,omitempty"`
	Playlist             *Playlist                   `protobuf:"bytes,9,opt,name=playlist,proto3" json:"playlist,omitempty"`
	UnitScaling          *Workspace_UnitScaling      `protobuf:"bytes,10,opt,name=unit_scaling,json=unitScaling,proto3" json:"unit_scaling,omitempty"`
	Effects              []*Effect                   `protobuf:"bytes,16,rep,name=effects,proto3" json:"effects,omitempty"`
	Masks                []*Mask                     `protobuf:"bytes,17,rep,name=masks,proto3" json:"masks,omitempty"`
	Screens              []*Screen                   `protobuf:"bytes,18,rep,name=screens,proto3" json:"screens,omitempty"`
	EdgeBlends           []*EdgeBlend                `protobuf:"bytes,19,rep,name=edge_blends,json=edgeBlends,proto3" json:"edge_blends,omitempty"`
	Layers               []*Layer                    `protobuf:"bytes,20,rep,name=layers,proto3" json:"layers,omitempty"`
	TargetSets           []*TargetSet                `protobuf:"bytes,21,rep,name=target_sets,json=targetSets,proto3" json:"target_sets,omitempty"`
	HotKeys              []*HotKey                   `protobuf:"bytes,22,rep,name=hot_keys,json=hotKeys,proto3" json:"hot_keys,omitempty"`
	Calendar             *Calendar                   `protobuf:"bytes,23,opt,name=calendar,proto3" json:"calendar,omitempty"`
	AlignmentGuides      []*AlignmentGuide           `protobuf:"bytes,24,rep,name=alignment_guides,json=alignmentGuides,proto3" json:"alignment_guides,omitempty"`
	LiveVideoPlaylist    *LiveVideoPlaylist          `protobuf:"bytes,25,opt,name=live_video_playlist,json=liveVideoPlaylist,proto3" json:"live_video_playlist,omitempty"`
	OutputPreviewDisplay *OutputDisplay              `protobuf:"bytes,26,opt,name=output_preview_display,json=outputPreviewDisplay,proto3" json:"output_preview_display,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *Workspace) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Workspace) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *Workspace) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Workspace) GetEditorBackground() *Workspace_EditorBackground {
	if x != nil {
		return x.EditorBackground
	}
	return nil
}

func (x *Workspace) GetEffectPresetUuid() *UUID {
	if x != nil {
		return x.EffectPresetUuid
	}
	return nil
}

func (x *Workspace) GetEffectBuildDuration() float64 {
	if x != nil {
		return x.EffectBuildDuration
	}
	return 0
}

func (x *Workspace) GetTransition() *Transition {
	if x != nil {
		return x.Transition
	}
	return nil
}

func (x *Workspace) GetActiveMaskUuid() *UUID {
	if x != nil {
		return x.ActiveMaskUuid
	}
	return nil
}

func (x *Workspace) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

func (x *Workspace) GetUnitScaling() *Workspace_UnitScaling {
	if x != nil {
		return x.UnitScaling
	}
	return nil
}

func (x *Workspace) GetEffects() []*Effect {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *Workspace) GetMasks() []*Mask {
	if x != nil {
		return x.Masks
	}
	return nil
}

func (x *Workspace) GetScreens() []*Screen {
	if x != nil {
		return x.Screens
	}
	return nil
}

func (x *Workspace) GetEdgeBlends() []*EdgeBlend {
	if x != nil {
		return x.EdgeBlends
	}
	return nil
}

func (x *Workspace) GetLayers() []*Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *Workspace) GetTargetSets() []*TargetSet {
	if x != nil {
		return x.TargetSets
	}
	return nil
}

func (x *Workspace) GetHotKeys() []*HotKey {
	if x != nil {
		return x.HotKeys
	}
	return nil
}

func (x *Workspace) GetCalendar() *Calendar {
	if x != nil {
		return x.Calendar
	}
	return nil
}

func (x *Workspace) GetAlignmentGuides() []*AlignmentGuide {
	if x != nil {
		return x.AlignmentGuides
	}
	return nil
}

func (x *Workspace) GetLiveVideoPlaylist() *LiveVideoPlaylist {
	if x != nil {
		return x.LiveVideoPlaylist
	}
	return nil
}

func (x *Workspace) GetOutputPreviewDisplay() *OutputDisplay {
	if x != nil {
		return x.OutputPreviewDisplay
	}
	return nil
}

type Workspace_EditorBackground struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Frame         *Graphics_Rect         `protobuf:"bytes,2,opt,name=frame,proto3" json:"frame,omitempty"`
	Url           *URL                   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Opacity       float64                `protobuf:"fixed64,4,opt,name=opacity,proto3" json:"opacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace_EditorBackground) Reset() {
	*x = Workspace_EditorBackground{}
	mi := &file_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace_EditorBackground) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace_EditorBackground) ProtoMessage() {}

func (x *Workspace_EditorBackground) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace_EditorBackground.ProtoReflect.Descriptor instead.
func (*Workspace_EditorBackground) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Workspace_EditorBackground) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Workspace_EditorBackground) GetFrame() *Graphics_Rect {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *Workspace_EditorBackground) GetUrl() *URL {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *Workspace_EditorBackground) GetOpacity() float64 {
	if x != nil {
		return x.Opacity
	}
	return 0
}

type Workspace_UnitScaling struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Length        float64                        `protobuf:"fixed64,1,opt,name=length,proto3" json:"length,omitempty"`
	Unit          Workspace_UnitScaling_UnitType `protobuf:"varint,2,opt,name=unit,proto3,enum=rv.data.Workspace_UnitScaling_UnitType" json:"unit,omitempty"`
	Points        float64                        `protobuf:"fixed64,3,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace_UnitScaling) Reset() {
	*x = Workspace_UnitScaling{}
	mi := &file_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace_UnitScaling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace_UnitScaling) ProtoMessage() {}

func (x *Workspace_UnitScaling) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace_UnitScaling.ProtoReflect.Descriptor instead.
func (*Workspace_UnitScaling) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Workspace_UnitScaling) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Workspace_UnitScaling) GetUnit() Workspace_UnitScaling_UnitType {
	if x != nil {
		return x.Unit
	}
	return Workspace_UnitScaling_UNIT_TYPE_POINTS
}

func (x *Workspace_UnitScaling) GetPoints() float64 {
	if x != nil {
		return x.Points
	}
	return 0
}

var File_workspace_proto protoreflect.FileDescriptor

const file_workspace_proto_rawDesc = "" +
	"\n" +
	"\x0fworkspace.proto\x12\arv.data\x1a\reffects.proto\x1a\vmasks.proto\x1a\rscreens.proto\x1a\flayers.proto\x1a\rtargets.proto\x1a\x0eplaylist.proto\x1a\fhotKey.proto\x1a\x10basicTypes.proto\x1a\x0ecalendar.proto\x1a\x14alignmentGuide.proto\x1a\x17liveVideoPlaylist.proto\x1a\x12graphicsData.proto\"\xf2\v\n" +
	"\tWorkspace\x12!\n" +
	"\x04uuid\x18\x01 \x01(\v2\r.rv.data.UUIDR\x04uuid\x12\x14\n" +
	"\x05muted\x18\x02 \x01(\bR\x05muted\x12\x16\n" +
	"\x06hidden\x18\x03 \x01(\bR\x06hidden\x12P\n" +
	"\x11editor_background\x18\x04 \x01(\v2#.rv.data.Workspace.EditorBackgroundR\x10editorBackground\x12;\n" +
	"\x12effect_preset_uuid\x18\x05 \x01(\v2\r.rv.data.UUIDR\x10effectPresetUuid\x122\n" +
	"\x15effect_build_duration\x18\x06 \x01(\x01R\x13effectBuildDuration\x123\n" +
	"\n" +
	"transition\x18\a \x01(\v2\x13.rv.data.TransitionR\n" +
	"transition\x127\n" +
	"\x10active_mask_uuid\x18\b \x01(\v2\r.rv.data.UUIDR\x0eactiveMaskUuid\x12-\n" +
	"\bplaylist\x18\t \x01(\v2\x11.rv.data.PlaylistR\bplaylist\x12A\n" +
	"\funit_scaling\x18\n" +
	" \x01(\v2\x1e.rv.data.Workspace.UnitScalingR\vunitScaling\x12)\n" +
	"\aeffects\x18\x10 \x03(\v2\x0f.rv.data.EffectR\aeffects\x12#\n" +
	"\x05masks\x18\x11 \x03(\v2\r.rv.data.MaskR\x05masks\x12)\n" +
	"\ascreens\x18\x12 \x03(\v2\x0f.rv.data.ScreenR\ascreens\x123\n" +
	"\vedge_blends\x18\x13 \x03(\v2\x12.rv.data.EdgeBlendR\n" +
	"edgeBlends\x12&\n" +
	"\x06layers\x18\x14 \x03(\v2\x0e.rv.data.LayerR\x06layers\x123\n" +
	"\vtarget_sets\x18\x15 \x03(\v2\x12.rv.data.TargetSetR\n" +
	"targetSets\x12*\n" +
	"\bhot_keys\x18\x16 \x03(\v2\x0f.rv.data.HotKeyR\ahotKeys\x12-\n" +
	"\bcalendar\x18\x17 \x01(\v2\x11.rv.data.CalendarR\bcalendar\x12B\n" +
	"\x10alignment_guides\x18\x18 \x03(\v2\x17.rv.data.AlignmentGuideR\x0falignmentGuides\x12J\n" +
	"\x13live_video_playlist\x18\x19 \x01(\v2\x1a.rv.data.LiveVideoPlaylistR\x11liveVideoPlaylist\x12L\n" +
	"\x16output_preview_display\x18\x1a \x01(\v2\x16.rv.data.OutputDisplayR\x14outputPreviewDisplay\x1a\x94\x01\n" +
	"\x10EditorBackground\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12,\n" +
	"\x05frame\x18\x02 \x01(\v2\x16.rv.data.Graphics.RectR\x05frame\x12\x1e\n" +
	"\x03url\x18\x03 \x01(\v2\f.rv.data.URLR\x03url\x12\x18\n" +
	"\aopacity\x18\x04 \x01(\x01R\aopacity\x1a\x93\x02\n" +
	"\vUnitScaling\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x01R\x06length\x12;\n" +
	"\x04unit\x18\x02 \x01(\x0e2'.rv.data.Workspace.UnitScaling.UnitTypeR\x04unit\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x01R\x06points\"\x96\x01\n" +
	"\bUnitType\x12\x14\n" +
	"\x10UNIT_TYPE_POINTS\x10\x00\x12\x19\n" +
	"\x15UNIT_TYPE_MILLIMETERS\x10\x01\x12\x19\n" +
	"\x15UNIT_TYPE_CENTIMETERS\x10\x02\x12\x14\n" +
	"\x10UNIT_TYPE_METERS\x10\x03\x12\x14\n" +
	"\x10UNIT_TYPE_INCHES\x10\x04\x12\x12\n" +
	"\x0eUNIT_TYPE_FEET\x10\x05B\x94\x01\n" +
	"\vcom.rv.dataB\x0eWorkspaceProtoP\x01Z8github.com/thatguycleeb/propresenter-toolkit/internal/pb\xa2\x02\x03RDX\xaa\x02\aRv.Data\xca\x02\aRv\\Data\xe2\x02\x13Rv\\Data\\GPBMetadata\xea\x02\bRv::Datab\x06proto3"

var (
	file_workspace_proto_rawDescOnce sync.Once
	file_workspace_proto_rawDescData []byte
)

func file_workspace_proto_rawDescGZIP() []byte {
	file_workspace_proto_rawDescOnce.Do(func() {
		file_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_proto_rawDesc), len(file_workspace_proto_rawDesc)))
	})
	return file_workspace_proto_rawDescData
}

var file_workspace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_workspace_proto_goTypes = []any{
	(Workspace_UnitScaling_UnitType)(0), // 0: rv.data.Workspace.UnitScaling.UnitType
	(*Workspace)(nil),                   // 1: rv.data.Workspace
	(*Workspace_EditorBackground)(nil),  // 2: rv.data.Workspace.EditorBackground
	(*Workspace_UnitScaling)(nil),       // 3: rv.data.Workspace.UnitScaling
	(*UUID)(nil),                        // 4: rv.data.UUID
	(*Transition)(nil),                  // 5: rv.data.Transition
	(*Playlist)(nil),                    // 6: rv.data.Playlist
	(*Effect)(nil),                      // 7: rv.data.Effect
	(*Mask)(nil),                        // 8: rv.data.Mask
	(*Screen)(nil),                      // 9: rv.data.Screen
	(*EdgeBlend)(nil),                   // 10: rv.data.EdgeBlend
	(*Layer)(nil),                       // 11: rv.data.Layer
	(*TargetSet)(nil),                   // 12: rv.data.TargetSet
	(*HotKey)(nil),                      // 13: rv.data.HotKey
	(*Calendar)(nil),                    // 14: rv.data.Calendar
	(*AlignmentGuide)(nil),              // 15: rv.data.AlignmentGuide
	(*LiveVideoPlaylist)(nil),           // 16: rv.data.LiveVideoPlaylist
	(*OutputDisplay)(nil),               // 17: rv.data.OutputDisplay
	(*Graphics_Rect)(nil),               // 18: rv.data.Graphics.Rect
	(*URL)(nil),                         // 19: rv.data.URL
}
var file_workspace_proto_depIdxs = []int32{
	4,  // 0: rv.data.Workspace.uuid:type_name -> rv.data.UUID
	2,  // 1: rv.data.Workspace.editor_background:type_name -> rv.data.Workspace.EditorBackground
	4,  // 2: rv.data.Workspace.effect_preset_uuid:type_name -> rv.data.UUID
	5,  // 3: rv.data.Workspace.transition:type_name -> rv.data.Transition
	4,  // 4: rv.data.Workspace.active_mask_uuid:type_name -> rv.data.UUID
	6,  // 5: rv.data.Workspace.playlist:type_name -> rv.data.Playlist
	3,  // 6: rv.data.Workspace.unit_scaling:type_name -> rv.data.Workspace.UnitScaling
	7,  // 7: rv.data.Workspace.effects:type_name -> rv.data.Effect
	8,  // 8: rv.data.Workspace.masks:type_name -> rv.data.Mask
	9,  // 9: rv.data.Workspace.screens:type_name -> rv.data.Screen
	10, // 10: rv.data.Workspace.edge_blends:type_name -> rv.data.EdgeBlend
	11, // 11: rv.data.Workspace.layers:type_name -> rv.data.Layer
	12, // 12: rv.data.Workspace.target_sets:type_name -> rv.data.TargetSet
	13, // 13: rv.data.Workspace.hot_keys:type_name -> rv.data.HotKey
	14, // 14: rv.data.Workspace.calendar:type_name -> rv.data.Calendar
	15, // 15: rv.data.Workspace.alignment_guides:type_name -> rv.data.AlignmentGuide
	16, // 16: rv.data.Workspace.live_video_playlist:type_name -> rv.data.LiveVideoPlaylist
	17, // 17: rv.data.Workspace.output_preview_display:type_name -> rv.data.OutputDisplay
	18, // 18: rv.data.Workspace.EditorBackground.frame:type_name -> rv.data.Graphics.Rect
	19, // 19: rv.data.Workspace.EditorBackground.url:type_name -> rv.data.URL
	0,  // 20: rv.data.Workspace.UnitScaling.unit:type_name -> rv.data.Workspace.UnitScaling.UnitType
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_workspace_proto_init() }
func file_workspace_proto_init() {
	if File_workspace_proto != nil {
		return
	}
	file_effects_proto_init()
	file_masks_proto_init()
	file_screens_proto_init()
	file_layers_proto_init()
	file_targets_proto_init()
	file_playlist_proto_init()
	file_hotKey_proto_init()
	file_basicTypes_proto_init()
	file_calendar_proto_init()
	file_alignmentGuide_proto_init()
	file_liveVideoPlaylist_proto_init()
	file_graphicsData_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_proto_rawDesc), len(file_workspace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workspace_proto_goTypes,
		DependencyIndexes: file_workspace_proto_depIdxs,
		EnumInfos:         file_workspace_proto_enumTypes,
		MessageInfos:      file_workspace_proto_msgTypes,
	}.Build()
	File_workspace_proto = out.File
	file_workspace_proto_goTypes = nil
	file_workspace_proto_depIdxs = nil
}
